#!/usr/bin/env python3
"""Generates the Heroes & Champions data classes (heroes_design.md §12.2, WS-A) from the single source of numbers.

Outputs (only the block between the GENERATED markers is written; hand-written rules outside it are kept):
  scripts/core/ladder.gd         Ladder        gem ladder, F-CAP caps, forms, Awakening, rank steps, budgets
  scripts/core/hero_data.gd      HeroData      roster of 10 heroes (kits, ult / rally numbers), PROGRESS, Feats, unlocks
  scripts/core/champion_data.gd  ChampionData  roster of 12 champions, aura, Champion Level, champion budgets
  scripts/core/team_data.gd      TeamData      classes, elements, factions, tiers, pairs, Affinity, Rally hooks, TEAM_DEMAND
  scripts/core/portal_data.gd    PortalData    Portal odds / pity / Seals / welcome / Beacons, Hero Chests, scripted chests
  scripts/core/ceremony_data.gd  CeremonyData  every ceremony length of §9.4

Sources (all in the repo, so the build is reproducible):
  1. tools/data/heroes_consts.json   exported by heroes_sim.py v2 (export_consts); the numbers.
  2. tools/data/heroes_roster.json   what heroes_consts.json does not carry: the roster rows (ids, native gem, class,
     element, faction, kit numbers) from heroes_sim.py HEROES / CHAMPS + heroes_tables.py KITS / ULT / RALLY / CHAMPS,
     ult kinds + collector numbers from heroes_design.md §6.0, and oracle tables computed by the sim's own rule
     functions (ladder, skill_cap, ult_form, can_awaken, awaken_cap) that scripts/dev/test_heroes.gd checks Ladder with.
     Refreshed with --refresh <dir holding heroes_sim.py + heroes_tables.py + heroes_consts.json>.
  3. DOC below: a few numbers only the design text carries (each with its § reference).

Every generated constant is listed in its class's SOURCE_KEYS ("consts:<path>", "roster:<path>", "doc:<§>" or
"derived:<rule>"); test_heroes.gd compares every consts: / roster: constant with the JSON value at that path.

Usage
  python3 tools/gen_heroes_data.py                  # regenerate the six blocks
  python3 tools/gen_heroes_data.py --check          # exit 1 when any block (or a json copy) is out of date
  python3 tools/gen_heroes_data.py --refresh [dir]  # rebuild heroes_roster.json from the sims in dir (default tools/;
                                                    # a dir holding heroes_consts.json also re-copies it), regenerate
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "data")
CONSTS_JSON = os.path.join(DATA, "heroes_consts.json")
ROSTER_JSON = os.path.join(DATA, "heroes_roster.json")
DESIGN_MD = os.path.join(ROOT, "docs", "design", "heroes_design.md")
BEGIN = "# <GENERATED by tools/gen_heroes_data.py — edit the json / the generator, never this block>"
END = "# </GENERATED>"
GEMS = ["C", "R", "E", "L", "M"]

# ------------------------------------------------------------------------------------------------ DOC constants
# Values the design text carries and neither json does. Each is quoted from heroes_design.md at the given §.
DOC = {
    # §4.2 clash: the front champion accumulates hit x 0.25 per tick (fractional accumulator, §1.4).
    "CLASH_SHARE": (0.25, "§4.2"),
    # §4.2: x0.5 clash share with a Guardian hero.
    "CLASH_SHARE_GUARDIAN_HERO": (0.5, "§4.2"),
    # §4.1: Champion Level cap 2 + 2 x world_reached, 20 in Invasion (= heroes_sim champ_cap).
    "CL_CAP_BASE": (2, "§4.1"),
    "CL_CAP_PER_WORLD": (2, "§4.1"),
    # §5.1 class order (TeamData.CLASSES) and §5.2 elements (= ArsenalData.FAMILY_ORDER without rift).
    "CLASSES": (["warrior", "ranger", "mage", "guardian", "healer"], "§5.1"),
    "ELEMENTS": (["kinetic", "volt", "frost", "plasma", "tech", "rune"], "§5.2"),
    # §5.3 faction tier effects in the run (index 0 = no tier; I / II / III = 2 / 3 / 4 members).
    "FACTION_RUN": ({"dawn": {"stat": "siege_reserves", "tiers": [0, 4, 8, 14]},
                     "wildfang": {"stat": "ult_charge", "tiers": [0.0, 0.06, 0.12, 0.20]},
                     "stoneheart": {"stat": "hazard_losses", "tiers": [0.0, -0.15, -0.30, -0.45]},
                     "celestial": {"stat": "machine_damage_b2", "tiers": [0.0, 0.03, 0.06, 0.10]}}, "§5.3"),
    "FACTION_MEMBERS_FOR_TIER": ([0, 2, 3, 4], "§5.3"),
    # §5.1 pair bonus (2 of the class) in the run.
    "CLASS_PAIR_RUN": ({"warrior": {"squad_clash_loss": 0.12},
                        "ranger": {"hero_rate": 0.05, "ranger_champion_cooldown": -0.15},
                        "mage": {"ult_effect": 0.08},
                        "guardian": {"champion_hp": 0.25, "block_cooldown": -0.20},
                        "healer": {"revive_pool": 0.25, "mend_rate": 0.20}}, "§5.1"),
    # §5.4 Rally hooks: target and how the value applies (add / mul); bases of the used hooks come from the roster.
    "RALLY_HOOK_TARGETS": ({"army_scrape": ["Army.scrape_spare", "add"], "army_drill": ["Army.drill_mult", "add"],
                            "machines_element": ["Weapons._b2", "add"], "champions_hp": ["champion.hp", "mul"],
                            "ult_start": ["tactics.ult_start", "add"], "machines_verb": ["Weapons._b2", "add"],
                            "army_reserves": ["Army.reserves", "add"], "army_volleys": ["Army.volley_mult", "mul"],
                            "champions_aura": ["champion.aura", "mul"], "army_recruits": ["Army.recruits", "add"],
                            "ult_charge": ["ult.charge_rate", "mul"]}, "§5.4"),
    # §5.4: the two hooks no hero uses yet (free for future heroes) and their bases.
    "RALLY_FREE_BASES": ({"army_recruits": 1.0, "ult_charge": 0.05}, "§5.4"),
    "ULT_START_CAP": (0.40, "§5.4"),
    # §7.1 / §7.4 Portal costs.
    "BEACONS_PER_SUMMON": (1, "§7.1"),
    "X10_SUMMONS": (10, "§7.1"),
    "SEALS_PER_SUMMON": (1, "§7.4"),
    # §7.5: the hero-fragment card targets owned heroes, the team hero at x2 weight (= heroes_sim roll weights).
    "CHEST_TEAM_HERO_WEIGHT": (2, "§7.5"),
    # §7.5: the Grand chest's last card is drawn among Amethyst+ only; chest pity forces a Topaz card.
    "GRAND_LAST_CARD_MIN": ("E", "§7.5"),
    "CHEST_PITY_GEM": ("L", "§7.5"),
    # §9.4 Fast ceremonies / Quick reveal and Reduce Motion columns (keys as heroes_consts.json "ceremony").
    "CEREMONY_FAST": ({"x1": [1.2, 1.2], "short_walkout": 1.2, "seal_pick_new": 1.2, "seal_pick_owned": 1.2,
                       "chest_inline": 1.6, "chest_inline_dup": 1.2, "cameo": 1.0, "cameo_next": 1.0,
                       "full_facets": 0.8, "recut": 1.5, "skill": 0.3, "form": 0.8, "awaken": 1.5, "craft": 0.6,
                       "temper_tier": 0.6, "temper_beat": 0.6, "team_ready": 0.2}, "§9.4"),
    "CEREMONY_REDUCED": ({"x1": [0.2, 0.2], "walkout_static_max": 1.0, "facet": 0.2, "full_facets": 0.5, "recut": 0.6,
                          "skill": 0.2, "form": 0.5, "awaken": 0.6, "craft": 0.35, "temper_tier": 0.35,
                          "temper_beat": 0.35}, "§9.4"),
    "TEAM_READY": (0.4, "§9.4"),
    "SKIP_FROM": (0.5, "§9.4 / §7.1"),
}


# ------------------------------------------------------------------------------------------------ refresh
def _parse_roster_tables(md: str) -> tuple[dict, dict]:
    """heroes_design.md §6.0: hero rows (№, ult kind, second element of form V) and champion rows (№)."""
    sec = md[md.index("### 6.0 At a glance"):md.index("### 6.1 ")]
    heroes, champs = {}, {}
    for line in sec.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 10 or not re.fullmatch(r"\d\d", cells[0]):
            continue
        cid = cells[1].strip("`")
        no = int(cells[0])
        if len(cells) == 12:   # hero table: № id Name Title Gem Class Element Faction Species Niche Ult Source
            m = re.search(r"\(\+(\w+) in V\)", cells[6])
            heroes[cid] = {"no": no, "ult": cells[10].strip("`"), "element2": m.group(1).lower() if m else "",
                           "niche": "" if cells[9] in ("—", "-") else cells[9].strip("`")}
        else:
            champs[cid] = {"no": no}
    if len(heroes) != 10 or len(champs) != 12:
        sys.exit("heroes_design.md §6.0 tables changed shape (%d heroes, %d champions)" % (len(heroes), len(champs)))
    return heroes, champs


def _gem_dict(d: dict) -> dict:
    """{gem: p} in gem order with every gem of the table present (0.0 when absent)."""
    keys = [g for g in GEMS if g in d] if len(d) < 5 else GEMS
    return {g: float(d.get(g, 0.0)) for g in keys}


def _low(s: str) -> str:
    s = s.lower()
    return "celestial" if s == "celestials" else s


def refresh(src_dir: str) -> None:
    """Rebuilds heroes_roster.json from the sim, the tables script and §6.0 (and copies heroes_consts.json when
    `src_dir` holds one; the repo copies of the sims in tools/ do not, so tools/data/heroes_consts.json stays)."""
    sim_path = os.path.join(src_dir, "heroes_sim.py")
    for p in (sim_path, os.path.join(src_dir, "heroes_tables.py")):
        if not os.path.exists(p):
            sys.exit("--refresh: %s not found" % p)
    os.makedirs(DATA, exist_ok=True)
    src_consts = os.path.join(src_dir, "heroes_consts.json")
    if os.path.exists(src_consts):
        shutil.copyfile(src_consts, CONSTS_JSON)
    sys.path.insert(0, src_dir)
    sys.dont_write_bytecode = True
    argv, sys.argv = sys.argv, [sim_path]
    import heroes_sim as H  # noqa: E402
    import heroes_tables as T  # noqa: E402
    sys.argv = argv
    doc_h, doc_c = _parse_roster_tables(open(DESIGN_MD, encoding="utf-8").read())

    heroes = {}
    for row in T.KITS:
        hid, _uk, n, cls, el, fac, hp, rate, dmg, splash, rng, targets, charge = row
        s = H.HEROES[hid]
        if (s["n"], s["cls"], s["el"], s["fac"]) != (n, _low(cls), _low(el), _low(fac)):
            sys.exit("heroes_tables.KITS[%s] disagrees with heroes_sim.HEROES" % hid)
        hook, base, note = T.RALLY[hid]
        m = re.fullmatch(r"(\w+)(?: \((\w+)\))?", hook)
        u2 = T.ULT2.get(hid)
        heroes[hid] = {
            "no": doc_h[hid]["no"], "native": GEMS[n], "class": s["cls"], "element": s["el"],
            "element2": doc_h[hid]["element2"], "faction": s["fac"], "niche": doc_h[hid]["niche"],
            "ult": doc_h[hid]["ult"],
            "kit": {"hp": hp, "rate": rate, "dmg": dmg, "splash": splash, "range": rng, "targets": targets,
                    "ult_charge": charge},
            "ult_main": {"value": T.ULT[hid][0], "note": T.ULT[hid][1]},
            "ult2": {"value": u2[0], "note": u2[1], "rank": u2[2]} if u2 else {},
            "rally": {"hook": m.group(1), "param": (m.group(2) or "").lower(), "base": float(base), "note": note},
        }
    if list(heroes) != list(H.HEROES):
        sys.exit("hero order differs between heroes_tables.KITS and heroes_sim.HEROES")
    champs = {}
    for row in T.CHAMPS:
        cid, _uk, n, cls, el, fac, hp, action, a_note, aura, au_note, radius, slot = row
        s = H.CHAMPS[cid]
        if (s["n"], s["cls"], s["el"], s["fac"]) != (n, _low(cls), _low(el), _low(fac)):
            sys.exit("heroes_tables.CHAMPS[%s] disagrees with heroes_sim.CHAMPS" % cid)
        champs[cid] = {"no": doc_c[cid]["no"], "native": GEMS[n], "class": s["cls"], "element": s["el"],
                       "faction": s["fac"], "slot": slot,
                       "kit": {"hp": hp, "action": action, "aura": aura, "radius": radius},
                       "action_note": a_note, "aura_note": au_note}
    if list(champs) != list(H.CHAMPS):
        sys.exit("champion order differs between heroes_tables.CHAMPS and heroes_sim.CHAMPS")

    home: dict = {f: [] for f in H.FACTIONS}
    for w, f in sorted(H.HOME.items()):
        home[f].append(w)
    rng5 = range(5)
    import economy_sim as E  # noqa: E402  (the sim's own import; Meta-1 power weights)
    portal_cons, portal_dist = H.portal_exact()
    oracle = {
        "ladder": [[[H.ladder(n, g, f) if g >= n else None for f in range(H.F + 1)] for g in rng5] for n in rng5],
        "skill_cap": [[[H.skill_cap(n, g, f) if g >= n else None for f in range(H.F + 1)] for g in rng5] for n in rng5],
        "ult_form": [[H.ult_form(n, r) for r in range(1, 12)] for n in rng5],
        "can_awaken": [[[H.can_awaken(n, g, f) if g >= n else None for f in range(H.F + 1)] for g in rng5] for n in rng5],
        "awaken_cap": [[H.awaken_cap(n, g) if g >= n else None for g in rng5] for n in rng5],
        "champ_level_cost": [H.champ_level_cost(L) for L in range(1, H.CHAMP_LEVEL_MAX)],
        "chest_hero_card_frags": [int(H.CHEST_HERO_CARD * d + 0.5) for d in H.DUP_FRAGS],
        "portal_pl": [H.portal_pl(s) for s in range(H.PITY_L_HARD + 1)],
        # exact odds tables the sim prints (§7.2, §7.5): consolidated gems over the stationary pity chain, best gem of a
        # x10 (fresh pity, the welcome rule, the stationary start), best chest card; Summon / HeroChest must match them
        "portal_consolidated": {g: v for g, v in sorted(portal_cons.items(), key=lambda kv: H.GI[kv[0]])},
        "portal_x10_fresh": _gem_dict(H.portal_x10_best((0, 0), False)),
        "portal_x10_welcome": _gem_dict(H.portal_x10_best((0, 0), True)),
        "portal_x10_stationary": _gem_dict(H.portal_x10_best_stationary(portal_dist)),
        "chest_best": {k: _gem_dict(H.chest_exact_best(k)) for k in ("hero", "grand")},
    }
    # power-index terms the sim keeps in code (team_power / _synergy), for Team.score (Auto-team)
    pair = {}
    for cls in ("guardian", "ranger"):
        pair.update(H._synergy([(cls, "a", "x"), (cls, "b", "y")])["champ_cls"])
    index_terms = {"power_w": {"mach": E.W_MACH, "hero": E.W_HERO, "army": E.W_ARMY, "b2_eff": H.B2_EFF},
                   "champ_cls_pair": pair}
    data = {
        "_source": "heroes_sim.py v2 + heroes_tables.py + heroes_design.md §6.0 via tools/gen_heroes_data.py --refresh",
        "gems": {"keys": H.G, "uk": H.GEM_UK, "en": H.GEM_EN},
        "hero_max_gem": GEMS[H.HERO_MAX_GEM], "champion_max_gem": GEMS[H.CHAMP_MAX_GEM],
        "atk_beats": list(H.ATK_BEATS),
        "hero_order": list(heroes), "champion_order": list(champs),
        "starters": list(H.STARTERS),
        "start_owned": [h for h, d in H.HEROES.items() if d.get("starter") == 0],
        "starter_at": {h: d["starter"] for h, d in H.HEROES.items() if "starter" in d},
        "scripted_chests": {"first": dict(H.SCRIPTED_FIRST), "first_default": H.SCRIPTED_FIRST_DEFAULT,
                            "second": H.SCRIPTED_SECOND},
        "factions": list(H.FACTIONS), "faction_home": home,
        "aura_share": dict(T.AURA_SHARE), "aura_cap": T.AURA_CAP,
        "heroes": heroes, "champions": champs, "index_terms": index_terms, "oracle": oracle,
    }
    with open(ROSTER_JSON, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print("refreshed %s and %s" % (os.path.relpath(CONSTS_JSON, ROOT), os.path.relpath(ROSTER_JSON, ROOT)))


# ------------------------------------------------------------------------------------------------ GDScript literals
def _gd(v, as_float: bool = False) -> str:
    """Python value -> GDScript literal (dicts keep insertion order)."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int) and not as_float:
        return str(v)
    if isinstance(v, (int, float)):
        r = repr(float(v))
        return r if ("." in r or "e" in r or "inf" in r or "nan" in r) else r + ".0"
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False)
    if isinstance(v, (list, tuple)):
        fl = any(isinstance(x, float) for x in v) and all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in v)
        return "[" + ", ".join(_gd(x, fl) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join("%s: %s" % (_gd(k), _gd(x)) for k, x in v.items()) + "}"
    raise TypeError(repr(v))


def _scalar_kind(xs) -> str:
    xs = list(xs)
    if not xs:
        return ""
    if all(isinstance(x, bool) for x in xs):
        return "bool"
    if all(isinstance(x, int) and not isinstance(x, bool) for x in xs):
        return "int"
    if all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in xs):
        return "float"
    if all(isinstance(x, str) for x in xs):
        return "String"
    return ""


def _const(name: str, v) -> str:
    """Typed const line: scalars, homogeneous Array[T], homogeneous flat Dictionary[String, T]."""
    if isinstance(v, bool):
        return "const %s := %s" % (name, _gd(v))
    if isinstance(v, int):
        return "const %s: int = %s" % (name, _gd(v))
    if isinstance(v, float):
        return "const %s: float = %s" % (name, _gd(v))
    if isinstance(v, str):
        return "const %s: String = %s" % (name, _gd(v))
    if isinstance(v, (list, tuple)):
        k = _scalar_kind(v)
        if k:
            return "const %s: Array[%s] = [%s]" % (name, k, ", ".join(_gd(x, k == "float") for x in v))
        return "const %s: Array = %s" % (name, _gd(v))
    if isinstance(v, dict):
        k = _scalar_kind(v.values())
        if k and all(isinstance(x, str) for x in v):
            return "const %s: Dictionary[String, %s] = {%s}" % (
                name, k, ", ".join("%s: %s" % (_gd(a), _gd(b, k == "float")) for a, b in v.items()))
        return "const %s: Dictionary = %s" % (name, _gd(v))
    raise TypeError(name)


class Block:
    """Collects the const lines and the SOURCE_KEYS table of one generated block."""

    def __init__(self, consts: dict, roster: dict):
        self.c, self.r = consts, roster
        self.lines: list[str] = []
        self.src: dict[str, str] = {}

    @staticmethod
    def _at(root, path: str):
        v = root
        for p in path.split("."):
            v = v[p]
        return v

    def head(self, text: str) -> None:
        self.lines += ["", "# ---- " + text]

    def doc(self, text: str) -> None:
        self.lines += ["## " + t for t in text.split("\n")]

    def emit(self, name: str, value, source: str, comment: str = "") -> None:
        if comment:
            self.doc(comment)
        self.lines.append(_const(name, value))
        self.src[name] = source

    def consts(self, name: str, path: str, comment: str = "") -> None:
        self.emit(name, self._at(self.c, path), "consts:" + path, comment)

    def roster(self, name: str, path: str, comment: str = "") -> None:
        self.emit(name, self._at(self.r, path), "roster:" + path, comment)

    def docv(self, name: str, comment: str = "") -> None:
        v, ref = DOC[name]
        self.emit(name, v, "doc:" + ref, comment + (" " if comment else "") + "(heroes_design.md %s)" % ref)

    def rows(self, name: str, path: str, order: list, comment_of) -> None:
        """A roster dictionary written one row per line with a trailing comment."""
        rows = self._at(self.r, path)
        self.lines.append("const %s: Dictionary = {" % name)
        for k in order:
            self.lines.append("\t%s: %s,  # %s" % (_gd(k), _gd(rows[k]), comment_of(k, rows[k])))
        self.lines.append("}")
        self.src[name] = "roster:" + path

    def text(self, stamp: str) -> str:
        out = [BEGIN, "## " + stamp] + self.lines
        out += ["", "## Where every generated constant comes from: consts:<path> = tools/data/heroes_consts.json,",
                "## roster:<path> = tools/data/heroes_roster.json (both checked by scripts/dev/test_heroes.gd),",
                "## doc:<§> = heroes_design.md, derived:<rule> = computed by the generator from the json."]
        out.append("const SOURCE_KEYS: Dictionary[String, String] = {")
        out += ["\t%s: %s," % (_gd(k), _gd(v)) for k, v in self.src.items()]
        out += ["}", END]
        return "\n".join(out)


# ------------------------------------------------------------------------------------------------ the six blocks
def block_ladder(b: Block) -> None:
    b.head("gems (keys = the Meta-1 rarity enum; display names come from Loc GEM_C ... GEM_M)")
    b.roster("GEMS", "gems.keys")
    b.roster("GEM_NAME_UK", "gems.uk", "Reference names (Кварц, Сапфір, Аметист, Топаз, Опал); UI copy reads Loc, never these.")
    b.roster("GEM_NAME_EN", "gems.en")
    b.roster("HERO_MAX_GEM", "hero_max_gem")
    b.roster("CHAMPION_MAX_GEM", "champion_max_gem", "Champion recut stops at Topaz (§4.1).")
    b.head("B1 stats: ladder(n, g, f) = NATIVE_MULT[n] x RECUT_STEP^(g - n) x (1 + FACET_STEP f)  (§2.2)")
    for k in ("Q_NATIVE", "FACET_STEP", "NATIVE_MULT", "RECUT_STEP", "CEILING", "FACETS_PER_GEM"):
        b.consts(k, "ladder." + k)
    b.head("B2 skills (F-CAP): skill_cap(n, g, f) = SKILL_BASE[g] - [g > n] + [f == FACETS_PER_GEM]")
    b.consts("SKILL_BASE", "ladder.SKILL_BASE")
    b.head("B3 ult forms: ult_form(n, rank) = min(n + 1, #{FORM_AT_RANK <= rank})")
    b.consts("FORM_AT_RANK", "ladder.FORM_AT_RANK")
    b.head("B4 Awakening (F-AWK2): can_awaken = g >= AWAKEN_MIN_GEM and (f == 5 or (g == n and n >= BORN_AWAKENED_MIN))")
    b.consts("AWAKEN_MIN_GEM", "ladder.AWAKEN_MIN_GEM")
    b.consts("AWAKEN_CAP", "ladder.AWAKEN_CAP", "awaken_cap(n, g) = AWAKEN_CAP[g] - [g > n] (0 below AWAKEN_MIN_GEM).")
    b.consts("BORN_AWAKENED_MIN", "ladder.BORN_AWAKENED_MIN")
    b.head("rank steps and the hero level curve (§3.1, §3.3)")
    for k in ("ULT_RANK_STEP", "ATK_RANK_STEP", "RALLY_RANK_STEP", "LV_DMG", "LV_HP", "LV_RATE", "LV_ULT"):
        b.consts(k, "ladder." + k)
    b.roster("ATK_BEATS", "atk_beats", "Attack rule beats (ranks).")
    b.head("budgets (§2.3 kit profile bands; LevelSim / test_kit_budget)")
    for k in b.c["budgets"]:
        if k not in CHAMPION_BUDGETS:
            b.consts(k, "budgets." + k)


def block_hero(b: Block) -> None:
    b.head("roster (heroes_design.md §6.0; kit = Lv1 rank-1 Quartz-normalised, eff = kit x Ladder.NATIVE_MULT[native])")
    b.roster("HERO_ORDER", "hero_order", "Collector order 01-10.")
    b.doc("id -> {no, native, class, element, element2 (ult form V), faction, niche, ult (kind id), kit {hp, rate, dmg,\n"
          "splash, range, targets, ult_charge}, ult_main {value, note}, ult2 {value, note, rank}, rally {hook, param, base,\n"
          "note}}. Notes are designer notes for tools, never UI copy (names and texts are Loc HERO_<ID>*).")
    b.rows("HEROES", "heroes", b.r["hero_order"], lambda k, v: "%s %s %s" % (v["native"], v["class"], v["ult"]))
    b.roster("STARTERS", "starters")
    b.roster("START_OWNED", "start_owned", "Heroes owned by a brand-new account.")
    b.roster("STARTER_AT", "starter_at", "Starter -> the level after which it joins (0 = from the start; Мейра 24, guest at L5).")
    b.head("unlock levels (after_win; §11.1)")
    b.consts("UNLOCK_AT", "unlocks")
    b.head("PROGRESS (§3.2, §3.3; champions reuse the fragment tables)")
    b.doc("PROGRESS[...] in the design = these constants.")
    for k in ("DUP_FRAGS", "FACET_FRAGS", "RECUT_FRAGS", "RECUT_COINS", "OVERFLOW_FRAGS_PER_TOME", "TOME_COST",
              "SKILL_COINS", "HERO_SYNC_BEHIND", "GEAR_SLOT_AT", "CHRONICLE_PRICES"):
        b.consts(k, "progress." + k, {"FACET_FRAGS": "FACET_FRAGS[g][f] = fragments for facet f -> f + 1 at gem g.",
                                      "TOME_COST": "TOME_COST[r] = Tomes for skill rank r -> r + 1.",
                                      "RECUT_FRAGS": "RECUT_FRAGS[g] = fragments for the recut g -> g + 1."}.get(k, ""))
    b.head("hero Feats (§3.6; pay Tomes, never Beacons)")
    b.consts("FEATS", "feats")


CHAMPION_BUDGETS = ("CL_STEP", "ACTION_TIER_STEP", "C_RELIC", "W_C", "CHAMP_UPTIME", "CHAMP_KIT_TOL")


def block_champion(b: Block) -> None:
    b.head("roster (heroes_design.md §6.0, §4.4; kit = f0 Lv1 Quartz-normalised)")
    b.roster("CHAMPION_ORDER", "champion_order", "Collector order 11-22.")
    b.doc("id -> {no, native, class, element, faction, slot (preferred), kit {hp, action, aura, radius}, action_note,\n"
          "aura_note}. Action tier = native gem index + 1, fixed at birth (§2.2).")
    b.rows("CHAMPIONS", "champions", b.r["champion_order"],
           lambda k, v: "%s %s %s" % (v["native"], v["class"], v["slot"]))
    b.head("aura and clash (§4.2)")
    b.roster("AURA_SHARE", "aura_share", "Fixed aura share per slot, the same in Run and LevelSim (critique X09).")
    b.consts("AURA_CAP", "team.AURA_CAP")
    b.docv("CLASH_SHARE", "The front champion in contact accumulates hit x CLASH_SHARE per tick.")
    b.docv("CLASH_SHARE_GUARDIAN_HERO", "Multiplier on the clash share with a Guardian hero.")
    u = b.c["unlocks"]
    b.emit("SLOTS_AT", {str(u["champions"]): 2, str(u["slot3"]): 3}, "derived:unlocks.champions / unlocks.slot3",
           "Frontier level (after_win) -> champion slots (§4.1).")
    b.head("Champion Level (one shared coin track; §4.1)")
    b.consts("CHAMP_LEVEL_MAX", "progress.CHAMP_LEVEL_MAX")
    b.consts("CHAMP_LEVEL_COST", "progress.CHAMP_LEVEL_COST", "CHAMP_LEVEL_COST[L - 1] = coins for Champion Level L -> L + 1.")
    b.docv("CL_CAP_BASE", "Cap = CL_CAP_BASE + CL_CAP_PER_WORLD x world_reached, CHAMP_LEVEL_MAX in Invasion.")
    b.docv("CL_CAP_PER_WORLD")
    b.head("champion budgets (§4.1, §2.3)")
    for k in CHAMPION_BUDGETS:
        b.consts(k, "budgets." + k)


def block_team(b: Block) -> None:
    b.head("tags (§5.1 - §5.3)")
    b.docv("CLASSES")
    b.docv("ELEMENTS", "= ArsenalData.FAMILY_ORDER without rift.")
    b.roster("FACTIONS", "factions")
    b.roster("FACTION_HOME", "faction_home", "Faction -> home worlds.")
    b.head("synergy as power-index terms (heroes_sim / Might; NOT the run effects)")
    for k in ("FACTION_TIERS", "AFFINITY_PER", "AFFINITY_CAP", "TEAM_B2_CAP", "CLASS_PAIR"):
        b.consts(k, "team." + k, {"FACTION_TIERS": "Index term per tier 0..III (dawn / stoneheart: army term; wildfang:\n"
                                                    "ult charge x; celestial: machine damage, bucket 2).",
                                  "CLASS_PAIR": "Class -> [index stat, value] for 2 of the class.",
                                  "AFFINITY_PER": "Affinity: fielded machines of element E +AFFINITY_PER x living members\n"
                                                  "of E (bucket 2), cap AFFINITY_CAP.",
                                  "TEAM_B2_CAP": "Celestials + Affinity + Rally machine hooks add at most this to one machine."}.get(k, ""))
    b.roster("CHAMP_CLS_PAIR", "index_terms.champ_cls_pair",
             "Class pair -> champion index x for that class (Guardian: Block cooldown -20%, Ranger: cooldown -15%).")
    b.roster("POWER_W", "index_terms.power_w", "Account power weights of the sim (§8.1: machines · hero · army) and the\n"
                                               "bucket-2 efficiency of machine synergy (Team.score / Auto-team).")
    b.head("synergy effects in the run (§5.1, §5.3)")
    b.docv("FACTION_RUN", "Faction -> {stat, tiers [none, I, II, III]}.")
    b.docv("FACTION_MEMBERS_FOR_TIER", "Living members needed for tier 0..III.")
    b.docv("CLASS_PAIR_RUN", "Class -> run effects with 2 of the class.")
    b.head("Rally hooks (§5.4): value = base x Ladder.mult(n, g, f) x (1 + RALLY_RANK_STEP (rank - 1))")
    hooks = {}
    targets, free = DOC["RALLY_HOOK_TARGETS"][0], DOC["RALLY_FREE_BASES"][0]
    for hid in b.r["hero_order"]:
        r = b.r["heroes"][hid]["rally"]
        old = hooks.get(r["hook"])
        if old is not None and old["base"] != r["base"]:
            sys.exit("Rally hook %s has two bases" % r["hook"])
        hooks[r["hook"]] = {"target": targets[r["hook"]][0], "op": targets[r["hook"]][1], "base": r["base"]}
    for hook, base in free.items():
        hooks[hook] = {"target": targets[hook][0], "op": targets[hook][1], "base": base}
    b.emit("RALLY_HOOKS", hooks, "derived:roster heroes.*.rally.base + doc §5.4 targets",
           "Hook -> {target, op (add | mul), base at rank 1, Quartz-normalised}.")
    b.docv("ULT_START_CAP", "Total tactics.ult_start never exceeds this.")
    b.head("difficulty re-bake (§8.2): LevelGen enemy budget multiplier per world")
    tf = {int(k): v for k, v in b.c["team_demand"].items()}
    b.emit("TEAM_DEMAND", {str(k): tf[k] for k in sorted(tf)}, "consts:team_demand",
           "World (as a string key, like the json) -> multiplier on the EXPECTED profile.")


def block_portal(b: Block) -> None:
    b.head("Portal (§7.1 - §7.4; unlock UNLOCK_PORTAL)")
    b.emit("UNLOCK_PORTAL", b.c["unlocks"]["portal"], "consts:unlocks.portal")
    for k in ("BASE_ODDS", "PITY_E", "PITY_L", "OPAL_SHARE_IN_L", "FOCUS_TOTAL", "SEAL_PRICES", "OWNED_SEAL_PICK_MULT",
              "WELCOME_X10", "BEACON"):
        b.consts(k, "portal." + k, {
            "PITY_E": "Amethyst+ certain on the summon number `hard` since the last Amethyst+.",
            "PITY_L": "Topaz+ chance rises by `step` from summon `soft_from`, certain on `hard`.",
            "OPAL_SHARE_IN_L": "Inside a Topaz-or-better result: Opal this share, Topaz the rest.",
            "FOCUS_TOTAL": "The Focus hero gets exactly this share of its gem's results once the gem is complete.",
            "OWNED_SEAL_PICK_MULT": "An owned Seal pick = this x the hero's DUP_FRAGS.",
            "BEACON": "Beacon sources (earned only; §7.3). track = 0: Track nodes never pay Beacons."}.get(k, ""))
    b.docv("BEACONS_PER_SUMMON")
    b.docv("X10_SUMMONS")
    b.docv("SEALS_PER_SUMMON")
    b.head("Hero Chests (§7.5; unlock UNLOCK_CHESTS)")
    b.emit("UNLOCK_CHESTS", b.c["unlocks"]["champions"], "consts:unlocks.champions")
    for k in b.c["chests"]:
        b.consts(k, "chests." + k, {
            "CHEST_TOMES": "Kind -> [min, max] Tomes (Grand only, after the skills unlock).",
            "CHEST_HERO_CARD": "Hero-fragment card = round(CHEST_HERO_CARD x DUP_FRAGS[native]) x CHEST_HERO_FRAG_MULT[kind]."
        }.get(k, ""))
    dup, share = b.c["progress"]["DUP_FRAGS"], b.c["chests"]["CHEST_HERO_CARD"]
    b.emit("CHEST_HERO_CARD_FRAGS", [int(share * d + 0.5) for d in dup], "derived:round(CHEST_HERO_CARD x DUP_FRAGS)",
           "Per native gem, Hero Chest (x CHEST_HERO_FRAG_MULT in a Grand chest); half rounds up like the sim.")
    b.docv("CHEST_TEAM_HERO_WEIGHT", "The team hero's weight when the hero-fragment card picks an owned hero.")
    b.docv("GRAND_LAST_CARD_MIN", "The Grand chest's last card is drawn among this gem and better.")
    b.docv("CHEST_PITY_GEM", "CHEST_PITY_L forces a card of this gem.")
    b.head("scripted chests (§7.5): #1 by the team hero, #2 fixed")
    b.roster("SCRIPTED_FIRST", "scripted_chests.first")
    b.roster("SCRIPTED_FIRST_DEFAULT", "scripted_chests.first_default")
    b.roster("SCRIPTED_SECOND", "scripted_chests.second")


def block_ceremony(b: Block) -> None:
    b.head("ceremony lengths in seconds (§9.4; also read by heroes_sim.py)")
    b.consts("CEREMONY", "ceremony", "x1 = [Quartz, Sapphire]; walkout keys are gem indices \"2\" / \"3\" / \"4\" (E / L / M),\n"
                                     "played after `prologue`; batch_crack = ×10 facet cracks; clevel = Champion Level.")
    b.docv("CEREMONY_FAST", "Fast ceremonies / Quick reveal lengths (keys absent = unchanged).")
    b.docv("CEREMONY_REDUCED", "Reduce Motion lengths (keys absent = no motion at all / unchanged).")
    b.docv("TEAM_READY")
    b.docv("SKIP_FROM", "Walkouts are skippable from this many seconds.")


FILES = [
    ("ladder", "Ladder", block_ladder),
    ("hero_data", "HeroData", block_hero),
    ("champion_data", "ChampionData", block_champion),
    ("team_data", "TeamData", block_team),
    ("portal_data", "PortalData", block_portal),
    ("ceremony_data", "CeremonyData", block_ceremony),
]

SKELETON = """class_name {cls}
extends RefCounted
## Heroes & Champions data (heroes_design.md §12.2, WS-A). The block below is generated by
## tools/gen_heroes_data.py from tools/data/heroes_consts.json + heroes_roster.json; hand-written
## helpers go after it. Nothing in the shipped game reads this class before EconData.HEROES_PHASE >= 1.

{block}
"""


def render_all() -> dict:
    craw, rraw = open(CONSTS_JSON, "rb").read(), open(ROSTER_JSON, "rb").read()
    consts, roster = json.loads(craw), json.loads(rraw)
    stamp = "Sources: heroes_consts.json sha256 %s, heroes_roster.json sha256 %s." % (
        hashlib.sha256(craw).hexdigest()[:16], hashlib.sha256(rraw).hexdigest()[:16])
    out = {}
    for fname, cls, fn in FILES:
        b = Block(consts, roster)
        fn(b)
        path = os.path.join(ROOT, "scripts", "core", fname + ".gd")
        block = b.text(stamp)
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if BEGIN in cur and END in cur:
            i, j = cur.index(BEGIN), cur.index(END) + len(END)
            new = cur[:i] + block + cur[j:]
        else:
            new = SKELETON.format(cls=cls, block=block)
        out[path] = (cur, new)
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--refresh", metavar="DIR", nargs="?", const=os.path.join(ROOT, "tools"))
    a = ap.parse_args()
    if a.refresh:
        refresh(a.refresh)
    for p in (CONSTS_JSON, ROSTER_JSON):
        if not os.path.exists(p):
            sys.exit("%s missing (run --refresh <dir>)" % os.path.relpath(p, ROOT))
    files = render_all()
    stale = [p for p, (cur, new) in files.items() if cur != new]
    if a.check:
        for p in stale:
            print("OUT OF DATE: %s (run python3 tools/gen_heroes_data.py)" % os.path.relpath(p, ROOT))
        if stale:
            sys.exit(1)
        print("heroes data in sync: %d files" % len(files))
        return
    for p, (cur, new) in files.items():
        if cur != new:
            with open(p, "w", encoding="utf-8") as fh:
                fh.write(new)
            print("wrote %s" % os.path.relpath(p, ROOT))
    if not stale:
        print("heroes data already in sync")


if __name__ == "__main__":
    main()
