extends RefCounted
## Team + Recut + Champion Showcase copy (owner: scripts/ui/heroes/team/*, recut/*, champion/*).
## Loaded by HeroesText (EXTRA_TABLES) after Loc and before the foundation fallback. Key families
## follow heroes_design.md §12.4 (TEAM_*, RECUT_*, CHAMP_UI_*, ACT_<ID>, RELIC_<ID>); WS-Loc moves
## these rows into Loc in H3b and deletes this file. No literal numbers: every number is a %d / %s
## placeholder filled from data (TeamData, ChampionData, Ladder, HeroData through the screens).

const T := {
	# ------------------------------------------------------------ Team (§5.5, §9.3, part U §2.7)
	"TEAM_PLAY": ["Грати", "Play"],
	"TEAM_PLAY_SUB": ["Рівень %d", "Level %d"],
	"TEAM_SLOT_FRONT": ["Попереду", "Front"], "TEAM_SLOT_LEFT": ["Ліворуч", "Left"],
	"TEAM_SLOT_RIGHT": ["Праворуч", "Right"], "TEAM_SLOT_REAR": ["Позаду", "Rear"],
	"TEAM_SLOT_ADD": ["Додати", "Add"],
	"TEAM_HERO_ROLE": ["Веде армію", "Leads the army"],
	"TEAM_FORMATION": ["Стрій", "Formation"],
	"TEAM_PRESETS": ["Набори", "Presets"],
	"TEAM_PRESET_SAVED": ["Збережено: %s", "Saved: %s"],
	"TEAM_PRESET_LOADED": ["Завантажено: %s", "Loaded: %s"],
	"TEAM_PRESET_HINT": ["Торкнись — завантажити · утримуй — зберегти", "Tap to load · hold to save"],
	"TEAM_AUTO_TITLE": ["Підібрана команда", "Suggested team"],
	"TEAM_AUTO_APPLY": ["Застосувати", "Apply"],
	"TEAM_AUTO_CANCEL": ["Скасувати", "Cancel"],
	"TEAM_AUTO_SAME": ["Твоя команда вже найсильніша з наявних", "Your team is already the strongest you have"],
	"TEAM_AUTO_GAINS": ["Синергія: %d → %d", "Synergy: %d → %d"],
	"TEAM_AUTO_WHY_POWER": ["Сильніше: вищі самоцвіти й грані, синергія та сама", "Stronger: higher gems and facets, the same synergy"],
	"TEAM_AUTO_WHY_POWER_OVER": ["Сильніше попри нижчу синергію: значно вищі самоцвіти й грані", "Stronger despite less synergy: much higher gems and facets"],
	"TEAM_ROSTER_CHAMP": ["Чемпіон · %s", "Champion · %s"],
	"TEAM_ROSTER_HERO": ["Герой команди", "Team hero"],
	"TEAM_ROSTER_HINT": ["Торкнись картку — вона стане в стрій. Значки показують зміну синергії.", "Tap a card to place it. Badges show how the synergy changes."],
	"TEAM_IN_SLOT": ["У строю", "In the team"],
	"TEAM_HERE": ["Тут зараз", "Here now"],
	"TEAM_REMOVE": ["Прибрати зі строю", "Remove from the team"],
	"TEAM_DELTA_FACTION": ["+Фракція", "+Faction"],
	"TEAM_DELTA_CLASS": ["+Клас", "+Class"],
	"TEAM_DELTA_ELEMENT": ["+Стихія", "+Element"],
	"TEAM_DELTA_FACTION_LOSS": ["−Фракція", "−Faction"],
	"TEAM_DELTA_CLASS_LOSS": ["−Клас", "−Class"],
	"TEAM_DELTA_ELEMENT_LOSS": ["−Стихія", "−Element"],
	"TEAM_DELTA_NONE": ["Без змін", "No change"],
	"TEAM_SYN_COUNT": ["%s %d / %d", "%s %d / %d"],
	"TEAM_SYN_PAIR": ["%s %d", "%s %d"],
	"TEAM_SYN_AFF": ["%s ×%d", "%s ×%d"],
	"TEAM_SYN_SIMPLE_NOTE": ["Повна панель синергії — з відкриттям Порталу", "The full synergy panel opens with the Portal"],
	# ------------------------------------------------------------ Recut (§2.2-§2.4, §9.3, part U §2.5)
	"RECUT_HEAD": ["%s · %s → %s", "%s · %s → %s"],
	"RECUT_UNLOCK_CAP_1": ["+%d межа навичок", "+%d skill cap"],
	"RECUT_UNLOCK_CAP_N": ["+%d межі навичок", "+%d skill caps"],
	"RECUT_UNLOCK_STATS": ["+%s до показників", "+%s to stats"],
	"RECUT_UNLOCK_AWAKEN": ["Пробудження", "Awakening"],
	"RECUT_UNLOCK_AWAKEN_RANK": ["Пробудження до рангу %d", "Awakening up to rank %d"],
	"RECUT_UNLOCK_FACETS": ["%d нових граней", "%d new facets"],
	"RECUT_UNLOCK_LOOK": ["Новий вигляд: %s серце й тло", "New look: a %s heart and backdrop"],
	"RECUT_UNLOCK_NOTE": ["усе — на Повних гранях нового самоцвіту", "all at Full facets of the new gem"],
	"RECUT_ROW_STATS": ["Показники", "Stats"],
	"RECUT_AT_FULL": ["→ значення на Повних гранях", "→ the value at Full facets"],
	"RECUT_CELL_NONE": ["—", "—"],
	"RECUT_CELL_RANK": ["ранг %d", "rank %d"],
	"RECUT_CELL_TIER": ["Ярус %s", "Tier %s"],
	"RECUT_CELL_BORN": ["від народження", "born"],
	"RECUT_CEILING_TITLE": ["Межа корінного", "The native ceiling"],
	"RECUT_CEILING_LINE": ["Огранений %s — до %s від корінного", "A recut %s reaches %s of a native"],
	"RECUT_CEILING_YOU": ["твоя межа", "your ceiling"],
	"RECUT_CEILING_NATIVE": ["корінний", "native"],
	"RECUT_NATIVE_EXPLAIN": ["Корінний — самоцвіт, з яким персонаж народився. Його не змінити й не купити.", "Native is the gem a character was born with. It can’t be changed or bought."],
	"RECUT_COST_TITLE": ["Ціна огранки", "Recut cost"],
	"RECUT_COST_ONLY": ["Лише фрагменти — монети не потрібні", "Fragments only — no coins"],
	"RECUT_SHORT": ["Бракує %s", "%s short"],
	"RECUT_NEED_FACETS": ["Ще %s до Повних граней", "%s more to Full facets"],
	"RECUT_CONFIRM": ["Підтвердити", "Confirm"],
	"RECUT_CONFIRM_SUB": ["Ще раз — і самоцвіт огранено", "Tap again to recut"],
	"RECUT_DONE": ["Огранено", "Recut"],
	"RECUT_CONTINUE": ["Далі", "Continue"],
	"RECUT_PATH_NATIVE": ["корінний", "native"],
	"RECUT_PATH_NOW": ["зараз", "now"],
	"RECUT_PATH_NEXT": ["далі", "next"],
	"RECUT_AT_MAX": ["Найвища огранка. Далі ростуть грані й навички.", "The highest cut. Facets and skills keep growing."],
	"RECUT_TOP_NATIVE": ["Корінний %s · найвищий самоцвіт", "Native %s · the highest gem"],
	"RECUT_TOP_RECUT": ["Огранений із %s · найвищий самоцвіт", "Recut from %s · the highest gem"],
	"RECUT_TOP_FULL": ["Повні грані", "Full facets"],
	"RECUT_TOP_AWAKEN": ["Пробудження: ранг %d / %d", "Awakening: rank %d / %d"],
	"RECUT_STONE_NATIVE": ["серце: %s", "heart: %s"],
	"CHAMP_UI_ART_SOON": ["Арт чемпіона — скоро", "Champion art — coming soon"],
	"RECUT_SKIP_HINT": ["Торкнись, щоб пропустити", "Tap to skip"],
	# ------------------------------------------------------------ Champion Showcase (§4, §9.3, part U §2.6)
	"CHAMP_UI_SHARED": ["спільний для всіх чемпіонів", "shared by every champion"],
	"CHAMP_UI_SLOT": ["Місце в строю: %s", "Formation slot: %s"],
	"CHAMP_UI_TIER_HAVE": ["Ярус %s — найвищий: корінний %s", "Tier %s — the highest: a native %s"],
	"CHAMP_UI_TIER_KEPT": ["Огранений: ярус лишається %s", "Recut: the tier stays %s"],
	"CHAMP_UI_RELIC_LOCKED": ["Майстерня — після рівня\u00A0%d", "Workshop — after level\u00A0%d"],
	"CHAMP_UI_RELIC_RANK": ["+%d · гартування в Майстерні", "+%d · temper in the Workshop"],
	"CHAMP_UI_AURA_VALUE": ["%s у колі", "%s inside the ring"],
	"CHAMP_UI_RUN": ["У забігу", "In the run"],
	"CHAMP_UI_RUN_SOON": ["Живе демо — разом із моделлю чемпіона", "The live demo arrives with the champion’s model"],
	"CHAMP_UI_TO_TEAM": ["До команди", "To the team"],
	"CHAMP_UI_TWIST": ["Особливість", "Twist"],
	# Twist names (ACT_<ID>, §6.11-§6.22, §6.25-§6.26) and their one-line rule (no numbers; the sheets hold them).
	"ACT_MILA": ["Тонік", "Tonic"],
	"ACT_MILA_DESC": ["Імпульс, що повернув солдата, кидає флакон: МІТКА на найближчий загін, видно Фантомів", "A pulse that returns a soldier throws a flare vial: MARK on the nearest squad, Phantoms revealed"],
	"ACT_IVO": ["Жар", "Brazier Heat"],
	"ACT_IVO_DESC": ["Заблокована загорода горить, а загін у сутичці отримує ОПІК", "A blocked barricade burns, and the squad in the clash gets BURN"],
	"ACT_BORKO": ["Підкоп", "Undermine"],
	"ACT_BORKO_DESC": ["Пірнає під землю й виринає під загоном: вбивства й ОГЛУШЕННЯ; летунів не дістає", "Burrows and erupts under a squad: kills and STAGGER; never fliers"],
	"ACT_ALBA": ["Крижана стріла", "Ice Arrow"],
	"ACT_ALBA_DESC": ["Постріли накладають ХОЛОД і першими б’ють летунів", "Shots apply CHILL and pick flying squads first"],
	"ACT_OTTO": ["Панцир-фортеця", "Shell Fortress"],
	"ACT_OTTO_DESC": ["На початку сутички вкопується: перші удари армія не відчуває", "Plants at each clash start: the army ignores the first clash ticks"],
	"ACT_TAYA": ["Пилок снів", "Dream Dust"],
	"ACT_TAYA_DESC": ["Уражені загони засинають на ходу: повільніші й слабші в сутичці", "Squads hit are lulled: slower and weaker in the clash"],
	"ACT_BRANT": ["Розжарені клинки", "Red-hot Blades"],
	"ACT_BRANT_DESC": ["Розтин накладає ОПІК, а стрибок лишає палаючий хрест", "Cleave applies BURN, and the leap leaves a burning cross"],
	"ACT_TEO": ["Зоряний зонд", "Star Probe"],
	"ACT_TEO_DESC": ["Кожен четвертий постріл — зонд: видно Фантомів, ціль отримує МІТКУ", "Every fourth shot is a probe: Phantoms revealed, the target MARKed"],
	"ACT_OLENA": ["Морозний бальзам", "Frost Balm"],
	"ACT_OLENA_DESC": ["Імпульс студить загони біля фронту; повернуті солдати краще переживають пастки", "Each pulse chills squads at the front; returned soldiers survive hazards better"],
	"ACT_NIMB": ["Громовідвід", "Lightning Rod"],
	"ACT_NIMB_DESC": ["Кожен блок розряджається ланцюгом блискавки у трьох ворогів", "Every Block discharges a lightning chain into three hostiles"],
	"ACT_DARA": ["Гарпун-блискавка", "Thunder Harpoon"],
	"ACT_DARA_DESC": ["Кожен третій постріл зшиває два загони і приземлює летунів", "Every third shot tethers two squads and grounds fliers"],
	"ACT_MENHIR": ["Рунне коло", "Rune Circle"],
	"ACT_MENHIR_DESC": ["Удар креслить коло: загони в ньому мічені й слабші в сутичці", "The strike carves a circle: squads inside are Branded and weaker in clashes"],
	"ACT_TARAS": ["Слово", "The Word"],
	"ACT_TARAS_DESC": ["Книга летить у найближчий загін, а сторінки розтинають і загін за ним", "A book strikes the nearest squad, and its pages cut on into the squad behind"],
	"ACT_SNARYAD": ["Нюх сапера", "Sapper’s Nose"],
	"ACT_SNARYAD_DESC": ["Знешкоджує пастку попереду армії й кидає її заряд на найближчий загін: Мітка", "Defuses the trap ahead of the army and drops its charge on the nearest squad: Mark"],
	# The Action's main number (kit x ladder x Champion Level), one template per champion.
	"CHAMP_MILA_ACTVAL": ["Повертає до %s солдатів за імпульс", "Returns up to %s soldiers per pulse"],
	"CHAMP_IVO_ACTVAL": ["Блок: %s шкоди загороді", "Block: %s damage to the barricade"],
	"CHAMP_BORKO_ACTVAL": ["Підкоп: %s вбивств", "Undermine: %s kills"],
	"CHAMP_ALBA_ACTVAL": ["Постріл: %s шкоди, по летунах більше", "Shot: %s damage, more against fliers"],
	"CHAMP_OTTO_ACTVAL": ["Блок: %s вбивств", "Block: %s kills"],
	"CHAMP_TAYA_ACTVAL": ["Чари: %s вбивств на загін", "Spell: %s kills per squad"],
	"CHAMP_BRANT_ACTVAL": ["Стрибок: %s вбивств", "Leap: %s kills"],
	"CHAMP_TEO_ACTVAL": ["Самонавідний постріл: %s шкоди", "Homing shot: %s damage"],
	"CHAMP_OLENA_ACTVAL": ["Повертає до %s солдатів за імпульс", "Returns up to %s soldiers per pulse"],
	"CHAMP_NIMB_ACTVAL": ["Громовідвід: %s шкоди кожній цілі", "Lightning Rod: %s damage per target"],
	"CHAMP_DARA_ACTVAL": ["Постріл: %s шкоди", "Shot: %s damage"],
	"CHAMP_MENHIR_ACTVAL": ["Рунний удар: %s вбивств на загін", "Rune strike: %s kills per squad"],
	"CHAMP_TARAS_ACTVAL": ["Слово: %s вбивств на загін", "The Word: %s kills per squad"],
	"CHAMP_SNARYAD_ACTVAL": ["Нюх сапера: %s вбивств за заряд", "Sapper’s Nose: %s kills per charge"],
	# Champion relics (§6.11-§6.22, §6.25-§6.26; RELIC_<ID>).
	"RELIC_MILA": ["Ліхтар наставниці", "Mentor’s Lantern"],
	"RELIC_IVO": ["Решітка жаровні", "Brazier Grate"],
	"RELIC_BORKO": ["Дідова лопата", "Grandsire’s Spade"],
	"RELIC_ALBA": ["Сніжна тятива", "Snow String"],
	"RELIC_OTTO": ["Перший камінчик", "First Pebble"],
	"RELIC_TAYA": ["Колискова", "Lullaby Chime"],
	"RELIC_BRANT": ["Серце жеоди", "Geode Heart"],
	"RELIC_TEO": ["Журнал зондів", "Probe Logbook"],
	"RELIC_OLENA": ["Рогові дзвоники", "Antler Bells"],
	"RELIC_NIMB": ["Гроза в пляшці", "Bottled Storm"],
	"RELIC_DARA": ["Лебідка гарпуна", "Harpoon Winch"],
	"RELIC_MENHIR": ["Найдавніша руна", "Eldest Rune"],
	"RELIC_TARAS": ["Перо поета", "The Poet’s Quill"],
	"RELIC_SNARYAD": ["Перше кільце", "The First Ring"],
}
