# -*- coding: utf-8 -*-
"""System apps across Pixel/AOSP, Samsung and Xiaomi - the icons a home screen
shows before any third-party app is installed."""

from catalog import App, M, T, brand, brand_glow, graphite, porcelain

APPS = [
    App("sys_phone", "Телефон", brand("#22B573"), M("handset"), scale=0.5,
        packages=["com.google.android.dialer", "com.android.dialer", "com.samsung.android.dialer",
                  "com.android.contacts.activities.DialtactsActivity"],
        components=["com.google.android.dialer/com.google.android.dialer.extensions.GoogleDialtactsActivity",
                    "com.android.dialer/com.android.dialer.main.impl.MainActivity",
                    "com.samsung.android.dialer/com.samsung.android.dialer.DialtactsActivity",
                    "com.android.contacts/com.android.contacts.activities.DialtactsActivity"],
        tags=["system"]),
    App("sys_messages", "Повідомлення", brand("#1E88E5"), M("bubble"), scale=0.5,
        packages=["com.google.android.apps.messaging", "com.samsung.android.messaging",
                  "com.android.mms", "com.miui.smsextra"],
        components=["com.google.android.apps.messaging/com.google.android.apps.messaging.ui.ConversationListActivity",
                    "com.samsung.android.messaging/com.android.mms.ui.ConversationComposer",
                    "com.android.mms/com.android.mms.ui.ConversationList"],
        tags=["system"]),
    App("sys_contacts", "Контакти", brand("#0EA5E9"), M("person"), scale=0.5,
        packages=["com.google.android.contacts", "com.android.contacts",
                  "com.samsung.android.app.contacts"],
        components=["com.google.android.contacts/com.android.contacts.activities.PeopleActivity",
                    "com.android.contacts/com.android.contacts.activities.PeopleActivity",
                    "com.samsung.android.app.contacts/com.samsung.android.app.contacts.PeopleActivity"],
        tags=["system"]),
    App("sys_camera", "Камера", graphite("#8894A6"), M("camera"), scale=0.52,
        packages=["com.android.camera2", "com.android.camera", "com.sec.android.app.camera",
                  "com.google.android.GoogleCamera", "com.oneplus.camera", "org.codeaurora.snapcam"],
        components=["com.android.camera2/com.android.camera.CameraLauncher",
                    "com.sec.android.app.camera/com.sec.android.app.camera.Camera",
                    "com.google.android.GoogleCamera/com.android.camera.CameraLauncher"],
        tags=["system"]),
    App("sys_gallery", "Галерея", brand_glow("#F43F5E", "#FB923C"), M("gallery"), scale=0.52,
        packages=["com.sec.android.gallery3d", "com.miui.gallery", "com.android.gallery3d",
                  "com.oneplus.gallery", "com.coloros.gallery3d"],
        components=["com.sec.android.gallery3d/com.sec.android.gallery3d.app.GalleryActivity",
                    "com.miui.gallery/com.miui.gallery.activity.HomePageActivity",
                    "com.android.gallery3d/com.android.gallery3d.app.GalleryActivity"],
        tags=["system"]),
    App("sys_clock", "Годинник", brand("#0EA5E9"), M("clock"), scale=0.54,
        packages=["com.google.android.deskclock", "com.android.deskclock",
                  "com.sec.android.app.clockpackage"],
        components=["com.google.android.deskclock/com.android.deskclock.DeskClock",
                    "com.android.deskclock/com.android.deskclock.DeskClock",
                    "com.sec.android.app.clockpackage/com.sec.android.app.clockpackage.ClockPackage"],
        tags=["system"]),
    App("sys_calculator", "Калькулятор", brand("#64748B"), M("calculator"), scale=0.5,
        packages=["com.google.android.calculator", "com.android.calculator2",
                  "com.sec.android.app.popupcalculator", "com.miui.calculator"],
        components=["com.google.android.calculator/com.android.calculator2.Calculator",
                    "com.android.calculator2/com.android.calculator2.Calculator",
                    "com.sec.android.app.popupcalculator/com.sec.android.app.popupcalculator.Calculator",
                    "com.miui.calculator/com.miui.calculator.cal.CalculatorActivity"],
        tags=["system"]),
    App("sys_settings", "Налаштування", graphite("#94A3B8"), M("gear"), scale=0.5,
        packages=["com.android.settings"],
        components=["com.android.settings/com.android.settings.Settings",
                    "com.android.settings/com.android.settings.homepage.SettingsHomepageActivity"],
        tags=["system"]),
    App("sys_files", "Файли", brand("#F59E0B"), M("folder"), scale=0.52,
        packages=["com.android.documentsui", "com.sec.android.app.myfiles",
                  "com.mi.android.globalFileexplorer", "com.google.android.documentsui"],
        components=["com.android.documentsui/com.android.documentsui.files.FilesActivity",
                    "com.sec.android.app.myfiles/com.sec.android.app.myfiles.ui.MainActivity",
                    "com.mi.android.globalFileexplorer/com.android.fileexplorer.FileExplorerTabActivity"],
        tags=["system"]),
    App("sys_calendar", "Календар", brand("#EF4444"), M("calendar"), scale=0.5,
        packages=["com.android.calendar", "com.samsung.android.calendar", "com.miui.calendar"],
        components=["com.android.calendar/com.android.calendar.AllInOneActivity",
                    "com.samsung.android.calendar/com.samsung.android.app.calendar.activity.MainActivity"],
        tags=["system"]),
    App("sys_browser", "Браузер", brand("#2563EB"), M("globe"), scale=0.5,
        packages=["com.sec.android.app.sbrowser", "com.android.browser", "com.mi.globalbrowser"],
        components=["com.sec.android.app.sbrowser/com.sec.android.app.sbrowser.SBrowserMainActivity",
                    "com.android.browser/com.android.browser.BrowserActivity"],
        tags=["system"]),
    App("sys_notes", "Нотатки", brand("#EAB308"), M("doc_page"), scale=0.5,
        packages=["com.samsung.android.app.notes", "com.miui.notes", "com.google.android.keep.notes"],
        components=["com.samsung.android.app.notes/com.samsung.android.app.notes.memolist.MemoListActivity",
                    "com.miui.notes/com.miui.notes.ui.NotesListActivity"],
        tags=["system"]),
    App("sys_recorder", "Диктофон", brand("#8B5CF6"), M("mic"), scale=0.5,
        packages=["com.android.soundrecorder", "com.sec.android.app.voicenote",
                  "com.google.android.apps.recorder"],
        tags=["system"]),
    App("sys_email", "Пошта", brand("#0891B2"), M("envelope"), scale=0.5,
        packages=["com.android.email", "com.samsung.android.email.provider"],
        components=["com.samsung.android.email.provider/com.samsung.android.email.ui.activity.MessageListXL"],
        tags=["system"]),
    App("sys_music", "Музика", brand("#F97316"), M("music_note"), scale=0.5,
        packages=["com.sec.android.app.music", "com.miui.player", "com.android.music"],
        tags=["system"]),
    App("sys_video", "Відео", brand("#7C3AED"), M("film"), scale=0.5,
        packages=["com.samsung.android.video", "com.miui.video", "com.android.gallery3d.videoplayer"],
        tags=["system"]),
    App("sys_store", "Магазин застосунків", brand("#1D4ED8"), M("bag"), scale=0.5,
        packages=["com.sec.android.app.samsungapps", "com.xiaomi.market", "com.huawei.appmarket"],
        components=["com.sec.android.app.samsungapps/com.sec.android.app.samsungapps.Main",
                    "com.xiaomi.market/com.xiaomi.market.ui.MarketTabActivity"],
        tags=["system"]),
    App("sys_themes", "Теми", brand("#DB2777"), M("gallery"), scale=0.5,
        packages=["com.samsung.android.themestore", "com.android.thememanager"],
        tags=["system"]),
    App("sys_health", "Здоров'я", brand("#E11D48"), M("heart"), scale=0.48,
        packages=["com.sec.android.app.shealth", "com.google.android.apps.fitness"],
        tags=["system"]),
    App("sys_weather", "Погода", brand("#38BDF8"), M("weather"), scale=0.56,
        packages=["com.sec.android.daemonapp", "com.miui.weather2", "com.google.android.apps.weather"],
        tags=["system"]),
    App("sys_security", "Безпека", brand("#16A34A"), M("shield"), scale=0.48,
        packages=["com.miui.securitycenter", "com.samsung.android.lool",
                  "com.google.android.apps.security"],
        tags=["system"]),
    App("sys_downloads", "Завантаження", brand("#0284C7"), M("parcel"), scale=0.48,
        packages=["com.android.providers.downloads.ui", "com.samsung.android.app.galaxyfinder"],
        tags=["system"]),
    App("sys_scanner", "Сканер QR", graphite("#22D3EE"), M("qr"), scale=0.48,
        packages=["com.google.android.apps.scanner", "com.gamma.scan"],
        tags=["system"]),
]
