# -*- coding: utf-8 -*-
"""Globally popular apps."""

from catalog import App, M, T, brand, brand_glow, graphite, porcelain

APPS = [
    # --- messengers & social ---------------------------------------------- #
    App("telegram", "Telegram", brand("#2AABEE"), M("telegram"), scale=0.54, dy=1,
        packages=["org.telegram.messenger", "org.telegram.messenger.web", "org.telegram.plus",
                  "nekox.messenger", "org.thunderdog.challegram"],
        components=["org.telegram.messenger/org.telegram.ui.LaunchActivity",
                    "org.telegram.messenger.web/org.telegram.ui.LaunchActivity"]),
    App("whatsapp", "WhatsApp", brand("#25D366"), M("whatsapp"), scale=0.56,
        packages=["com.whatsapp", "com.whatsapp.w4b"],
        components=["com.whatsapp/com.whatsapp.Main", "com.whatsapp/com.whatsapp.HomeActivity",
                    "com.whatsapp.w4b/com.whatsapp.Main"]),
    App("viber", "Viber", brand("#7360F2"), M("viber"), scale=0.56,
        packages=["com.viber.voip"],
        components=["com.viber.voip/com.viber.voip.WelcomeActivity",
                    "com.viber.voip/com.viber.voip.HomeActivity"]),
    App("signal", "Signal", brand("#3A76F0"), M("signal"), scale=0.52,
        packages=["org.thoughtcrime.securesms"],
        components=["org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity",
                    "org.thoughtcrime.securesms/org.thoughtcrime.securesms.MainActivity"]),
    App("messenger", "Messenger", brand_glow("#0A7CFF", "#A033FF"), M("messenger"), scale=0.54,
        packages=["com.facebook.orca"],
        components=["com.facebook.orca/com.facebook.orca.auth.StartScreenActivity",
                    "com.facebook.orca/com.facebook.orca.notify.MessengerNotificationActivity"]),
    App("facebook", "Facebook", brand("#1877F2"), M("facebook"), scale=0.5,
        packages=["com.facebook.katana", "com.facebook.lite"],
        components=["com.facebook.katana/com.facebook.katana.LoginActivity",
                    "com.facebook.lite/com.facebook.lite.MainActivity"]),
    App("instagram", "Instagram", brand_glow("#C13584", "#FCAF45"), M("instagram"), scale=0.54,
        packages=["com.instagram.android", "com.instagram.lite"],
        components=["com.instagram.android/com.instagram.mainactivity.MainActivity",
                    "com.instagram.android/com.instagram.android.activity.MainTabActivity"]),
    App("threads", "Threads", graphite("#8E97A8"), M("threads"), scale=0.52,
        packages=["com.instagram.barcelona"],
        components=["com.instagram.barcelona/com.instagram.barcelona.mainactivity.BarcelonaMainActivity"]),
    App("x_twitter", "X", graphite("#7A8698"), M("x_twitter"), scale=0.5,
        packages=["com.twitter.android", "com.twitter.android.lite"],
        components=["com.twitter.android/com.twitter.app.main.MainActivity",
                    "com.twitter.android/com.twitter.android.StartActivity"]),
    App("tiktok", "TikTok", graphite("#FE2C55"), M("tiktok_color"), scale=0.52,
        packages=["com.zhiliaoapp.musically", "com.ss.android.ugc.trill"],
        components=["com.zhiliaoapp.musically/com.ss.android.ugc.aweme.splash.SplashActivity",
                    "com.ss.android.ugc.trill/com.ss.android.ugc.aweme.splash.SplashActivity"]),
    App("snapchat", "Snapchat", brand_glow("#FFE300", "#FFF176"), M("snapchat"), fg="#1B1B00", scale=0.52,
        packages=["com.snapchat.android"],
        components=["com.snapchat.android/com.snap.mushroom.MainActivity"]),
    App("pinterest", "Pinterest", brand("#E60023"), M("pinterest"), scale=0.5,
        packages=["com.pinterest"],
        components=["com.pinterest/com.pinterest.activity.PinterestActivity"]),
    App("linkedin", "LinkedIn", brand("#0A66C2"), M("linkedin"), scale=0.5,
        packages=["com.linkedin.android"],
        components=["com.linkedin.android/com.linkedin.android.authenticator.LaunchActivity"]),
    App("reddit", "Reddit", brand("#FF4500"), M("reddit"), scale=0.54,
        packages=["com.reddit.frontpage"],
        components=["com.reddit.frontpage/com.reddit.launch.main.MainActivity",
                    "com.reddit.frontpage/com.reddit.frontpage.StartActivity"]),
    App("discord", "Discord", brand("#5865F2"), M("discord"), scale=0.54,
        packages=["com.discord"],
        components=["com.discord/com.discord.main.MainActivity",
                    "com.discord/com.discord.app.AppActivity$Main"]),
    App("bluesky", "Bluesky", brand("#0085FF"), M("bubble"), scale=0.48,
        packages=["xyz.blueskyweb.app"]),
    App("skype", "Skype", brand("#00AFF0"), T("S", width=0.44, height=0.62),
        packages=["com.skype.raider"],
        components=["com.skype.raider/com.skype.m2.SplashActivity"]),

    # --- google ------------------------------------------------------------ #
    App("google", "Google", porcelain("#4285F4"), M("google_g"), scale=0.5,
        packages=["com.google.android.googlequicksearchbox"],
        components=["com.google.android.googlequicksearchbox/com.google.android.googlequicksearchbox.SearchActivity",
                    "com.google.android.googlequicksearchbox/.SearchActivity"]),
    App("gmail", "Gmail", porcelain("#EA4335"), M("gmail"), scale=0.64,
        packages=["com.google.android.gm"],
        components=["com.google.android.gm/com.google.android.gm.ConversationListActivityGmail"]),
    App("google_maps", "Google Maps", porcelain("#34A853"), M("maps_pin"), scale=0.5,
        packages=["com.google.android.apps.maps"],
        components=["com.google.android.apps.maps/com.google.android.maps.MapsActivity"]),
    App("google_drive", "Google Drive", porcelain("#FBBC05"), M("drive"), scale=0.54,
        packages=["com.google.android.apps.docs"],
        components=["com.google.android.apps.docs/com.google.android.apps.docs.app.NewMainProxyActivity"]),
    App("google_photos", "Google Photos", porcelain("#4285F4"), M("photos"), scale=0.54,
        packages=["com.google.android.apps.photos"],
        components=["com.google.android.apps.photos/com.google.android.apps.photos.home.HomeActivity"]),
    App("play_store", "Google Play", graphite("#34A853"), M("play_store"), scale=0.52,
        packages=["com.android.vending"],
        components=["com.android.vending/com.google.android.finsky.activities.MainActivity",
                    "com.android.vending/com.android.vending.AssetBrowserActivity"]),
    App("chrome", "Chrome", porcelain("#4285F4"), M("chrome"), scale=0.54,
        packages=["com.android.chrome", "com.chrome.beta", "com.chrome.dev"],
        components=["com.android.chrome/com.google.android.apps.chrome.Main"]),
    App("google_meet", "Google Meet", brand("#00832D"), M("meet"), scale=0.54,
        packages=["com.google.android.apps.tachyon", "com.google.android.apps.meetings"],
        components=["com.google.android.apps.tachyon/com.google.android.apps.tachyon.MainActivity"]),
    App("google_calendar", "Google Calendar", porcelain("#4285F4"), M("calendar"), fg="#1A73E8", scale=0.52,
        packages=["com.google.android.calendar"],
        components=["com.google.android.calendar/com.android.calendar.AllInOneActivity"]),
    App("google_keep", "Keep", brand("#FBBC05"), M("keep_bulb"), scale=0.5,
        packages=["com.google.android.keep"],
        components=["com.google.android.keep/com.google.android.keep.activities.BrowseActivity"]),
    App("google_translate", "Translate", brand("#4285F4"), M("translate"), scale=0.54,
        packages=["com.google.android.apps.translate"],
        components=["com.google.android.apps.translate/com.google.android.apps.translate.TranslateActivity"]),
    App("youtube", "YouTube", brand("#FF0033"), M("youtube"), scale=0.56,
        packages=["com.google.android.youtube", "app.revanced.android.youtube"],
        components=["com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity"]),
    App("youtube_music", "YouTube Music", graphite("#FF0033"), M("play_triangle"), scale=0.4,
        packages=["com.google.android.apps.youtube.music"],
        components=["com.google.android.apps.youtube.music/com.google.android.apps.youtube.music.activities.MusicActivity"]),
    App("google_docs", "Docs", brand("#2C5BD8"), M("doc_page"), scale=0.5,
        packages=["com.google.android.apps.docs.editors.docs"]),
    App("google_sheets", "Sheets", brand("#0F9D58"), M("doc_page"), scale=0.5,
        packages=["com.google.android.apps.docs.editors.sheets"]),
    App("google_slides", "Slides", brand("#F4B400"), M("doc_page"), scale=0.5,
        packages=["com.google.android.apps.docs.editors.slides"]),
    App("google_wallet", "Wallet", brand("#1A73E8"), M("wallet"), scale=0.5,
        packages=["com.google.android.apps.walletnfcrel"],
        components=["com.google.android.apps.walletnfcrel/com.google.commerce.tapandpay.android.wallet.WalletActivity"]),
    App("google_files", "Files", brand("#4285F4"), M("folder"), scale=0.52,
        packages=["com.google.android.apps.nbu.files"],
        components=["com.google.android.apps.nbu.files/com.google.android.apps.nbu.files.home.HomeActivity"]),

    # --- microsoft & work --------------------------------------------------- #
    App("outlook", "Outlook", brand("#0F6CBD"), M("envelope"), scale=0.5,
        packages=["com.microsoft.office.outlook"],
        components=["com.microsoft.office.outlook/com.microsoft.office.outlook.MainActivity"]),
    App("teams", "Teams", brand("#5059C9"), T("T", width=0.44, height=0.6),
        packages=["com.microsoft.teams"],
        components=["com.microsoft.teams/com.microsoft.skype.teams.Launcher"]),
    App("onedrive", "OneDrive", brand("#0364B8"), M("folder"), scale=0.52,
        packages=["com.microsoft.skydrive"]),
    App("ms_word", "Word", brand("#2B579A"), T("W", width=0.5, height=0.56),
        packages=["com.microsoft.office.word"]),
    App("ms_excel", "Excel", brand("#217346"), T("X", width=0.46, height=0.58),
        packages=["com.microsoft.office.excel"]),
    App("ms_powerpoint", "PowerPoint", brand("#D24726"), T("P", width=0.42, height=0.6),
        packages=["com.microsoft.office.powerpoint"]),
    App("zoom", "Zoom", brand("#2D8CFF"), M("meet"), scale=0.5,
        packages=["us.zoom.videomeetings"],
        components=["us.zoom.videomeetings/com.zipow.videobox.LauncherActivity"]),
    App("slack", "Slack", graphite("#E01E5A"), M("slack"), scale=0.5,
        packages=["com.Slack"],
        components=["com.Slack/slack.app.di.MainActivity"]),
    App("notion", "Notion", porcelain("#9AA3AF"), T("N", width=0.46, height=0.58), fg="#101418",
        packages=["notion.id"]),
    App("github", "GitHub", graphite("#8B98AA"), T("G", width=0.46, height=0.58),
        packages=["com.github.android"]),
    App("figma", "Figma", graphite("#F24E1E"), T("F", width=0.4, height=0.6),
        packages=["com.figma.mirror"]),
    App("canva", "Canva", brand_glow("#00C4CC", "#7D2AE8"), T("C", width=0.44, height=0.6),
        packages=["com.canva.editor"]),
    App("dropbox", "Dropbox", brand("#0061FF"), M("parcel"), scale=0.48,
        packages=["com.dropbox.android"]),
    App("todoist", "Todoist", brand("#E44332"), T("T", width=0.42, height=0.6),
        packages=["com.todoist"]),
    App("evernote", "Evernote", brand("#00A82D"), T("E", width=0.42, height=0.6),
        packages=["com.evernote"]),

    # --- ai ----------------------------------------------------------------- #
    App("chatgpt", "ChatGPT", graphite("#10A37F"), T("AI", width=0.62, height=0.5),
        packages=["com.openai.chatgpt"],
        components=["com.openai.chatgpt/com.openai.chatgpt.MainActivity"]),
    App("claude", "Claude", brand("#D97757"), T("C", width=0.44, height=0.6),
        packages=["com.anthropic.claude"]),
    App("gemini", "Gemini", porcelain("#4285F4"), T("G", width=0.46, height=0.58), fg="#1A73E8",
        packages=["com.google.android.apps.bard"]),
    App("copilot", "Copilot", brand("#0078D4"), T("Co", width=0.66, height=0.5),
        packages=["com.microsoft.copilot"]),
    App("perplexity", "Perplexity", brand("#20808D"), T("P", width=0.42, height=0.6),
        packages=["ai.perplexity.app.android"]),

    # --- music, video, games -------------------------------------------------- #
    App("spotify", "Spotify", brand("#1DB954"), M("spotify"), scale=0.56,
        packages=["com.spotify.music", "com.spotify.lite"],
        components=["com.spotify.music/com.spotify.music.MainActivity"]),
    App("netflix", "Netflix", graphite("#E50914"), M("netflix"), scale=0.46, fg="#E50914",
        packages=["com.netflix.mediaclient"],
        components=["com.netflix.mediaclient/com.netflix.mediaclient.ui.launch.UIWebViewActivity"]),
    App("twitch", "Twitch", brand("#9146FF"), M("twitch"), scale=0.5,
        packages=["tv.twitch.android.app"],
        components=["tv.twitch.android.app/tv.twitch.android.feature.splash.SplashActivity"]),
    App("soundcloud", "SoundCloud", brand("#FF5500"), M("music_note"), scale=0.5,
        packages=["com.soundcloud.android"]),
    App("deezer", "Deezer", graphite("#A238FF"), M("music_note"), scale=0.5,
        packages=["deezer.android.app"]),
    App("shazam", "Shazam", brand("#0088FF"), M("music_note"), scale=0.5,
        packages=["com.shazam.android"]),
    App("apple_music", "Apple Music", brand("#FA243C"), M("music_note"), scale=0.5,
        packages=["com.apple.android.music"]),
    App("vlc", "VLC", brand("#FF8800"), M("play_triangle"), scale=0.44,
        packages=["org.videolan.vlc"],
        components=["org.videolan.vlc/org.videolan.vlc.StartActivity"]),
    App("steam", "Steam", graphite("#66C0F4"), T("S", width=0.44, height=0.6),
        packages=["com.valvesoftware.android.steam.community"]),
    App("roblox", "Roblox", graphite("#E2231A"), M("gamepad"), scale=0.5,
        packages=["com.roblox.client"]),
    App("minecraft", "Minecraft", brand("#5B8731"), M("gamepad"), scale=0.5,
        packages=["com.mojang.minecraftpe"]),
    App("brawl_stars", "Brawl Stars", brand("#FFC800"), M("star"), fg="#1A1A1A", scale=0.5,
        packages=["com.supercell.brawlstars"]),
    App("clash_of_clans", "Clash of Clans", brand("#D8912A"), M("shield"), scale=0.5,
        packages=["com.supercell.clashofclans"]),
    App("pubg", "PUBG Mobile", brand("#F2A900"), M("gamepad"), fg="#1A1A1A", scale=0.5,
        packages=["com.tencent.ig", "com.pubg.imobile"]),
    App("genshin", "Genshin Impact", brand("#3B5DC9"), M("star"), scale=0.5,
        packages=["com.miHoYo.GenshinImpact"]),

    # --- shopping, travel, money ---------------------------------------------- #
    App("aliexpress", "AliExpress", brand("#E62E04"), M("bag"), scale=0.5,
        packages=["com.alibaba.aliexpresshd"]),
    App("amazon", "Amazon", graphite("#FF9900"), T("a", face="grotesk", width=0.4, height=0.6),
        packages=["com.amazon.mShop.android.shopping"]),
    App("temu", "Temu", brand("#FB7701"), T("T", width=0.42, height=0.6),
        packages=["com.einnovation.temu"]),
    App("shein", "SHEIN", graphite("#B0B8C4"), T("S", width=0.42, height=0.6),
        packages=["com.zzkko"]),
    App("booking", "Booking.com", brand("#003580"), M("ticket"), scale=0.5,
        packages=["com.booking"]),
    App("airbnb", "Airbnb", brand("#FF5A5F"), M("heart"), scale=0.48,
        packages=["com.airbnb.android"]),
    App("uber", "Uber", graphite("#9AA3AF"), T("Uber", width=0.84, height=0.4),
        packages=["com.ubercab"],
        components=["com.ubercab/com.ubercab.presidio.app.core.root.RootActivity"]),
    App("bolt", "Bolt", brand("#34D186"), M("bolt"), scale=0.46,
        packages=["ee.mtakso.client"],
        components=["ee.mtakso.client/eu.bolt.client.commondeps.ui.MainActivity",
                    "ee.mtakso.client/ee.mtakso.client.view.RideHailingActivity"]),
    App("bolt_food", "Bolt Food", brand("#2AA766"), M("bag"), scale=0.48,
        packages=["ee.bolt.deliveryclient"]),
    App("glovo", "Glovo", brand("#FFC244"), T("g", face="grotesk", width=0.34, height=0.6), fg="#1B4B3A",
        packages=["com.glovo", "com.glovoapp.android"]),
    App("paypal", "PayPal", brand("#003087"), T("P", width=0.4, height=0.6),
        packages=["com.paypal.android.p2pmobile"]),
    App("revolut", "Revolut", graphite("#7B8AA0"), T("R", width=0.44, height=0.6),
        packages=["com.revolut.revolut"]),
    App("wise", "Wise", brand("#9FE870"), T("W", width=0.52, height=0.54), fg="#163300",
        packages=["com.transferwise.android"]),
    App("binance", "Binance", brand("#F0B90B"), T("B", width=0.42, height=0.6), fg="#181A20",
        packages=["com.binance.dev"]),
    App("trust_wallet", "Trust Wallet", brand("#3375BB"), M("shield"), scale=0.48,
        packages=["com.wallet.crypto.trustapp"]),
    App("metamask", "MetaMask", brand("#F6851B"), M("shield"), scale=0.48,
        packages=["io.metamask"]),
    App("waze", "Waze", brand("#33CCFF"), M("maps_pin"), fg="#FFFFFF", scale=0.5,
        packages=["com.waze"]),

    # --- browsers, privacy, utility -------------------------------------------- #
    App("firefox", "Firefox", brand("#FF7139"), M("globe"), scale=0.5,
        packages=["org.mozilla.firefox", "org.mozilla.focus"],
        components=["org.mozilla.firefox/org.mozilla.fenix.HomeActivity",
                    "org.mozilla.firefox/org.mozilla.gecko.BrowserApp"]),
    App("opera", "Opera", brand("#FF1B2D"), T("O", width=0.46, height=0.6),
        packages=["com.opera.browser", "com.opera.mini.native", "com.opera.gx"]),
    App("brave", "Brave", brand("#FB542B"), M("shield"), scale=0.48,
        packages=["com.brave.browser"]),
    App("edge", "Edge", brand("#0F7FCB"), M("globe"), scale=0.5,
        packages=["com.microsoft.emmx"]),
    App("duckduckgo", "DuckDuckGo", brand("#DE5833"), M("search"), scale=0.48,
        packages=["com.duckduckgo.mobile.android"]),
    App("proton_mail", "Proton Mail", brand("#6D4AFF"), M("envelope"), scale=0.5,
        packages=["ch.protonmail.android"]),
    App("proton_vpn", "Proton VPN", brand("#4A34C4"), M("shield"), scale=0.48,
        packages=["ch.protonvpn.android"]),
    App("nordvpn", "NordVPN", brand("#4687FF"), M("shield"), scale=0.48,
        packages=["com.nordvpn.android"]),
    App("tor", "Tor Browser", brand("#7D4698"), M("globe"), scale=0.5,
        packages=["org.torproject.torbrowser"]),

    # --- lifestyle -------------------------------------------------------------- #
    App("duolingo", "Duolingo", brand("#58CC02"), M("cap"), scale=0.52,
        packages=["com.duolingo"]),
    App("strava", "Strava", brand("#FC4C02"), M("bolt"), scale=0.46,
        packages=["com.strava"]),
    App("mcdonalds", "McDonald's", brand("#DA291C"), T("M", width=0.5, height=0.58), fg="#FFC72C",
        packages=["com.mcdonalds.mobileapp", "com.mcdonalds.app"]),
    App("starbucks", "Starbucks", brand("#00704A"), M("star"), scale=0.48,
        packages=["com.starbucks.mobilecard"]),
    App("kindle", "Kindle", graphite("#FF9900"), M("book"), scale=0.5,
        packages=["com.amazon.kindle"]),
    App("capcut", "CapCut", graphite("#00E5E5"), M("film"), scale=0.48,
        packages=["com.lemon.lvoverseas"]),
    App("picsart", "Picsart", brand("#C209C1"), M("camera"), scale=0.5,
        packages=["com.picsart.studio"]),
    App("lightroom", "Lightroom", brand("#0D66D0"), M("camera"), scale=0.5,
        packages=["com.adobe.lrmobile"]),
    App("imdb", "IMDb", brand("#F5C518"), T("i", face="grotesk", width=0.28, height=0.6), fg="#1A1A1A",
        packages=["com.imdb.mobile"]),

    # --- more of the global shelf ------------------------------------------ #
    App("wechat", "WeChat", brand("#07C160"), M("bubble"), scale=0.5,
        packages=["com.tencent.mm"],
        components=["com.tencent.mm/com.tencent.mm.ui.LauncherUI"]),
    App("line", "LINE", brand("#06C755"), M("bubble"), scale=0.5,
        packages=["jp.naver.line.android"]),
    App("kakaotalk", "KakaoTalk", brand("#FEE500"), M("bubble"), fg="#1A1A1A", scale=0.5,
        packages=["com.kakao.talk"]),
    App("element", "Element", brand("#0DBD8B"), M("bubble"), scale=0.48,
        packages=["im.vector.app"]),
    App("tinder", "Tinder", brand("#FE3C72"), M("heart"), scale=0.48,
        packages=["com.tinder"]),
    App("bumble", "Bumble", brand("#FFC629"), M("heart"), fg="#1A1A1A", scale=0.48,
        packages=["com.bumble.app"]),
    App("wikipedia", "Wikipedia", porcelain("#8E97A8"), T("W", width=0.54, height=0.54), fg="#101418",
        packages=["org.wikipedia"]),
    App("coursera", "Coursera", brand("#0056D2"), M("cap"), scale=0.52,
        packages=["org.coursera.android"]),
    App("udemy", "Udemy", brand("#A435F0"), M("cap"), scale=0.52,
        packages=["com.udemy.android"]),
    App("khan", "Khan Academy", brand("#14BF96"), M("cap"), scale=0.52,
        packages=["org.khanacademy.android"]),
    App("deepl", "DeepL", brand("#0F2B46"), M("translate"), scale=0.52,
        packages=["com.deepl.mobiletranslator"]),
    App("grammarly", "Grammarly", brand("#15C39A"), T("G", width=0.46, height=0.58),
        packages=["com.grammarly.android.keyboard"]),
    App("audible", "Audible", brand("#F8991C"), M("book"), fg="#1A1A1A", scale=0.5,
        packages=["com.audible.application"]),
    App("pocketcasts", "Pocket Casts", brand("#F43E37"), M("mic"), scale=0.48,
        packages=["au.com.shiftyjelly.pocketcasts"]),
    App("mxplayer", "MX Player", brand("#3F51B5"), M("play_triangle"), scale=0.44,
        packages=["com.mxtech.videoplayer.ad", "com.mxtech.videoplayer.pro"]),
    App("plex", "Plex", graphite("#E5A00D"), M("play_triangle"), fg="#E5A00D", scale=0.44,
        packages=["com.plexapp.android"]),
    App("kodi", "Kodi", brand("#17B2E7"), M("tv"), scale=0.5,
        packages=["org.xbmc.kodi"]),
    App("vimeo", "Vimeo", brand("#1AB7EA"), M("play_triangle"), scale=0.44,
        packages=["com.vimeo.android.videoapp"]),
    App("snapseed", "Snapseed", brand("#F5C518"), M("camera"), fg="#1A1A1A", scale=0.5,
        packages=["com.niksoftware.snapseed"]),
    App("inshot", "InShot", brand("#FF4E63"), M("film"), scale=0.48,
        packages=["com.camerasideas.instashot"]),
    App("chess", "Chess.com", brand("#7FA650"), M("chess_pawn"), scale=0.5,
        packages=["com.chess"]),
    App("myfitnesspal", "MyFitnessPal", brand("#0066EE"), M("heart"), scale=0.46,
        packages=["com.myfitnesspal.android"]),
    App("calm", "Calm", brand("#2F6BFF"), M("weather"), scale=0.52,
        packages=["com.calm.android"]),
    App("headspace", "Headspace", brand("#FF7E1D"), M("weather"), scale=0.52,
        packages=["com.getsomeheadspace.android"]),
    App("flo", "Flo", brand("#FF5E8A"), M("heart"), scale=0.46,
        packages=["org.iggymedia.periodtracker"]),
    App("garmin", "Garmin Connect", graphite("#00A6E0"), M("heart"), scale=0.46,
        packages=["com.garmin.android.apps.connectmobile"]),
    App("fitbit", "Fitbit", brand("#00B0B9"), M("heart"), scale=0.46,
        packages=["com.fitbit.FitbitMobile"]),
    App("mihome", "Mi Home", brand("#FF6900"), M("gear"), scale=0.48,
        packages=["com.xiaomi.smarthome"]),
    App("anydesk", "AnyDesk", brand("#EF443B"), M("qr"), scale=0.46,
        packages=["com.anydesk.anydeskandroid"]),
    App("teamviewer", "TeamViewer", brand("#0E8EE9"), M("globe"), scale=0.5,
        packages=["com.teamviewer.teamviewer.market.mobile"]),
    App("acrobat", "Acrobat", brand("#B30B00"), M("doc_page"), scale=0.5,
        packages=["com.adobe.reader"]),
    App("truecaller", "Truecaller", brand("#0F7AE5"), M("handset"), scale=0.48,
        packages=["com.truecaller"]),
    App("bitwarden", "Bitwarden", brand("#175DDC"), M("shield"), scale=0.48,
        packages=["com.x8bit.bitwarden"]),
    App("authenticator", "Authenticator", brand("#4285F4"), M("qr"), scale=0.46,
        packages=["com.google.android.apps.authenticator2", "com.azure.authenticator"]),
    App("flightradar", "Flightradar24", brand("#FFCC00"), M("plane"), fg="#1A1A1A", scale=0.52,
        packages=["com.flightradar24free"]),
    App("windy", "Windy", brand("#1F7BD0"), M("weather"), scale=0.54,
        packages=["com.windyty.android"]),
    App("accuweather", "AccuWeather", brand("#FF6B00"), M("weather"), scale=0.54,
        packages=["com.accuweather.android"]),
    App("osmand", "OsmAnd", brand("#5B9E4B"), M("maps_pin"), fg="#FFFFFF", scale=0.5,
        packages=["net.osmand", "net.osmand.plus"]),
    App("google_earth", "Google Earth", brand("#1A73E8"), M("globe"), scale=0.52,
        packages=["com.google.earth"]),
    App("zedge", "Zedge", brand("#7C3AED"), M("gallery"), scale=0.5,
        packages=["net.zedge.android"]),
    App("nova_launcher", "Nova Launcher", brand("#F5A623"), M("cards_stack"), scale=0.54,
        packages=["com.teslacoilsw.launcher"],
        components=["com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher"]),
    App("lawnchair", "Lawnchair", brand("#3DDC84"), M("cards_stack"), scale=0.54,
        packages=["app.lawnchair", "ch.deletescape.lawnchair.plah"]),
    App("niagara", "Niagara Launcher", graphite("#8E97A8"), M("cards_stack"), scale=0.54,
        packages=["bitpit.launcher"]),
    App("smart_launcher", "Smart Launcher", brand("#2196F3"), M("cards_stack"), scale=0.54,
        packages=["ginlemon.flowerfree", "ginlemon.flowerpro"]),
    App("kwgt", "KWGT", brand("#607D8B"), M("gear"), scale=0.48,
        packages=["org.kustom.widget"]),
    App("tasker", "Tasker", brand("#4CAF50"), M("gear"), scale=0.48,
        packages=["net.dinglisch.android.taskerm"]),
]
