# -*- coding: utf-8 -*-
"""Ukrainian apps: banking, state services, delivery, retail, telecom, media."""

from catalog import App, M, T, brand, brand_glow, graphite, porcelain

APPS = [
    # --- state services --------------------------------------------------- #
    App("diia", "Дія", graphite("#4B7BEC"), T("Дія", width=0.84),
        packages=["ua.gov.diia.app", "ua.gov.diia"],
        components=["ua.gov.diia.app/ua.gov.diia.ui.main.MainActivity",
                    "ua.gov.diia.app/ua.gov.diia.app.MainActivity"], tags=["ua", "gov"]),
    App("diia_business", "Дія.Бізнес", graphite("#37C2A0"), T("Дія.Б", width=0.88),
        packages=["ua.gov.diia.business"], tags=["ua", "gov"]),
    App("army_plus", "Армія+", brand("#4C5A3A"), M("cross_med"), scale=0.46,
        packages=["ua.gov.mou.armyplus", "ua.gov.armyplus", "com.armyplus.app"], tags=["ua", "gov"]),
    App("reserve_plus", "Резерв+", brand("#5A6B45"), M("shield"), scale=0.50,
        packages=["ua.gov.mou.reserveplus", "ua.gov.reserveplus"], tags=["ua", "gov"]),
    App("mriia", "Мрія", brand_glow("#1E64D2", "#FFD500"), M("cap"), scale=0.54,
        packages=["ua.gov.mriia", "ua.gov.diia.mriia"], tags=["ua", "gov"]),
    App("kyiv_digital", "Київ Цифровий", brand("#1665D8"), T("К", width=0.5, height=0.62),
        packages=["ua.kyivsmartcity.mobile", "com.kyivsmartcity", "ua.gov.kyivdigital"], tags=["ua", "gov"]),
    App("air_alert", "Повітряна тривога", brand("#D32029"), M("siren"), scale=0.54,
        packages=["ua.gov.airalert", "com.ajax.airalarm", "com.ajaxsystems.airalert",
                  "ua.gov.diia.airalert"], tags=["ua", "gov"]),
    App("alerts_in_ua", "Alerts.in.ua", graphite("#FF4D4F"), M("siren"), scale=0.50,
        packages=["ua.in.alerts", "com.alertsinua.app"], tags=["ua"]),
    App("eherga", "єЧерга", brand("#2563EB"), M("qr"), scale=0.48,
        packages=["ua.gov.dmsu.echerha", "ua.gov.echerga"], tags=["ua", "gov"]),
    App("prozorro", "Prozorro", brand("#0F5FA6"), T("P", width=0.44, height=0.6),
        packages=["ua.gov.prozorro"], tags=["ua", "gov"]),

    # --- banking ---------------------------------------------------------- #
    App("monobank", "monobank", graphite("#6E7B8F"), T("mono", face="grotesk", width=0.8),
        packages=["com.ftband.mono", "com.ftband.mono.iron"],
        components=["com.ftband.mono/com.ftband.mono.MainActivity",
                    "com.ftband.mono/com.ftband.app.splash.SplashActivity"], tags=["ua", "bank"]),
    App("privat24", "Приват24", brand("#5BA829"), T("24", width=0.66, height=0.56),
        packages=["ua.privatbank.ap24", "ua.privatbank.ap24v6"],
        components=["ua.privatbank.ap24/ua.privatbank.ap24.MainActivity",
                    "ua.privatbank.ap24/ua.privatbank.ap24.beta.activity.MainActivity"], tags=["ua", "bank"]),
    App("sense_bank", "Sense SuperApp", brand("#D6002A"), T("S", width=0.42, height=0.62),
        packages=["ua.alfabank.mobile.android", "ua.sensebank.mobile", "ua.sensesuperapp.mobile"],
        tags=["ua", "bank"]),
    App("pumb", "ПУМБ Online", brand("#A5152A"), T("ПУМБ", width=0.86, height=0.4),
        packages=["com.fuib.android.spot.online", "ua.pumb.online"], tags=["ua", "bank"]),
    App("oschadbank", "Ощад 24/7", brand("#0B7A3E"), T("Ощад", width=0.86, height=0.42),
        packages=["ua.oschadbank.online", "com.oschadbank.mobile", "ua.oschadbank.mobile"],
        tags=["ua", "bank"]),
    App("abank", "A-Bank", graphite("#E4002B"), T("A", width=0.44, height=0.62),
        packages=["ua.abank24.mobile", "com.abank24.mobile"], tags=["ua", "bank"]),
    App("izibank", "izibank", brand("#7A43F5"), T("izi", width=0.7),
        packages=["ua.izibank.app", "com.izibank.mobile"], tags=["ua", "bank"]),
    App("raiffeisen", "Raiffeisen", brand("#FFE000"), T("R", width=0.44, height=0.62), fg="#0F1115",
        packages=["ua.aval.myraif", "com.rba.myraif", "ua.com.aval.myraif"], tags=["ua", "bank"]),
    App("otp_smart", "OTP Smart", brand("#4FA72E"), T("OTP", width=0.82, height=0.42),
        packages=["ua.otpbank.otpsmart", "ua.otpbank.smart"], tags=["ua", "bank"]),
    App("ukrsib", "UKRSIB online", brand("#0E7C5A"), T("US", width=0.68, height=0.5),
        packages=["ua.ukrsibbank.online", "ua.ukrsibbank.client"], tags=["ua", "bank"]),
    App("credit_agricole", "Credit Agricole", brand("#007B5F"), T("CA", width=0.7, height=0.48),
        packages=["ua.creditagricole.mobile", "com.creditagricole.ua"], tags=["ua", "bank"]),
    App("novapay", "NovaPay", brand("#D22630"), M("wallet"), scale=0.52,
        packages=["ua.novapay.app", "ua.novapay.mobile"], tags=["ua", "bank"]),

    # --- delivery & logistics --------------------------------------------- #
    App("nova_poshta", "Нова пошта", brand("#DA291C"), T("NP", width=0.7, height=0.5),
        packages=["ua.novaposhta.online", "ua.novaposhta.mobile", "com.novaposhta.app"],
        components=["ua.novaposhta.online/ua.novaposhta.online.MainActivity"], tags=["ua"]),
    App("ukrposhta", "Укрпошта", brand_glow("#FFD100", "#FFE873"), M("envelope"), fg="#123A6B", scale=0.52,
        packages=["ua.ukrposhta.mobile", "com.ukrposhta.tracking", "ua.gov.ukrposhta"], tags=["ua"]),
    App("meest", "Meest", brand("#1F4FA3"), M("parcel"), scale=0.52,
        packages=["ua.meest.mobile", "com.meest.express"], tags=["ua"]),
    App("justin", "Justin", brand("#F07E26"), M("parcel"), scale=0.52,
        packages=["ua.justin.mobile", "com.justin.ua"], tags=["ua"]),

    # --- marketplaces & retail -------------------------------------------- #
    App("rozetka", "Rozetka", brand("#00A046"), T("r", face="grotesk", width=0.4, height=0.6),
        packages=["ua.com.rozetka.shop"],
        components=["ua.com.rozetka.shop/ua.com.rozetka.shop.ui.splash.SplashActivity",
                    "ua.com.rozetka.shop/ua.com.rozetka.shop.screen.splash.SplashActivity"], tags=["ua"]),
    App("olx", "OLX", brand("#6E0AD6"), T("olx", width=0.8),
        packages=["ua.slando", "com.olx.ua"],
        components=["ua.slando/com.olxgroup.olx.MainActivity",
                    "ua.slando/pl.tablica.activities.HomeActivity"], tags=["ua"]),
    App("prom", "Prom.ua", brand("#1F4FD8"), T("prom", width=0.84, height=0.4),
        packages=["ua.prom.b2c", "com.prom.ua"], tags=["ua"]),
    App("kasta", "Kasta", graphite("#FF3B6B"), T("K", width=0.44, height=0.62),
        packages=["ua.modnakasta", "com.kasta.android"], tags=["ua"]),
    App("shafa", "Shafa", brand("#22B573"), T("Ш", width=0.5, height=0.58),
        packages=["ua.shafa.app", "com.shafa.ua"], tags=["ua"]),
    App("silpo", "Сільпо", brand("#D81E28"), T("С", width=0.46, height=0.62),
        packages=["ua.silpo.mobile", "com.silpo.ua", "ua.com.silpo"], tags=["ua"]),
    App("atb", "АТБ-Маркет", brand("#00963F"), T("АТБ", width=0.84, height=0.42),
        packages=["com.atbmarket.android", "ua.com.atbmarket.mobile"], tags=["ua"]),
    App("varus", "Varus", brand("#1E5AA8"), M("cart"), scale=0.5,
        packages=["ua.varus.mobile", "com.varus.ua"], tags=["ua"]),
    App("novus", "Novus", brand("#E1251B"), M("cart"), scale=0.5,
        packages=["ua.novus.mobile", "com.novus.ua"], tags=["ua"]),
    App("fora", "Fora", brand("#00A651"), M("cart"), scale=0.5,
        packages=["ua.fora.mobile", "com.fora.ua"], tags=["ua"]),
    App("aurora", "Аврора", brand("#F5C400"), T("А", width=0.46, height=0.6), fg="#1A1A1A",
        packages=["ua.aurora.app", "com.aurora.multimarket"], tags=["ua"]),
    App("eva", "EVA", brand("#E5007D"), T("eva", width=0.78),
        packages=["ua.eva.mobile", "com.eva.ua"], tags=["ua"]),
    App("comfy", "Comfy", brand("#F5811F"), T("C", width=0.44, height=0.62),
        packages=["ua.comfy.mobile", "com.comfy.ua"], tags=["ua"]),
    App("foxtrot", "Foxtrot", brand("#E4002B"), T("F", width=0.42, height=0.62),
        packages=["ua.foxtrot.mobile", "com.foxtrot.ua"], tags=["ua"]),
    App("allo", "Allo", brand("#E3000F"), T("allo", width=0.84, height=0.4),
        packages=["ua.allo.mobile", "com.allo.ua"], tags=["ua"]),
    App("epicentr", "Епіцентр", brand("#E52421"), T("E", width=0.44, height=0.62),
        packages=["ua.epicentrk.mobile", "com.epicentrk.ua"], tags=["ua"]),
    App("autoria", "AUTO.RIA", brand("#0E7C3A"), M("taxi"), scale=0.54,
        packages=["ua.auto.ria", "ua.ria.auto"], tags=["ua"]),
    App("work_ua", "Work.ua", brand("#0F6FD1"), T("W", width=0.52, height=0.56),
        packages=["ua.work.app", "com.workua.android"], tags=["ua"]),
    App("robota_ua", "Robota.ua", brand("#F05A28"), T("R", width=0.44, height=0.62),
        packages=["ua.robota.app", "ua.rabota.app"], tags=["ua"]),

    # --- transport & fuel -------------------------------------------------- #
    App("uklon", "Uklon", graphite("#FFD400"), T("U", width=0.46, height=0.6), fg="#FFD400",
        packages=["com.uklontaxi", "ua.com.uklon.uklon"], tags=["ua"]),
    App("ukrzaliznytsia", "Укрзалізниця", brand_glow("#0057B8", "#FFD500"), M("train"), scale=0.54,
        packages=["ua.gov.uz.app", "com.uz.tickets", "ua.uz.mobile"], tags=["ua"]),
    App("wog", "WOG", brand("#D6001C"), M("fuel"), scale=0.5,
        packages=["ua.wog.app", "com.wog.pride", "ua.com.wog"], tags=["ua"]),
    App("okko", "OKKO", brand("#E63329"), M("fuel"), scale=0.5,
        packages=["ua.okko.app", "com.okko.ua"], tags=["ua"]),
    App("socar", "SOCAR", brand("#00A1E0"), M("fuel"), scale=0.5,
        packages=["ua.socar.app", "com.socar.ua"], tags=["ua"]),
    App("fishka", "Fishka", brand("#E4002B"), M("star"), scale=0.5,
        packages=["ua.fishka.app", "com.fishka.ua"], tags=["ua"]),

    # --- telecom ----------------------------------------------------------- #
    App("kyivstar", "Київстар", brand("#0072BC"), M("star"), scale=0.52,
        packages=["ua.kyivstar.mykyivstar", "com.kyivstar.mykyivstar", "ua.kyivstar.app"], tags=["ua"]),
    App("kyivstar_tv", "Київстар ТБ", brand("#00427A"), M("tv"), scale=0.52,
        packages=["com.kyivstar.tv.mobile", "ua.kyivstar.tv"], tags=["ua"]),
    App("vodafone_ua", "Vodafone UA", brand("#E60000"), M("bubble"), scale=0.48,
        packages=["ua.vodafone.myvodafone", "com.vodafone.ua"], tags=["ua"]),
    App("lifecell", "lifecell", brand("#A9CE2C"), T("l", width=0.3, height=0.6), fg="#1A1A1A",
        packages=["com.lifecell.lifecellmobile", "ua.lifecell.myaccount"], tags=["ua"]),

    # --- media -------------------------------------------------------------- #
    App("megogo", "Megogo", brand("#7B2BFF"), T("M", width=0.52, height=0.56),
        packages=["com.megogo.application"],
        components=["com.megogo.application/com.megogo.application.SplashActivity"], tags=["ua"]),
    App("sweettv", "sweet.tv", brand("#FF6B00"), M("tv"), scale=0.5,
        packages=["tv.sweet.player"], tags=["ua"]),
    App("suspilne", "Суспільне", graphite("#00A3E0"), T("С", width=0.46, height=0.62),
        packages=["ua.suspilne.news", "ua.suspilne.mobile"], tags=["ua"]),
    App("pravda", "Українська правда", graphite("#E4002B"), T("УП", width=0.72, height=0.48),
        packages=["ua.pravda.app", "com.pravda.ua"], tags=["ua"]),
    App("unian", "УНІАН", brand("#0B4DA2"), T("У", width=0.46, height=0.6),
        packages=["ua.unian.app", "com.unian.news"], tags=["ua"]),
    App("multiplex", "Multiplex", brand("#E30613"), M("film"), scale=0.5,
        packages=["ua.multiplex.app", "com.multiplex.ua"], tags=["ua"]),
    App("planetakino", "Планета Кіно", brand("#5B2C8D"), M("film"), scale=0.5,
        packages=["ua.planetakino.app", "com.planetakino.ua"], tags=["ua"]),
    App("ukrnet", "ukr.net", brand("#1B75BB"), M("envelope"), scale=0.5,
        packages=["ua.net.ukr.mail", "net.ukr.mail", "ua.ukr.net.mail"], tags=["ua"]),
    App("sinoptik", "Sinoptik", brand("#2E9BD6"), M("weather"), scale=0.56,
        packages=["ua.sinoptik.app", "com.sinoptik.ua"], tags=["ua"]),

    # --- health -------------------------------------------------------------- #
    App("helsi", "Helsi", brand("#00A9A5"), M("cross_med"), scale=0.46,
        packages=["ua.helsi.patient", "com.helsi.ua"], tags=["ua"]),
    App("liki24", "Liki24", brand("#00B267"), M("pill"), scale=0.52,
        packages=["com.liki24.app", "ua.liki24.mobile"], tags=["ua"]),
    App("tabletki", "Tabletki.ua", brand("#1E7BD6"), M("pill"), scale=0.52,
        packages=["ua.tabletki.app", "com.tabletki.ua"], tags=["ua"]),
    App("apteka911", "Аптека 911", brand("#1AA053"), M("cross_med"), scale=0.46,
        packages=["ua.apteka911.app", "com.apteka911.ua"], tags=["ua"]),
    App("ajax", "Ajax Security", graphite("#3B82F6"), M("shield"), scale=0.5,
        packages=["com.ajaxsystems"], tags=["ua"]),

    # --- payments, utilities, everyday services ---------------------------- #
    App("sportbank", "Sportbank", graphite("#FF4D00"), T("s", face="grotesk", width=0.34, height=0.6),
        packages=["ua.sportbank.mobile", "com.sportbank.ua"], tags=["ua", "bank"]),
    App("vlasnyi_rakhunok", "Власний рахунок", brand("#1D4ED8"), M("card"), scale=0.5,
        packages=["ua.vlasnyirakhunok.mobile"], tags=["ua", "bank"]),
    App("easypay", "EasyPay", brand("#F5A623"), M("card"), fg="#1A1A1A", scale=0.5,
        packages=["ua.easypay.mobile", "com.easypay.ua"], tags=["ua"]),
    App("portmone", "Portmone", brand("#0E9F6E"), M("wallet"), scale=0.5,
        packages=["ua.portmone.mobile", "com.portmone.ua"], tags=["ua"]),
    App("ipay", "iPay.ua", brand("#00A3E0"), M("card"), scale=0.5,
        packages=["ua.ipay.mobile", "com.ipay.ua"], tags=["ua"]),
    App("yasno", "YASNO", brand("#FFD400"), M("bolt"), fg="#1A1A1A", scale=0.46,
        packages=["com.yasno.app", "ua.dtek.yasno", "com.dtek.yasno"], tags=["ua"]),
    App("rocket", "Rocket", brand("#FF3B30"), M("plane"), scale=0.5,
        packages=["com.rocket.ua", "ua.rocket.delivery"], tags=["ua"]),
    App("zakaz", "Zakaz.ua", brand("#00B050"), M("cart"), scale=0.5,
        packages=["ua.zakaz.mobile", "com.zakaz.ua"], tags=["ua"]),
    App("auchan", "Auchan", brand("#E2001A"), M("cart"), scale=0.5,
        packages=["com.auchan.ua", "ua.auchan.mobile"], tags=["ua"]),
    App("metro_ua", "METRO", brand("#003D7D"), M("cart"), scale=0.5,
        packages=["com.metro.ua", "de.metro.companion"], tags=["ua"]),
    App("prostor", "Prostor", brand("#E6007E"), T("П", width=0.46, height=0.6),
        packages=["ua.prostor.mobile", "com.prostor.ua"], tags=["ua"]),
    App("watsons", "Watsons", brand("#00A651"), T("W", width=0.52, height=0.54),
        packages=["ua.watsons.mobile", "com.watsons.ua"], tags=["ua"]),
    App("docua", "Doc.ua", brand("#009FE3"), M("cross_med"), scale=0.46,
        packages=["ua.doc.mobile", "com.docua.android"], tags=["ua"]),
    App("tsn", "ТСН", brand("#D8232A"), T("ТСН", width=0.84, height=0.42),
        packages=["ua.tsn.app", "ua.unian.tsn"], tags=["ua"]),
    App("nv", "НВ", graphite("#E4002B"), T("НВ", width=0.66, height=0.5),
        packages=["ua.nv.app", "com.nv.ua"], tags=["ua"]),
    App("diia_osvita", "Дія.Освіта", brand("#2563EB"), M("cap"), scale=0.52,
        packages=["ua.gov.diia.osvita"], tags=["ua", "gov"]),
    App("uklon_driver", "Uklon Driver", graphite("#FFD400"), M("taxi"), fg="#FFD400", scale=0.52,
        packages=["ua.com.uklon.uklondriver"], tags=["ua"]),
    App("blablacar", "BlaBlaCar", brand("#00AFF5"), M("taxi"), scale=0.52,
        packages=["com.comuto"], tags=["ua"]),
    App("infobus", "Infobus", brand("#F57C00"), M("ticket"), scale=0.5,
        packages=["ua.infobus.app", "com.infobus.ua"], tags=["ua"]),
    App("citycard", "Львівська е-картка", brand("#0F766E"), M("card"), scale=0.5,
        packages=["ua.lvivcard.mobile", "ua.gov.lviv.card"], tags=["ua"]),
]
