extends Node
## Localization table (sole owner: WS4 hub UI; other workstreams send key lists). Ukrainian is
## the primary language, English the fallback. Keys follow arsenal_design.md §9.5 / §11.

signal language_changed

const LANGS: Array[String] = ["uk", "en"]

const STRINGS := {
	"GAME_TITLE": ["Кришталевий Ривок", "Crystal Rush"],
	"GAME_TAGLINE": ["Веди армію, збирай зброю, бери фортецю", "Lead the army, grab the guns, take the fortress"],
	"PLAY_LEVEL": ["Рівень %d", "Level %d"],
	"LEVEL": ["Рівень %d", "Level %d"],
	"CHOOSE_HERO": ["Обери героя", "Choose your hero"],
	"HERO_BOLT": ["Блискавка", "Bolt"],
	"HERO_BOLT_DESC": ["Швидкий лис: часті блискавки здалеку", "Swift fox: rapid lightning from afar"],
	"HERO_TITAN": ["Громило", "Titan"],
	"HERO_TITAN_DESC": ["Кам’яний вартовий: важкі удари по натовпу", "Stone guardian: heavy blows that hit a crowd"],
	"ULT_STORM": ["Громовий вихор!", "Thunder vortex!"],
	"ULT_QUAKE": ["Смарагдовий розлом!", "Emerald quake!"],
	"UPGRADE_ARMY": ["Армія", "Army"],
	"UPGRADE_ARMY_DESC": ["+2 воїни на старті", "+2 soldiers at the start"],
	"UPGRADE_POWER": ["Сила героя", "Hero power"],
	"UPGRADE_POWER_DESC": ["+12% швидкість атак", "+12% attack speed"],
	"MAX": ["Макс.", "Max"],
	"VICTORY": ["Перемога!", "Victory!"],
	"DEFEAT": ["Поразка", "Defeat"],
	"FORTRESS_FALLS": ["Фортецю взято!", "The fortress falls!"],
	"ARMY_LOST": ["Армію розбито", "Your army was routed"],
	"NOT_ENOUGH": ["Забракло сил на браму", "Not enough strength for the gate"],
	"COINS_EARNED": ["+%d монет", "+%d coins"],
	"NEXT": ["Далі", "Next"],
	"RETRY": ["Ще раз", "Retry"],
	"MENU": ["Меню", "Menu"],
	"PAUSED": ["Пауза", "Paused"],
	"RESUME": ["Продовжити", "Resume"],
	"SETTINGS": ["Налаштування", "Settings"],
	"MUSIC": ["Музика", "Music"],
	"SOUND": ["Звуки", "Sounds"],
	"LANGUAGE": ["Мова", "Language"],
	"LANG_NAME": ["Українська", "English"],
	"GRAPHICS": ["Графіка", "Graphics"],
	"QUALITY_HIGH": ["Висока", "High"],
	"QUALITY_LOW": ["Економна", "Battery saver"],
	"VIBRATION": ["Вібрація", "Vibration"],
	"ON": ["Увімк.", "On"],
	"OFF": ["Вимк.", "Off"],
	"CLOSE": ["Закрити", "Close"],
	"ULT_READY": ["Ульта готова!", "Ultimate ready!"],
	"ULT": ["Ульта", "Ult"],
	"WORLD_SPACE": ["Орбітальна траса", "Orbital Track"],
	# Run: control and tutorial hints
	"DRAG_HINT": ["Тягни, щоб вести армію", "Drag to lead your army"],
	"HINT_DRAG": ["Тягни, щоб вести армію", "Drag to lead your army"],
	"HINT_GATES": ["Обирай ворота з кращим числом", "Pick the gate with the better number"],
	"HINT_FORECAST": ["Під воротами — скільки воїнів стане", "Under each gate: your army after it"],
	"HINT_CRATE": ["Стріляй по ящику — забери зброю!", "Shoot the crate to grab the weapon!"],
	"HINT_CHARGE": ["Веди героя на ворота — постріли їх перевернуть", "Aim your hero at the gate: shots flip it"],
	"HINT_ULT": ["Тисни ульту!", "Hit your ultimate!"],
	"HINT_SPIKES": ["Шипи вбивають воїнів — обходь краєм", "Spikes kill soldiers: slip past the edge"],
	"HINT_BLADES": ["Чекай, поки лезо пройде", "Wait for the blade to pass"],
	"HINT_RECRUITS": ["Збирай сірих рекрутів", "Pick up the grey recruits"],
	"HINT_ARM": ["Арбалети стріляють ще до бою", "Crossbows fire before the clash"],
	"HINT_TURRET": ["Збий турель, поки вона косить армію", "Take the turret down before it mows your army"],
	"HINT_GEODE": ["Розбий жеоду — там нагорода", "Crack the geode: there is a prize inside"],
	# Weapons and power-ups
	"NEW_WEAPON": ["Нова зброя", "New weapon"],
	"WEAPON_GOT": ["%s!", "%s!"],
	"WEAPON_UP": ["%s ★%d", "%s ★%d"],
	"W_BALLISTA": ["Балиста", "Ballista"],
	"W_CANNON": ["Плазмова гармата", "Plasma cannon"],
	"W_LASER": ["Лазер", "Laser"],
	"W_ROCKETS": ["Ракетниця", "Rocket launcher"],
	"W_DRONE": ["Дрон", "Drone"],
	"ARM_SPEAR": ["Списи", "Spears"],
	"ARM_CROSSBOW": ["Арбалети", "Crossbows"],
	"ARM_BLASTER": ["Бластери", "Blasters"],
	"ARMY_ARMED": ["Армія озброєна", "Army armed"],
	"POWER_RATE": ["+%d%% швидкість", "+%d%% attack speed"],
	"POWER_DMG": ["+%d шкода", "+%d damage"],
	"POWER_MULTI": ["+1 постріл", "+1 shot"],
	"HERO_POWER": ["Сила героя", "Hero power"],
	"ARMOR": ["Смарагдова броня!", "Emerald armour!"],
	# Result
	"STAIRS_MULT": ["×%s", "×%s"],
	"MULTIPLIER": ["Множник", "Multiplier"],
	"SURVIVORS": ["Вижило: %d", "Survivors: %d"],
	"COINS_BASE": ["За перемогу", "Victory bonus"],
	"COINS_COLLECTED": ["Зібрано", "Collected"],
	"COINS_TOTAL": ["Разом", "Total"],
	# ---------------------------------------------------------------- Meta-1 (meta1_contracts.md §10)
	# Machines (24; meta2 cards show the name + "Скоро")
	"M_DRONE": ["Дрон", "Drone"],
	"M_DRONE_DESC": ["Летить до цілі героя, позначає її для всього арсеналу", "Flies to the hero's target and marks it for the whole arsenal"],
	"M_BALLISTA": ["Балиста", "Ballista"],
	"M_BALLISTA_DESC": ["Болт у смузі героя пробиває кілька цілей поспіль", "A bolt down the hero's lane pierces a line of targets"],
	"M_CANNON": ["Плазмова гармата", "Plasma Cannon"],
	"M_CANNON_DESC": ["Плазмова куля по цілі героя: сплеск і підпал", "A plasma orb at the hero's target: splash and Burn"],
	"M_ROCKETS": ["Ракетниця", "Rocket Pod"],
	"M_ROCKETS_DESC": ["Залп ракет із самонаведенням, сильний проти споруд", "A homing salvo that wrecks structures"],
	"M_MORTAR": ["Облогова мортира", "Siege Mortar"],
	"M_MORTAR_DESC": ["Снаряд падає за 12 кроків перед героєм — наведи кільце", "A shell lands 12 u ahead of the hero: steer the ring"],
	"M_GATLING": ["Гатлінг", "Gatling"],
	"M_GATLING_DESC": ["Шквал куль із рикошетом, розриває рої", "A ricocheting bullet stream that shreds swarms"],
	"M_LASER": ["Лазер", "Laser"],
	"M_LASER_DESC": ["Промінь у смузі героя розжарюється на одній цілі", "A beam down the hero's lane that ramps on one target"],
	"M_RAILGUN": ["Рейкова гармата", "Railgun"],
	"M_RAILGUN_DESC": ["Заряджений постріл прошиває всю смугу й фортецю", "A charged shot through the whole lane and the fortress"],
	"M_PRISM": ["Призма", "Prism"],
	"M_PRISM_DESC": ["Посилює кожен постріл, що пролітає крізь неї", "Amplifies every shot that passes through it"],
	"M_TESLA": ["Котушка Тесли", "Tesla Coil"],
	"M_TESLA_DESC": ["Дуга перестрибує між загонами", "An arc that jumps between squads"],
	"M_BANNER": ["Бойовий штандарт", "War Banner"],
	"M_BANNER_DESC": ["Сильніші залпи армії, менші втрати в бою", "Stronger army volleys, fewer clash losses"],
	"M_CRYO": ["Кріо-гармата", "Cryo Sprayer"],
	"M_CRYO_DESC": ["Конус холоду заморожує загін перед боєм", "A cold cone freezes a squad before the clash"],
	"M_FROST_MINER": ["Крижаний мінер", "Frost Miner"],
	"M_FROST_MINER_DESC": ["Міни морозять загони, леза й лаву", "Mines freeze squads, blades and lava"],
	"M_RAM": ["Облоговий таран", "Siege Ram"],
	"M_RAM_DESC": ["Ривок, що трощить барикади й браму", "A dash that smashes barricades and the gate"],
	"M_HARVESTER": ["Збирач", "Harvester"],
	"M_HARVESTER_DESC": ["Притягує здобич біля краю армії", "Pulls in pickups near the army's edge"],
	"M_ARC_FENCE": ["Дуговий паркан", "Arc Fence"],
	"M_ARC_FENCE_DESC": ["Стіна блискавок приголомшує загони", "A lightning wall that stuns squads"],
	"M_AEGIS": ["Егіда", "Aegis"],
	"M_AEGIS_DESC": ["Купол поглинає удари пасток", "A dome that absorbs hazard hits"],
	"M_SENTINEL": ["Вартовий мех", "Sentinel"],
	"M_SENTINEL_DESC": ["Крокує вперед і тримає загін", "Walks ahead and pins a squad"],
	"M_GRAVITY": ["Гравітаційний вир", "Gravity Well"],
	"M_GRAVITY_DESC": ["Стягує загін у купу й приземлює летунів", "Clumps a squad and grounds flyers"],
	"M_TUNER": ["Камертон", "Gate Tuner"],
	"M_TUNER_DESC": ["Підкручує число воріт попереду", "Tunes up the gate ahead"],
	"M_STARFALL": ["Зорепад", "Starfall Array"],
	"M_STARFALL_DESC": ["Орбітальний удар туди, куди веде герой", "An orbital strike where the hero leads"],
	"M_CHRONO": ["Хронодзвін", "Chrono Bell"],
	"M_CHRONO_DESC": ["Сповільнює час біля воріт", "Slows time at the gate rows"],
	"M_PHOENIX": ["Багаття фенікса", "Phoenix Pyre"],
	"M_PHOENIX_DESC": ["Полеглі повстають із полум’я", "The fallen rise from the flames"],
	"M_ECHO": ["Ехо-реактор", "Echo Reactor"],
	"M_ECHO_DESC": ["Повторює ефект добрих воріт", "Echoes a good gate"],
	# Rarities, families, verbs, statuses
	"RAR_COMMON": ["Звичайна", "Common"],
	"RAR_RARE": ["Рідкісна", "Rare"],
	"RAR_EPIC": ["Епічна", "Epic"],
	"RAR_LEGENDARY": ["Легендарна", "Legendary"],
	"RAR_MYTHIC": ["Міфічна", "Mythic"],
	"FAM_KINETIC": ["Кінетика", "Kinetic"],
	"FAM_VOLT": ["Вольт", "Volt"],
	"FAM_FROST": ["Мороз", "Frost"],
	"FAM_PLASMA": ["Плазма", "Plasma"],
	"FAM_TECH": ["Техно", "Tech"],
	"FAM_RUNE": ["Руна", "Rune"],
	"FAM_RIFT": ["Розлом", "Rift"],
	"VERB_LANE": ["Смуга", "Lane"],
	"VERB_LANE_DESC": ["Стріляє вздовж смуги героя", "Fires down the hero's lane"],
	"VERB_PAINT": ["Ціль", "Paint"],
	"VERB_PAINT_DESC": ["Б’є туди, куди влучив герой", "Hits what the hero hit"],
	"VERB_PLACE": ["Ціль: точка", "Target: point"],
	"VERB_PLACE_DESC": ["Б’є в точку попереду героя", "Strikes a spot ahead of the hero"],
	"VERB_RULE": ["Правило", "Rule"],
	"VERB_RULE_DESC": ["Змінює ворота, пастки чи бій", "Changes gates, hazards or clashes"],
	"ST_STAGGER": ["Відкидання", "Stagger"],
	"ST_JOLT": ["Розряд", "Jolt"],
	"ST_CHILL": ["Холод", "Chill"],
	"ST_FREEZE": ["Заморожено", "Frozen"],
	"ST_BURN": ["Опік", "Burn"],
	"ST_MARK": ["Мітка", "Mark"],
	"ST_SEAL": ["Печать", "Seal"],
	# Talents I/II (family templates; all 4 options of the 4 Meta-1 families ship)
	"TAL_TEMPERED": ["Загартування", "Tempered"],
	"TAL_TEMPERED_DESC": ["+15% шкоди", "+15% damage"],
	"TAL_LONG_BARREL": ["Довгий ствол", "Long Barrel"],
	"TAL_LONG_BARREL_DESC": ["+20% дальності", "+20% range"],
	"TAL_PIERCING": ["Наскрізні", "Piercing"],
	"TAL_PIERCING_DESC": ["+1 ціль на постріл", "+1 pierce"],
	"TAL_CONCUSSIVE": ["Контузія", "Concussive"],
	"TAL_CONCUSSIVE_DESC": ["Відкидання ×2", "Stagger push ×2"],
	"TAL_CAPACITOR": ["Конденсатор", "Capacitor"],
	"TAL_CAPACITOR_DESC": ["+1 стрибок дуги", "+1 chain jump"],
	"TAL_HAIR_TRIGGER": ["Чутливий спуск", "Hair Trigger"],
	"TAL_HAIR_TRIGGER_DESC": ["+20% швидкості стрільби", "+20% fire rate"],
	"TAL_LINGERING_CHARGE": ["Залишковий заряд", "Lingering Charge"],
	"TAL_LINGERING_CHARGE_DESC": ["Розряд триває на 1 с довше", "Jolt lasts 1 s longer"],
	"TAL_ARC_REACH": ["Довга дуга", "Arc Reach"],
	"TAL_ARC_REACH_DESC": ["Дуга стрибає на 1 крок далі", "Arcs jump 1 u further"],
	"TAL_DEEP_COLD": ["Глибокий холод", "Deep Cold"],
	"TAL_DEEP_COLD_DESC": ["Холод сповільнює ще на 5% за заряд", "Chill slows 5% more per stack"],
	"TAL_WIDE_SPRAY": ["Широкий струмінь", "Wide Spray"],
	"TAL_WIDE_SPRAY_DESC": ["+15% площі", "+15% area"],
	"TAL_HARD_FREEZE": ["Міцний лід", "Hard Freeze"],
	"TAL_HARD_FREEZE_DESC": ["Заморожування +0,5 с", "Freeze +0.5 s"],
	"TAL_BRITTLE": ["Крихкість", "Brittle"],
	"TAL_BRITTLE_DESC": ["Заморожені отримують +25% від кінетики", "Frozen squads take +25% from Kinetic"],
	"TAL_HOT_CORE": ["Гаряче ядро", "Hot Core"],
	"TAL_HOT_CORE_DESC": ["Опік палить швидше", "Burn burns faster"],
	"TAL_WIDE_BLOOM": ["Широкий спалах", "Wide Bloom"],
	"TAL_WIDE_BLOOM_DESC": ["+15% радіуса сплеску", "+15% splash radius"],
	"TAL_WILDFIRE": ["Пожежа", "Wildfire"],
	"TAL_WILDFIRE_DESC": ["Опік перескакує ще на 1 загін", "Burn jumps to 1 more squad"],
	"TAL_FISSION": ["Поділ", "Fission"],
	"TAL_FISSION_DESC": ["+1 уламок або відскок", "+1 split or bounce"],
	"TAL_TWIN_FEED": ["Подвійна подача", "Twin Feed"],
	"TAL_TWIN_FEED_DESC": ["+1 ракета або дрон", "+1 rocket or drone"],
	"TAL_LONG_LINK": ["Далекий зв’язок", "Long Link"],
	"TAL_LONG_LINK_DESC": ["+20% дальності", "+20% range"],
	"TAL_PAINT_TARGET": ["Позначка цілі", "Paint Target"],
	"TAL_PAINT_TARGET_DESC": ["Мітка +10%", "Mark +10%"],
	"TAL_SMART_FUSE": ["Розумний підрив", "Smart Fuse"],
	"TAL_SMART_FUSE_DESC": ["Наводиться і на нерозкритих фантомів", "Homing may target unrevealed Phantoms"],
	"TAL_RESONANCE": ["Резонанс", "Resonance"],
	"TAL_RESONANCE_DESC": ["+20% до головного ефекту", "+20% primary effect"],
	"TAL_WIDE_FIELD": ["Широке поле", "Wide Field"],
	"TAL_WIDE_FIELD_DESC": ["+15% радіуса", "+15% radius"],
	"TAL_PROSPECTOR": ["Старатель", "Prospector"],
	"TAL_PROSPECTOR_DESC": ["Печать заряджає ульту", "Seal also charges the ult"],
	"TAL_ECHO_STONE": ["Відлуння каменю", "Echo Stone"],
	"TAL_ECHO_STONE_DESC": ["Ефект триває на 1 с довше", "Effect lingers 1 s longer"],
	# Ascension forms (Lv8; Meta-1 shows the look, Epic+ default branch A)
	"ASC_WASP_DRONE": ["Дрон-оса", "Wasp Drone"],
	"ASC_STORM_BALLISTA": ["Штормова балиста", "Storm Ballista"],
	"ASC_SUN_CANNON": ["Сонячна гармата", "Sun Cannon"],
	"ASC_HUNTER_POD": ["Мисливська ракетниця", "Hunter Pod"],
	"ASC_TITAN_MORTAR": ["Титанова мортира", "Titan Mortar"],
	"ASC_VULCAN_DRUM": ["Барабан Вулкана", "Vulcan Drum"],
	"ASC_SPECTRAL_LANCE": ["Спектральний спис", "Spectral Lance"],
	"ASC_BREACHER": ["Проломник", "Breacher"],
	"ASC_SPLITTER": ["Розщеплювач", "Splitter"],
	"ASC_LENS_OF_RUIN": ["Лінза руїни", "Lens of Ruin"],
	"ASC_RAINBOW_PRISM": ["Райдужна призма", "Rainbow Prism"],
	# Beats, ranks, crates, gates
	"BEAT_TALENT1": ["Талант I", "Talent I"],
	"BEAT_TALENT2": ["Талант II", "Talent II"],
	"BEAT_TALENT3": ["Талант III", "Talent III"],
	"BEAT_LEAD": ["Лідер", "Lead"],
	"BEAT_ASCENSION": ["Піднесення", "Ascension"],
	"BEAT_APEX": ["Апогей", "Apex"],
	"BEAT_PRESTIGE": ["Престиж", "Prestige"],
	"BEAT_MASTERED": ["Майстерність", "Mastered"],
	"MILESTONE": ["до %s · %s: %d рів.", "%s · %s in %d lv"],
	"RANK_UP": ["Ранг %s!", "Rank %s!"],
	"GATE_RANK": ["Ранг", "Rank"],
	"CRATE_NEW": ["НОВА", "NEW"],
	"CRATE_BONUS": ["Бонус!", "Bonus!"],
	"CRATE_RANK": ["→ %s %s", "→ %s %s"],
	"CRATE_OVERFLOW": ["+%d%% %s", "+%d%% %s"],
	"CRATE_FAMILY": ["%s %d/3", "%s %d/3"],
	"NEW_MACHINE": ["Нова машина!", "New machine!"],
	# Arsenal screens
	"TAB_SHOP": ["Магазин", "Shop"],
	"TAB_ARSENAL": ["Арсенал", "Arsenal"],
	"TAB_PLAY": ["ГРА", "PLAY"],
	"TAB_HEROES": ["Герої", "Heroes"],
	"TAB_BARRACKS": ["Казарми", "Barracks"],
	"TAB_LOCKED": ["Рівень %d", "Level %d"],
	"SUB_MACHINES": ["Машини", "Machines"],
	"SUB_DECK": ["Колода", "Deck"],
	"FILTER_ALL": ["Усі", "All"],
	"FILTER_OWNED": ["Мої", "Owned"],
	"FILTER_UPGRADABLE": ["Можна покращити", "Upgradable"],
	"LV": ["Рів. %d", "Lv %d"],
	"LV_MAX": ["Макс.", "Max"],
	"UPGRADE": ["Покращити", "Upgrade"],
	"CONFIRM_COST": ["Підтвердити · %s", "Confirm · %s"],
	"USES_WILD": ["диких креслень: %d", "wild blueprints: %d"],
	"NEED_BP": ["Потрібно креслень: %d", "Blueprints needed: %d"],
	"NEED_COINS": ["Бракує монет", "Not enough coins"],
	"LOCKED_WORLD": ["Світ %d, рівень %d", "World %d, level %d"],
	"LOCKED_SOON": ["Скоро", "Coming soon"],
	"FOCUS": ["Фокус", "Focus"],
	"FOCUS_ETA": ["%s %d/%d · ≈%d перемоги", "%s %d/%d · ≈%d wins"],
	"LEAD": ["Лідер", "Lead"],
	"LEAD_DESC": ["Виходить на бій з самого старту", "Fielded from the start of the run"],
	"DECK": ["Колода", "Deck"],
	"AUTO_DECK": ["Авто-колода", "Auto-deck"],
	"DECK_HINT": ["Колода вирішує, що в скринях", "Your deck decides what crates hold"],
	"BEST_UPGRADE": ["Найкраще покращення", "Best upgrade"],
	"TALENT_PICK": ["Обери талант", "Pick a talent"],
	"TALENT_RESPEC": ["Змінити безкоштовно", "Change for free"],
	"ASCENSION": ["Піднесення", "Ascension"],
	"STAT_DAMAGE": ["Шкода", "Damage"],
	"STAT_RATE": ["Постріли/с", "Shots/s"],
	"STAT_RANGE": ["Дальність", "Range"],
	"STAT_PIERCE": ["Пробиття", "Pierce"],
	"STAT_RADIUS": ["Радіус", "Radius"],
	"STAT_DPS": ["Шкода/с", "Damage/s"],
	"STAT_VOLLEY": ["Ракет у залпі", "Rockets per volley"],
	"STAT_CHARGE": ["Заряд", "Charge"],
	"STAT_AMP": ["Підсилення", "Amp"],
	"FLAG_FLYING": ["Б’є летунів", "Hits flyers"],
	"FLAG_BEAM": ["Ігнорує щити", "Ignores shields"],
	"FLAG_GROUND": ["Лише наземні", "Ground only"],
	# Heroes and Barracks
	"HERO_LEVEL": ["Рівень героя %d", "Hero level %d"],
	"HERO_CAP": ["Макс. у цьому світі: %d", "Max in this world: %d"],
	"HERO_DMG": ["+%d%% шкоди", "+%d%% damage"],
	"HERO_HP": ["+%d%% стійкості", "+%d%% toughness"],
	"ULT_RANK": ["Ульта: ранг %s", "Ult: rank %s"],
	"BAR_RECRUITS": ["Новобранці", "Recruits"],
	"BAR_RECRUITS_DESC": ["+%d до кожної групи рекрутів", "+%d soldiers per recruit group"],
	"BAR_RESERVES": ["Резерв", "Reserves"],
	"BAR_RESERVES_DESC": ["+%d до армії біля фортеці", "+%d soldiers join at the siege"],
	"BAR_SCRAPE": ["Обережність", "Scrape Guard"],
	"BAR_SCRAPE_DESC": ["Пастка щадить перших: %d", "Each hazard spares the first %d soldiers"],
	"BAR_DRILL": ["Муштра", "Drill"],
	"BAR_DRILL_DESC": ["Загони, у які влучив герой, втрачають у бою +%d%%", "Squads your hero hits lose %d%% more in the clash"],
	"BAR_VOLLEYS": ["Залпи", "Volleys"],
	"BAR_VOLLEYS_DESC": ["+%d%% шкоди залпів армії", "+%d%% army volley damage"],
	"BAR_CAP": ["Межа світу: %d", "World cap: %d"],
	# Currencies and Caches
	"CUR_COINS": ["Монети", "Coins"],
	"CUR_GEMS": ["Самоцвіти", "Gems"],
	"CUR_CROWNS": ["Корони", "Crowns"],
	"CUR_BP": ["Креслення", "Blueprints"],
	"CUR_WILD": ["Дикі креслення", "Wild Blueprints"],
	"CUR_CORE": ["Ядро боса", "Boss Core"],
	"CACHE_STONE": ["Кам’яна схованка", "Stone Cache"],
	"CACHE_WORLD": ["Світова схованка", "World Cache"],
	"CACHE_ROYAL": ["Королівська схованка", "Royal Cache"],
	"CACHE_XRAY": ["Прозора схованка", "X-Ray Cache"],
	"TAP_TO_CRACK": ["Торкнись, щоб розбити", "Tap to crack"],
	"OPEN_ALL": ["Відкрити все", "Open all"],
	"OPEN_ON_ALTAR": ["Відкрити на вівтарі", "Open on the Altar"],
	"LATER": ["Пізніше", "Later"],
	"DONE": ["Готово", "Done"],
	"UPGRADE_MACHINE": ["Покращити: %s", "Upgrade %s"],
	"VAULT": ["Сховище", "Vault"],
	"TO_VAULT": ["→ Сховище", "→ Vault"],
	"VAULT_EMPTY": ["Схованок немає. Перемоги приносять кам’яні схованки.", "No caches. Wins bring Stone Caches."],
	"ODDS_TITLE": ["Шанси і гарантії", "Odds and guarantees"],
	"ODDS_PER_CARD": ["Шанс на картку", "Chance per card"],
	"ODDS_BEST": ["Найкраща картка", "Best card"],
	"ODDS_GUARANTEED": ["Остання картка: %s або краща", "Last card: %s or better"],
	"ODDS_STACK": ["Креслень на картці: %s", "Blueprints per card: %s"],
	"ODDS_WILD": ["Дике креслення: 0,5% на картку", "Wild Blueprint: 0.5% per card"],
	"ODDS_FOCUS": ["40% карток рідкості фокуса — йому", "40% of the Focus rarity's cards go to it"],
	"ODDS_DECK": ["Машини колоди ×1,5", "Deck machines ×1.5"],
	"ODDS_DUPES": ["Легендарні — спершу нові машини", "Legendaries go to new machines first"],
	"PITY_EPIC": ["Епічна гарантовано кожні 8 схованок", "An Epic at least every 8 caches"],
	"PITY_LEG": ["Легендарна гарантовано ≤ %d", "Legendary guaranteed in ≤ %d"],
	"PITY_LEG_LOCKED": ["Легендарні з’являються у Світі 3", "Legendaries appear in World 3"],
	# Result and loss
	"RESULT_SURVIVORS": ["Вижило: %d", "Survivors: %d"],
	"CACHE_EARNED": ["%s!", "%s!"],
	"LOSS_PROGRESS": ["Пройдено %d%% мосту", "%d%% of the bridge covered"],
	"LOSS_PAYOUT": ["Здобуто: %d", "Earned: %d"],
	"LOSS_CHARGE": ["Схованка %d/3", "Cache %d/3"],
	"ASSIST_CHIP": ["Підкріплення +%d%%", "Reinforcements +%d%%"],
	"ASSIST_DESC": ["+%d до армії і +%d%% шкоди до перемоги", "+%d soldiers and +%d%% damage until you win"],
	"ARSENAL_BTN": ["Арсенал", "Arsenal"],
	"MIGRATION_CARD": ["Твої покращення переїхали в Казарми й Героїв", "Your upgrades moved to Barracks and Heroes"],
	# Unlock lines (UnlockQueue)
	"UNL_ARSENAL": ["Покращ машину за монети", "Upgrade a machine with coins"],
	"UNL_HEROES": ["Обери, хто веде армію", "Choose who leads the army"],
	"UNL_PAIRS": ["Дві скрині — бери одну", "Two crates — take one"],
	"UNL_STONE_CACHE": ["Схованка: креслення для твоїх машин", "A cache: blueprints for your machines"],
	"UNL_ALTAR": ["Розбий схованку героєм", "Crack the cache with your hero"],
	"UNL_DECK": ["Колода вирішує, що в скринях", "Your deck decides what crates hold"],
	"UNL_RANK_GATES": ["Ворота рангу посилюють машину", "Rank gates power up a machine"],
	"UNL_BARRACKS": ["Казарми: армія, що росте від твоїх рішень", "Barracks: an army that grows from your choices"],
	"UNL_TALENTS": ["Талант змінює, як стріляє машина", "A talent changes how a machine fires"],
	"UNL_DRAG": ["Тягни, щоб вести армію", "Drag to lead the army"],
	"UNL_HAVEN": ["Відбудуй світ за корони", "Rebuild the world with crowns"],
	# Settings
	"SET_FAST_CEREMONIES": ["Швидкі церемонії", "Fast ceremonies"],
	"SET_QUICK_REVEAL": ["Швидке відкриття", "Quick reveal"],
	"SET_CACHES_TO_VAULT": ["Схованки в сховище", "Caches to the Vault"],
	"SET_REDUCE_MOTION": ["Менше руху", "Reduce motion"],
	"SET_REINFORCEMENTS": ["Допомога після поразок", "Help after defeats"],
	# ---------------------------------------------------------------- Hub (WS4)
	"WORLD_N": ["Світ %d", "World %d"],
	"WORLD_REEF": ["Кораловий риф", "Coral Reef"],
	"WORLD_MYSTIC": ["Рунічний ліс", "Rune Forest"],
	"WORLD_VOLCANO": ["Магмові копальні", "Magma Mines"],
	"WORLD_ICE": ["Крижані вершини", "Frost Peaks"],
	"WORLD_SKY": ["Небесна гавань", "Sky Harbour"],
	"WORLD_RIFT": ["Серце Розлому", "Rift Heart"],
	"PLAY": ["Грати", "Play"],
	"BOSS": ["Бос", "Boss"],
	"BOSS_LEVEL": ["Фортеця боса", "Boss fortress"],
	"WORLD_CACHE_HINT": ["Бос світу береже світову схованку", "The world boss guards a World Cache"],
	"NEW_CRATE_AT": ["Нова машина: %s", "New machine: %s"],
	"OWNED_N": ["Машини %d/%d", "Machines %d/%d"],
	"IN_DECK": ["У колоді", "In deck"],
	"DECK_EMPTY_SLOT": ["Порожньо", "Empty"],
	"DECK_TAP_ADD": ["Торкнись машини, щоб додати її до колоди", "Tap a machine to add it to the deck"],
	"DECK_FULL": ["Колода повна: прибери машину", "The deck is full: remove a machine"],
	"DECK_SLOT_LEAD": ["Слот лідера", "Lead slot"],
	"LEAD_AT": ["Лідер з рів. %d", "Lead from Lv %d"],
	"DECK_AUTO_INFO": ["Колода збирається сама до рівня %d", "The deck builds itself until level %d"],
	"REMOVE": ["Прибрати", "Remove"],
	"ADD": ["Додати", "Add"],
	"TALENT_LOCKED": ["Відкриється на рів. %d", "Unlocks at Lv %d"],
	"TALENT_CHOSEN": ["Обрано", "Chosen"],
	"TALENT_PICK_BTN": ["Обрати", "Pick"],
	"SET_FOCUS": ["Зробити фокусом", "Make it the Focus"],
	"FOCUS_ON": ["Фокус схованок", "Cache Focus"],
	"FOCUS_DESC": ["40% карток цієї рідкості в схованках дістанеться їй", "40% of this rarity's Cache cards go to it"],
	"STATS": ["Характеристики", "Stats"],
	"BEATS": ["Віхи машини", "Machine milestones"],
	"UPGRADE_TO": ["Покращити до рів. %d", "Upgrade to Lv %d"],
	"NOTHING_TO_UPGRADE": ["Збирай монети й креслення в забігах", "Earn coins and blueprints in runs"],
	"STAT_SPLASH": ["Сплеск", "Splash"],
	"STAT_BOLTS": ["Болтів", "Bolts"],
	"STAT_DRONES": ["Дронів", "Drones"],
	"STAT_CHAIN": ["Стрибків", "Jumps"],
	"STAT_STATUS": ["Ефект", "Effect"],
	"FAMILY": ["Родина", "Family"],
	"RARITY": ["Рідкість", "Rarity"],
	"HERO_SELECT": ["Обрати героя", "Select hero"],
	"HERO_SELECTED": ["Веде армію", "Leads the army"],
	"HERO_LOCKED": ["Відкриється після рівня %d", "Unlocks after level %d"],
	"HERO_SOON": ["Третій герой — після боса Світу 3", "The third hero joins after the World 3 boss"],
	"LEVEL_UP": ["Підвищити", "Level up"],
	"HERO_FREE_LEVEL": ["Перший рівень — у подарунок", "The first level is on us"],
	"HERO_MAX_WORLD": ["Межа цього світу. Пройди боса, щоб рости далі", "This world's cap. Beat the boss to grow further"],
	"MS_ULT": ["Ульта %s", "Ult %s"],
	"MS_AWAKEN": ["Пробудження %s", "Awakening %s"],
	"ULT_RATE": ["+%d%% заряду ульти", "+%d%% ult charge"],
	"ARMY": ["Армія", "Army"],
	"BAR_ALL": ["Покращити все", "Upgrade all"],
	"BAR_NEXT": ["Далі: %s", "Next: %s"],
	"BAR_LOCKED_INFO": ["Казарми відкриваються після рівня %d", "Barracks open after level %d"],
	"SHOP_SOON": ["Крамниця відкриється згодом", "The shop opens later"],
	"SHOP_PROMISE": ["Без таймерів, без енергії, без платних випадкових скринь", "No timers, no energy, no paid random packs"],
	"NO_RANDOM": ["Без випадковостей: усе, що бачиш, — твоє", "No randomness: what you see is what you get"],
	"RESTORE": ["Відновити покупки", "Restore purchases"],
	"ODDS": ["Шанси", "Odds"],
	"OPEN": ["Відкрити", "Open"],
	"VAULT_COUNT": ["Схованок: %d", "Caches: %d"],
	"VAULT_DESC": ["Світові схованки чекають на вівтар", "World Caches wait for the Altar"],
	"ODDS_POOL": ["Для машин, які ти вже можеш знайти", "For the machines you can find now"],
	"ODDS_PITY_BAR": ["До гарантованої легендарної", "To a guaranteed Legendary"],
	"ODDS_SLOTS": ["Карток: %d", "Cards: %d"],
	"ODDS_COINS": ["+ монети", "+ coins"],
	"REVEAL_NEW": ["НОВА", "NEW"],
	"REVEAL_GOT": ["Здобуто", "You got"],
	"UNLOCK_TITLE": ["Відкрито!", "Unlocked!"],
	"VERSION": ["Версія %s", "Version %s"],
	"TELEMETRY_SAVED": ["Телеметрію збережено", "Telemetry exported"],
	"SET_GAMEPLAY": ["Гра", "Gameplay"],
	"SET_AUDIO": ["Звук і екран", "Sound and screen"],
	"RANK_LABEL": ["Ранг %s", "Rank %s"],
	"SOON": ["Скоро", "Soon"],
	"ARSENAL_RATING": ["Рейтинг арсеналу", "Arsenal rating"],
	"PITY_SHORT": ["Легендарна ≤ %d", "Legendary ≤ %d"],
	"COINS_SHORT": ["%s монет", "%s coins"],
	"FREE": ["Безкоштовно", "Free"],
	# Third hero (WS2b)
	"HERO_SEER": ["Провидиця", "Seer"],
	"HERO_SEER_DESC": ["Рись-містик: подвійні сфери й погляд крізь таємні брами", "Lynx mystic: twin orbs and sight through hidden gates"],
	"ULT_RIFT": ["Зоряний розлом!", "Star Rift!"],
	# Altar and result flow (WS5)
	"TAP_TO_OPEN": ["Торкнись, щоб відкрити", "Tap to open"],
	"TAP_CONTINUE": ["Торкнись, щоб продовжити", "Tap to continue"],
	"RF_TO_VAULT": ["У сховище", "To the Vault"],
	"RF_IN_VAULT": ["Чекає у сховищі", "Waiting in the Vault"],
	"RF_EARNED": ["Здобуто", "Earned"],
	"BAR_RECRUITS_DESC_F": ["+%s до кожної групи рекрутів (у середньому)", "+%s soldiers per recruit group (on average)"],
	# UI v2 (final pass)
	"HOME_EVENTS": ["Події", "Events"],
	"HOME_MAIL": ["Пошта", "Mail"],
	"HOME_QUESTS": ["Завдання", "Quests"],
	"HOME_SOON": ["%s — скоро", "%s: coming soon"],
	"NAV_PLAY": ["Грати", "Play"],
	"TALENTS": ["Таланти", "Talents"],
	"TAB_BEATS": ["Віхи", "Milestones"],
	"FOUND_AT": ["Де знайти: %s", "Found at: %s"],
	"LV_NOW": ["Рів. %d → %d", "Lv %d → %d"],
	"BEAT_DONE": ["Отримано", "Reached"],
	"BEAT_IN": ["через %d рів.", "in %d lv"],
	"LOSS_CHEER": ["Майже! Наступна спроба буде сильнішою", "So close! The next try will be stronger"],
	"UNLOCK_NAMED": ["Відкрито: %s", "Unlocked: %s"],
	"UNF_ALTAR": ["Вівтар", "Altar"],
	"UNF_STONE_CACHE": ["Схованки", "Caches"],
	"UNF_DECK": ["Колода", "Deck"],
	"UNF_TALENTS": ["Таланти", "Talents"],
	"UNF_PAIRS": ["Подвійні скрині", "Crate pairs"],
	"UNF_RANK_GATES": ["Ворота рангу", "Rank gates"],
	"UNF_DRAG": ["Керування армією", "Army control"],
	"UNF_TITAN": ["Новий герой", "New hero"],
	"UNF_MIGRATION": ["Оновлення", "Update"],
	"BACK_TO_QUIT": ["Натисни ще раз, щоб вийти", "Press back again to quit"],
	"BUY_ALL_CONFIRM": ["Підтвердити · %s", "Confirm · %s"],
	"DECK_REMOVED": ["%s — прибрано з колоди", "%s removed from the deck"],
	"UNDO": ["Повернути", "Undo"],
	"FOCUS_DEFAULT": ["За замовчуванням — Лідер", "Default: the Lead"],
	"BEAT_NEXT": ["Ще %d рів. до віхи «%s»", "%d lv to the «%s» milestone"],
	"OWNED_COUNT": ["Зібрано %d/%d", "Collected %d/%d"],
	"SHOP_SOON_ROW": ["Самоцвіти, образи, пропуск — скоро", "Gems, looks and the pass: coming soon"],
	"WILD_SHARE": ["дикі +%d", "wild +%d"],
	"TARGET_POINT": ["Ціль: точка", "Target: point"],
}


var lang := "uk"


func _ready() -> void:
	var wanted := Save.language
	for a in OS.get_cmdline_user_args():
		if a.begins_with("--lang="):
			wanted = a.trim_prefix("--lang=")
	if wanted == "":
		wanted = "uk" if OS.get_locale_language() == "uk" else "en"
	set_language(wanted, false)


func set_language(code: String, persist := true) -> void:
	lang = code if code in LANGS else "en"
	TranslationServer.set_locale(lang)
	if persist:
		Save.language = lang
		Save.save_data()
	language_changed.emit()


func next_language() -> String:
	return LANGS[(LANGS.find(lang) + 1) % LANGS.size()]


func t(key: String) -> String:
	if not STRINGS.has(key):
		return key
	var row: Array = STRINGS[key]
	return row[maxi(LANGS.find(lang), 0)]


func f(key: String, args: Array) -> String:
	return t(key) % args


## Ukrainian plural form: `forms` = [one, few, many] ("рівень", "рівні", "рівнів"); English uses
## one / many. Returns the bare word (callers add the number).
func plural(n: int, forms: Array) -> String:
	var a := absi(n)
	if lang != "uk":
		return str(forms[0]) if a == 1 else str(forms[forms.size() - 1])
	if a % 10 == 1 and a % 100 != 11:
		return str(forms[0])
	if a % 10 in [2, 3, 4] and not (a % 100 in [12, 13, 14]):
		return str(forms[1])
	return str(forms[2])


## Integer with thousands separated by a no-break space in Ukrainian ("12 400"; Rubik has no thin space) and a comma in
## English ("12,400").
func num(n: int) -> String:
	var s := str(absi(n))
	var sep := "\u00a0" if lang == "uk" else ","
	var out := ""
	while s.length() > 3:
		out = sep + s.substr(s.length() - 3) + out
		s = s.substr(0, s.length() - 3)
	return ("-" if n < 0 else "") + s + out
