class_name CeremonyData
extends RefCounted
## Heroes & Champions data (heroes_design.md §12.2, WS-A). The block below is generated by
## tools/gen_heroes_data.py from tools/data/heroes_consts.json + heroes_roster.json; hand-written
## helpers go after it. Nothing in the shipped game reads this class before EconData.HEROES_PHASE >= 1.

# <GENERATED by tools/gen_heroes_data.py — edit the json / the generator, never this block>
## Sources: heroes_consts.json sha256 6993c4c2e6e4fd89, heroes_roster.json sha256 abf5d495210842eb.

# ---- ceremony lengths in seconds (§9.4; also read by heroes_sim.py)
## x1 = [Quartz, Sapphire]; walkout keys are gem indices "2" / "3" / "4" (E / L / M),
## played after `prologue`; batch_crack = ×10 facet cracks; clevel = Champion Level.
const CEREMONY: Dictionary = {"prologue": 0.6, "x1": [1.2, 1.8], "walkout": {"2": 2.6, "3": 3.6, "4": 5.0}, "short_walkout": 1.2, "x10_frame": 1.2, "batch_crack": 0.5, "seal_pick_new": 1.8, "seal_pick_owned": 1.2, "chest_inline": 1.6, "chest_inline_dup": 1.2, "cameo": 1.5, "cameo_next": 1.0, "vault_batch": 0.3, "facet": 0.35, "full_facets": 1.6, "recut": 3.0, "skill": 0.6, "form": 1.6, "awaken": 3.0, "hero_level": 0.35, "clevel": 0.35, "craft": 1.2, "temper": 0.35, "temper_tier": 1.2, "temper_beat": 1.2, "chronicle": 0.35, "migration_summary": 3.0}
## Fast ceremonies / Quick reveal lengths (keys absent = unchanged). (heroes_design.md §9.4)
const CEREMONY_FAST: Dictionary = {"x1": [1.2, 1.2], "short_walkout": 1.2, "seal_pick_new": 1.2, "seal_pick_owned": 1.2, "chest_inline": 1.6, "chest_inline_dup": 1.2, "cameo": 1.0, "cameo_next": 1.0, "full_facets": 0.8, "recut": 1.5, "skill": 0.3, "form": 0.8, "awaken": 1.5, "craft": 0.6, "temper_tier": 0.6, "temper_beat": 0.6, "team_ready": 0.2}
## Reduce Motion lengths (keys absent = no motion at all / unchanged). (heroes_design.md §9.4)
const CEREMONY_REDUCED: Dictionary = {"x1": [0.2, 0.2], "walkout_static_max": 1.0, "facet": 0.2, "full_facets": 0.5, "recut": 0.6, "skill": 0.2, "form": 0.5, "awaken": 0.6, "craft": 0.35, "temper_tier": 0.35, "temper_beat": 0.35}
## (heroes_design.md §9.4)
const TEAM_READY: float = 0.4
## Walkouts are skippable from this many seconds. (heroes_design.md §9.4 / §7.1)
const SKIP_FROM: float = 0.5

## Where every generated constant comes from: consts:<path> = tools/data/heroes_consts.json,
## roster:<path> = tools/data/heroes_roster.json (both checked by scripts/dev/test_heroes.gd),
## doc:<§> = heroes_design.md, derived:<rule> = computed by the generator from the json.
const SOURCE_KEYS: Dictionary[String, String] = {
	"CEREMONY": "consts:ceremony",
	"CEREMONY_FAST": "doc:§9.4",
	"CEREMONY_REDUCED": "doc:§9.4",
	"TEAM_READY": "doc:§9.4",
	"SKIP_FROM": "doc:§9.4 / §7.1",
}
# </GENERATED>


# ------------------------------------------------------------------ helpers (hand-written)

## Full length of a NEW hero's summon reveal of `gem` (x1 for Quartz / Sapphire, prologue +
## walkout for Amethyst+), in seconds.
static func reveal_length(gem: String) -> float:
	var g := Ladder.gem_index(gem)
	if g < 2:
		return float((CEREMONY["x1"] as Array)[g])
	return float(CEREMONY["prologue"]) + float((CEREMONY["walkout"] as Dictionary)[str(g)])
