class_name ChampionData
extends RefCounted
## Heroes & Champions data (heroes_design.md §12.2, WS-A). The block below is generated by
## tools/gen_heroes_data.py from tools/data/heroes_consts.json + heroes_roster.json; hand-written
## helpers go after it. Nothing in the shipped game reads this class before EconData.HEROES_PHASE >= 1.

# <GENERATED by tools/gen_heroes_data.py — edit the json / the generator, never this block>
## Sources: heroes_consts.json sha256 652c2fc3bfb2e83f, heroes_roster.json sha256 0cef01ed1dc74e06.

# ---- roster (heroes_design.md §6.0, §4.4; kit = f0 Lv1 Quartz-normalised)
## Collector order 11-22.
const CHAMPION_ORDER: Array[String] = ["mila", "ivo", "borko", "alba", "otto", "taya", "brant", "teo", "olena", "nimb", "dara", "menhir"]
## id -> {no, native, class, element, faction, slot (preferred), kit {hp, action, aura, radius}, action_note,
## aura_note}. Action tier = native gem index + 1, fixed at birth (§2.2).
const CHAMPIONS: Dictionary = {
	"mila": {"no": 11, "native": "C", "class": "healer", "element": "tech", "faction": "dawn", "slot": "left", "kit": {"hp": 30, "action": 3, "aura": 0.12, "radius": 1.3}, "action_note": "soldiers returned per pulse (every 3 s)", "aura_note": "hazard losses -"},  # C healer left
	"ivo": {"no": 12, "native": "C", "class": "guardian", "element": "plasma", "faction": "dawn", "slot": "front", "kit": {"hp": 60, "action": 3, "aura": 0.1, "radius": 1.0}, "action_note": "blocked-barricade damage (Block every 5 s)", "aura_note": "clash losses -"},  # C guardian front
	"borko": {"no": 13, "native": "C", "class": "warrior", "element": "kinetic", "faction": "wildfang", "slot": "front", "kit": {"hp": 48, "action": 3, "aura": 0.1, "radius": 1.1}, "action_note": "Undermine kills (every 5 s)", "aura_note": "squad clash loss +"},  # C warrior front
	"alba": {"no": 14, "native": "R", "class": "ranger", "element": "frost", "faction": "wildfang", "slot": "rear", "kit": {"hp": 26, "action": 1.0, "aura": 0.15, "radius": 1.4}, "action_note": "shot damage (every 1.2 s; x1.5 vs Flying)", "aura_note": "army volleys +"},  # R ranger rear
	"otto": {"no": 15, "native": "R", "class": "guardian", "element": "kinetic", "faction": "stoneheart", "slot": "front", "kit": {"hp": 60, "action": 1, "aura": 0.1, "radius": 1.0}, "action_note": "kills per Block (Block every 5 s)", "aura_note": "clash losses -"},  # R guardian front
	"taya": {"no": 16, "native": "R", "class": "mage", "element": "rune", "faction": "celestial", "slot": "rear", "kit": {"hp": 26, "action": 4, "aura": 0.15, "radius": 1.2}, "action_note": "Spell kills per squad (every 4 s)", "aura_note": "volley status proc x"},  # R mage rear
	"brant": {"no": 17, "native": "E", "class": "warrior", "element": "plasma", "faction": "stoneheart", "slot": "front", "kit": {"hp": 48, "action": 3, "aura": 0.1, "radius": 1.1}, "action_note": "leap kills (every 5 s)", "aura_note": "squad clash loss +"},  # E warrior front
	"teo": {"no": 18, "native": "E", "class": "ranger", "element": "tech", "faction": "celestial", "slot": "rear", "kit": {"hp": 26, "action": 1.0, "aura": 0.15, "radius": 1.4}, "action_note": "shot damage (every 1.2 s, homing)", "aura_note": "army volleys +"},  # E ranger rear
	"olena": {"no": 19, "native": "E", "class": "healer", "element": "frost", "faction": "wildfang", "slot": "right", "kit": {"hp": 30, "action": 3, "aura": 0.12, "radius": 1.3}, "action_note": "soldiers returned per pulse (every 3 s)", "aura_note": "hazard losses -"},  # E healer right
	"nimb": {"no": 20, "native": "L", "class": "guardian", "element": "volt", "faction": "celestial", "slot": "front", "kit": {"hp": 60, "action": 2, "aura": 0.1, "radius": 1.0}, "action_note": "Lightning Rod damage x3 targets (per Block)", "aura_note": "clash losses -"},  # L guardian front
	"dara": {"no": 21, "native": "L", "class": "ranger", "element": "volt", "faction": "dawn", "slot": "rear", "kit": {"hp": 26, "action": 1.0, "aura": 0.15, "radius": 1.4}, "action_note": "shot damage (every 1.2 s; harpoon every 3rd)", "aura_note": "army volleys +"},  # L ranger rear
	"menhir": {"no": 22, "native": "L", "class": "mage", "element": "rune", "faction": "stoneheart", "slot": "right", "kit": {"hp": 26, "action": 4, "aura": 0.15, "radius": 1.2}, "action_note": "rune-strike kills per squad (every 4 s)", "aura_note": "volley status proc x"},  # L mage right
}

# ---- aura and clash (§4.2)
## Fixed aura share per slot, the same in Run and LevelSim (critique X09).
const AURA_SHARE: Dictionary[String, float] = {"front": 0.35, "left": 0.3, "right": 0.3, "rear": 0.25}
const AURA_CAP: float = 0.4
## The front champion in contact accumulates hit x CLASH_SHARE per tick. (heroes_design.md §4.2)
const CLASH_SHARE: float = 0.25
## Multiplier on the clash share with a Guardian hero. (heroes_design.md §4.2)
const CLASH_SHARE_GUARDIAN_HERO: float = 0.5
## Frontier level (after_win) -> champion slots (§4.1).
const SLOTS_AT: Dictionary[String, int] = {"14": 2, "40": 3}

# ---- Champion Level (one shared coin track; §4.1)
const CHAMP_LEVEL_MAX: int = 20
## CHAMP_LEVEL_COST[L - 1] = coins for Champion Level L -> L + 1.
const CHAMP_LEVEL_COST: Array[int] = [40, 110, 210, 320, 450, 590, 740, 910, 1080, 1260, 1460, 1660, 1870, 2100, 2320, 2560, 2800, 3050, 3310]
## Cap = CL_CAP_BASE + CL_CAP_PER_WORLD x world_reached, CHAMP_LEVEL_MAX in Invasion. (heroes_design.md §4.1)
const CL_CAP_BASE: int = 2
## (heroes_design.md §4.1)
const CL_CAP_PER_WORLD: int = 2

# ---- champion budgets (§4.1, §2.3)
const CL_STEP: float = 0.04
const ACTION_TIER_STEP: float = 0.04
const C_RELIC: Array[float] = [0.03, 0.01]
const W_C: float = 0.012
const CHAMP_UPTIME: float = 0.94
const CHAMP_KIT_TOL: float = 0.03

## Where every generated constant comes from: consts:<path> = tools/data/heroes_consts.json,
## roster:<path> = tools/data/heroes_roster.json (both checked by scripts/dev/test_heroes.gd),
## doc:<§> = heroes_design.md, derived:<rule> = computed by the generator from the json.
const SOURCE_KEYS: Dictionary[String, String] = {
	"CHAMPION_ORDER": "roster:champion_order",
	"CHAMPIONS": "roster:champions",
	"AURA_SHARE": "roster:aura_share",
	"AURA_CAP": "consts:team.AURA_CAP",
	"CLASH_SHARE": "doc:§4.2",
	"CLASH_SHARE_GUARDIAN_HERO": "doc:§4.2",
	"SLOTS_AT": "derived:unlocks.champions / unlocks.slot3",
	"CHAMP_LEVEL_MAX": "consts:progress.CHAMP_LEVEL_MAX",
	"CHAMP_LEVEL_COST": "consts:progress.CHAMP_LEVEL_COST",
	"CL_CAP_BASE": "doc:§4.1",
	"CL_CAP_PER_WORLD": "doc:§4.1",
	"CL_STEP": "consts:budgets.CL_STEP",
	"ACTION_TIER_STEP": "consts:budgets.ACTION_TIER_STEP",
	"C_RELIC": "consts:budgets.C_RELIC",
	"W_C": "consts:budgets.W_C",
	"CHAMP_UPTIME": "consts:budgets.CHAMP_UPTIME",
	"CHAMP_KIT_TOL": "consts:budgets.CHAMP_KIT_TOL",
}
# </GENERATED>


# ------------------------------------------------------------------ helpers (hand-written)

## Action tier I..IV = native gem index + 1, fixed at birth (a recut keeps its tier; §2.2).
static func action_tier(id: String) -> int:
	return Ladder.gem_index(str(CHAMPIONS[id]["native"])) + 1


## Champion slots open at frontier `level` (0 before the champions unlock; §4.1).
static func slots_at(level: int) -> int:
	var n := 0
	for k: String in SLOTS_AT:
		if level >= int(k):
			n = maxi(n, SLOTS_AT[k])
	return n


## Champion Level cap: CL_CAP_BASE + CL_CAP_PER_WORLD x world_reached, the max in Invasion.
static func level_cap(world_reached: int, invasion: bool) -> int:
	if invasion:
		return CHAMP_LEVEL_MAX
	return mini(CHAMP_LEVEL_MAX, CL_CAP_BASE + CL_CAP_PER_WORLD * world_reached)


## Coins for Champion Level `lvl` -> `lvl` + 1 (0 at the max).
static func level_cost(lvl: int) -> int:
	return CHAMP_LEVEL_COST[lvl - 1] if lvl >= 1 and lvl < CHAMP_LEVEL_MAX else 0
