class_name HeroData
extends RefCounted
## Heroes & Champions data (heroes_design.md §12.2, WS-A). The block below is generated by
## tools/gen_heroes_data.py from tools/data/heroes_consts.json + heroes_roster.json; hand-written
## helpers go after it. Nothing in the shipped game reads this class before EconData.HEROES_PHASE >= 1.

# <GENERATED by tools/gen_heroes_data.py — edit the json / the generator, never this block>
## Sources: heroes_consts.json sha256 979204e5a8f02583, heroes_roster.json sha256 c0fdfcfab182e408.

# ---- roster (heroes_design.md §6.0; kit = Lv1 rank-1 Quartz-normalised, eff = kit x Ladder.NATIVE_MULT[native])
## Collector numbers 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 26, 27 (heroes and champions share one number line).
const HERO_ORDER: Array[String] = ["titan", "arin", "bolt", "eira", "seer", "iskar", "vesta", "vartan", "lumen", "pava", "sirko", "olha"]
## id -> {no, native, class, element, element2 (ult form V), faction, niche, ult (kind id), kit {hp, rate, dmg,
## splash, range, targets, ult_charge}, ult_main {value, note}, ult2 {value, note, rank}, rally {hook, param, base,
## note}}. Notes are designer notes for tools, never UI copy (names and texts are Loc HERO_<ID>*).
const HEROES: Dictionary = {
	"titan": {"no": 1, "native": "C", "class": "guardian", "element": "kinetic", "element2": "", "faction": "stoneheart", "niche": "structures", "ult": "quake", "kit": {"hp": 32, "rate": 1.2, "dmg": 4, "splash": 3, "range": 12, "targets": 1, "ult_charge": 40}, "ult_main": {"value": 12, "note": "kills & breaks per band (4 bands)"}, "ult2": {}, "rally": {"hook": "army_scrape", "param": "", "base": 3.0, "note": "soldiers spared per hazard contact"}},  # C guardian quake
	"arin": {"no": 2, "native": "C", "class": "warrior", "element": "kinetic", "element2": "", "faction": "dawn", "niche": "armored", "ult": "anchor", "kit": {"hp": 26, "rate": 1.6, "dmg": 3, "splash": 2, "range": 11, "targets": 1, "ult_charge": 36}, "ult_main": {"value": 22, "note": "impact kills & breaks"}, "ult2": {}, "rally": {"hook": "army_drill", "param": "", "base": 0.075, "note": "extra clash loss of squads he hit"}},  # C warrior anchor
	"bolt": {"no": 3, "native": "R", "class": "ranger", "element": "volt", "element2": "", "faction": "wildfang", "niche": "flying", "ult": "storm", "kit": {"hp": 14, "rate": 3.6, "dmg": 1, "splash": 0, "range": 15, "targets": 1, "ult_charge": 35}, "ult_main": {"value": 5, "note": "storm kills per tick (12 ticks)"}, "ult2": {}, "rally": {"hook": "machines_element", "param": "volt", "base": 0.03, "note": "Volt machine damage, bucket 2"}},  # R ranger storm
	"eira": {"no": 4, "native": "R", "class": "healer", "element": "frost", "element2": "", "faction": "dawn", "niche": "shielded", "ult": "rime", "kit": {"hp": 20, "rate": 2.0, "dmg": 1, "splash": 0, "range": 14, "targets": 1, "ult_charge": 34}, "ult_main": {"value": 4, "note": "Litany kills per squad"}, "ult2": {}, "rally": {"hook": "champions_hp", "param": "", "base": 0.15, "note": "champion HP x(1+v)"}},  # R healer rime
	"seer": {"no": 5, "native": "E", "class": "mage", "element": "rune", "element2": "", "faction": "wildfang", "niche": "", "ult": "rift", "kit": {"hp": 18, "rate": 2.0, "dmg": 1, "splash": 0, "range": 16, "targets": 2, "ult_charge": 38}, "ult_main": {"value": 5, "note": "rift kills per tick (8 ticks)"}, "ult2": {}, "rally": {"hook": "ult_start", "param": "", "base": 0.1, "note": "ult charge at level start"}},  # E mage rift
	"iskar": {"no": 6, "native": "E", "class": "ranger", "element": "volt", "element2": "", "faction": "celestial", "niche": "", "ult": "comet", "kit": {"hp": 13, "rate": 3.2, "dmg": 1, "splash": 0, "range": 16, "targets": 1, "ult_charge": 36}, "ult_main": {"value": 6, "note": "comet kills per tick (6 ticks)"}, "ult2": {}, "rally": {"hook": "machines_verb", "param": "lane", "base": 0.025, "note": "LANE machine damage, bucket 2"}},  # E ranger comet
	"vesta": {"no": 7, "native": "L", "class": "warrior", "element": "plasma", "element2": "", "faction": "dawn", "niche": "", "ult": "sunglaive", "kit": {"hp": 27, "rate": 1.5, "dmg": 3, "splash": 2, "range": 12, "targets": 1, "ult_charge": 38}, "ult_main": {"value": 10, "note": "Sunrise kills & breaks per pulse (4 pulses)"}, "ult2": {"value": 8, "note": "Sunstride slam (form IV)", "rank": 7}, "rally": {"hook": "army_reserves", "param": "", "base": 6.0, "note": "soldiers joining at the siege"}},  # L warrior sunglaive
	"vartan": {"no": 8, "native": "L", "class": "guardian", "element": "tech", "element2": "", "faction": "stoneheart", "niche": "", "ult": "forgewall", "kit": {"hp": 33, "rate": 1.1, "dmg": 4, "splash": 3, "range": 12, "targets": 1, "ult_charge": 42}, "ult_main": {"value": 8, "note": "wall contact kills (wall HP 30 scales the same)"}, "ult2": {"value": 8, "note": "Landslide (form IV)", "rank": 7}, "rally": {"hook": "army_volleys", "param": "", "base": 0.15, "note": "army volley damage x(1+v)"}},  # L guardian forgewall
	"lumen": {"no": 9, "native": "M", "class": "mage", "element": "plasma", "element2": "rune", "faction": "celestial", "niche": "", "ult": "spectrum", "kit": {"hp": 17, "rate": 2.2, "dmg": 1, "splash": 1, "range": 15, "targets": 2, "ult_charge": 42}, "ult_main": {"value": 2, "note": "fan kills & breaks per ray per tick (10 ticks)"}, "ult2": {"value": 4, "note": "Crown Shard hit (form IV)", "rank": 7}, "rally": {"hook": "machines_element", "param": "plasma", "base": 0.03, "note": "Plasma machine damage, bucket 2"}},  # M mage spectrum
	"pava": {"no": 10, "native": "M", "class": "healer", "element": "rune", "element2": "frost", "faction": "wildfang", "niche": "", "ult": "eyes", "kit": {"hp": 21, "rate": 1.9, "dmg": 1, "splash": 0, "range": 14, "targets": 1, "ult_charge": 44}, "ult_main": {"value": 8, "note": "fan base return (+30% of the revive pool)"}, "ult2": {"value": 4, "note": "Eyes Wide kills (form IV)", "rank": 7}, "rally": {"hook": "champions_aura", "param": "", "base": 0.06, "note": "champion aura value x(1+v)"}},  # M healer eyes
	"sirko": {"no": 26, "native": "M", "class": "warrior", "element": "rune", "element2": "tech", "faction": "dawn", "niche": "", "ult": "letter", "kit": {"hp": 25, "rate": 1.7, "dmg": 3, "splash": 2, "range": 11, "targets": 1, "ult_charge": 42}, "ult_main": {"value": 16, "note": "laughter kills & breaks per squad / structure under the scroll"}, "ult2": {"value": 8, "note": "Second Roar kills & breaks (form III)", "rank": 5}, "rally": {"hook": "army_recruits", "param": "", "base": 1.0, "note": "soldiers added to every recruit group"}},  # M warrior letter
	"olha": {"no": 27, "native": "M", "class": "ranger", "element": "plasma", "element2": "kinetic", "faction": "wildfang", "niche": "structures", "ult": "doves", "kit": {"hp": 15, "rate": 3.4, "dmg": 1, "splash": 0, "range": 16, "targets": 1, "ult_charge": 40}, "ult_main": {"value": 18, "note": "breaks per structure / gate the flock reaches (squads under the flight path lose a third + BURN)"}, "ult2": {"value": 8, "note": "Fourth Revenge kills on the biggest squad (form III)", "rank": 5}, "rally": {"hook": "ult_charge", "param": "", "base": 0.05, "note": "ult charge rate x(1+v)"}},  # M ranger doves
}
const STARTERS: Array[String] = ["titan", "bolt", "seer"]
## Heroes owned by a brand-new account.
const START_OWNED: Array[String] = ["bolt"]
## Starter -> the level after which it joins (0 = from the start; Мейра 24, guest at L5).
const STARTER_AT: Dictionary[String, int] = {"titan": 4, "bolt": 0, "seer": 24}

# ---- unlock levels (after_win; §11.1)
const UNLOCK_AT: Dictionary[String, int] = {"champions": 14, "portal": 20, "seer": 24, "skills": 30, "workshop": 32, "slot3": 40}

# ---- PROGRESS (§3.2, §3.3; champions reuse the fragment tables)
## PROGRESS[...] in the design = these constants.
const DUP_FRAGS: Array[int] = [10, 15, 25, 50, 100]
## FACET_FRAGS[g][f] = fragments for facet f -> f + 1 at gem g.
const FACET_FRAGS: Array = [[5, 5, 10, 10, 20], [10, 10, 15, 15, 25], [15, 15, 20, 20, 30], [20, 20, 30, 30, 50], [30, 30, 40, 40, 60]]
## RECUT_FRAGS[g] = fragments for the recut g -> g + 1.
const RECUT_FRAGS: Array[int] = [40, 60, 100, 150]
const RECUT_COINS: Array[int] = [0, 0, 0, 0]
const OVERFLOW_FRAGS_PER_TOME: int = 20
## TOME_COST[r] = Tomes for skill rank r -> r + 1.
const TOME_COST: Array[int] = [0, 2, 3, 5, 8, 12, 16, 20, 25, 30, 40]
const SKILL_COINS: int = 0
const HERO_SYNC_BEHIND: int = 3
const GEAR_SLOT_AT: Dictionary[String, int] = {"weapon": 1, "armour": 4, "charm": 8, "relic": 12}
const CHRONICLE_PRICES: Array[int] = [10, 15, 20, 30, 40]

# ---- hero Feats (§3.6; pay Tomes, never Beacons)
const FEATS: Dictionary = {"F-61": {"counter": "heroes_owned", "tiers": [4, 7, 10], "reward": ["tomes", [2, 4, 8]]}, "F-62": {"counter": "recuts", "tiers": [1, 6, 20], "reward": ["tomes", [2, 4, 8]]}, "F-63": {"counter": "full_cuts", "tiers": [2, 10, 30], "reward": ["tomes", [2, 4, 8]]}, "F-64": {"counter": "champions_owned", "tiers": [4, 8, 12], "reward": ["tomes", [2, 4, 8]]}, "F-65": {"counter": "skill_ranks", "tiers": [10, 40, 100], "reward": ["tomes", [2, 4, 8]]}, "F-66": {"counter": "awakenings", "tiers": [1, 3, 6], "reward": ["tomes", [2, 4, 8]]}, "F-70": {"counter": "champion_level", "tiers": [5, 12, 20], "reward": ["tomes", [2, 4, 8]]}}

# ---- ults and attacks as data (§6.1-6.10, §6.28, §6.29; bot policies §10.4; heroes_tables.py ULTS / ATTACKS)
## Form I = rank 1, Quartz-normalised. kills / breaks / heal / return / wall_hp (and an extra's kills / breaks)
## are x ult power (ladder x Ult Rank x lv_ult); lengths, radii, rates and counts never scale. forms = the deltas
## of forms II-V, null where the native gem caps the ult; ult_numbers(kind, form) merges them onto `base` (a
## Dictionary merges key by key, anything else is replaced). Attack beats merge the same way (attack_numbers).
## `knobs` = the sheet's *(knob)* numbers (test_kit_budget handles), as paths into the dict beside them.
## Ult shape -> how it hits (the closed set every ULTS row uses).
const ULT_SHAPES: Dictionary[String, String] = {
	"timed": "a field around the hero for `duration` s; every `tick` s it hits everything with d in [hero - 0.5, hero + `range`] (the Meta-1 storm / rift; `ahead` places the rift's visual)",
	"waves": "`waves` bands `spacing` u deep, `gap` s apart, from `from` to `to` u ahead of the cast point; each band hits once",
	"drop": "an impact `ahead` u in front (at the hero's x with `at_x`), `radius` u: `pulses` hits `gap` s apart (one when absent)",
	"area": "a band from `from` to `to` u ahead, `width` u wide at the hero's x (null = the full bridge): hits once; its front runs from `from` to `to` in `sweep` s (at once when absent) and it stays `duration` s",
	"beam": "a corridor `width` u wide down the hero's x from `from` to `to` u ahead for `duration` s, hitting every `tick` s",
	"fan": "`rays` rays over `angle` degrees from the hero's x, `length` u long, for `duration` s; each ray hits every `tick` s (a squad takes at most `per_squad_max` rays per tick)",
	"wall": "a barrier `width` u wide, `ahead` u in front, that travels with the army for `duration` s: it absorbs (`absorb`), squads reaching it fight it first (`wall_hp`)",
	"ward": "a window of `duration` s on the army: soldiers lost meanwhile are recorded (x `record`) and at the close min(recorded, `return` + `return_pool` x revive pool) come back",
	"flock": "birds fly over the squads in `waves` waves `gap` s apart to every structure of `targets` within `reach` u ahead: each structure takes `breaks` (an equal share per wave), squads under the flight path `kills`",
}
## Every key an ult base, form delta or part may carry -> its meaning.
const ULT_FIELDS: Dictionary[String, String] = {
	"duration": "s the ult or the part lasts",
	"tick": "s between the hits of a lasting shape",
	"range": "u ahead a timed ult hits",
	"ahead": "u in front of the hero where the shape is placed",
	"from": "u ahead where the shape starts",
	"to": "u ahead where the shape ends",
	"width": "u across the bridge (null = the full bridge)",
	"radius": "u",
	"at_x": "placed at the hero's x",
	"follow": "follows the hero's x live",
	"moves": "travels with the army",
	"sweep": "s for an area's front to run from `from` to `to`",
	"waves": "bands / waves",
	"spacing": "u, band depth",
	"gap": "s between waves or pulses",
	"pulses": "hits of a drop",
	"rays": "rays of a fan",
	"angle": "degrees",
	"length": "u, ray length",
	"per_squad_max": "rays one squad takes per tick at most",
	"reach": "u ahead targets are sought",
	"delay": "s after the cast",
	"at": "when a part fires (ULT_TIMING)",
	"target": "what a part hits (ULT_TARGETS)",
	"targets": "structure kinds a flock seeks",
	"count": "targets / turrets",
	"leap_s": "s the visual leap out and back takes at most (logic x stays under the thumb)",
	"kills": "soldiers removed per squad per hit",
	"breaks": "hp removed per structure per hit",
	"gate_hits": "hero hits on every gate in the shape per hit",
	"neg_gate_hits": "hero hits on every negative gate of the next gate row",
	"fortress": "at the siege the hit lands on the fortress (it takes `breaks`)",
	"flying": "also hits Flying squads",
	"pierce_shield": "ignores the Shielded pool",
	"flying_mult": "damage x on Flying squads",
	"ground": "s a Flying squad hit stays grounded",
	"ground_after": "a Flying squad hit stays grounded until the ult ends + this many s",
	"statuses": "status id (ArsenalData.STATUSES; seal = BRAND) -> stacks per hit (lengths: the status rule's)",
	"stagger_s": "s of STAGGER when the sheet gives it",
	"burn_s": "s of BURN when the sheet gives it",
	"freeze_s": "s of the FREEZE the CHILL stacks end in",
	"paint_s": "s the biggest squad hit stays PAINTED",
	"reveal": "u ahead hidden gates and Phantom squads are revealed (-1 = the whole screen)",
	"mark_phantoms": "the revealed Phantom squads are MARKed",
	"slow": "hazards, turrets, squads and clash losses run at 1 - slow while it lasts",
	"armor_time": "s the army ignores hazards and turrets",
	"hold": "s squads touching the hold area are held (no advance, no clash damage, STAGGERed)",
	"hold_width": "u, width of the hold area",
	"clash_loss": "squads hit lose this much more in clashes",
	"clash_loss_s": "s it lasts (null = their next clash)",
	"strip_s": "s squads caught fight as plain squads (Armored / Shielded off)",
	"silence_s": "s turrets on the path miss every shot",
	"heal": "soldiers the army regains",
	"heal_pool": "share of the revive pool the army regains on top",
	"record": "x on the soldiers a ward records",
	"return": "base of a ward's return at the close",
	"return_pool": "share of the revive pool added to a ward's return cap",
	"revive": "fallen champions revived (1 = the first, -1 = all)",
	"revive_hp": "HP share they stand up with",
	"wall_hp": "HP of a wall (x ult power)",
	"wall_hp_mult": "x on wall_hp",
	"contact_breaks": "breaks on the barricade a wall absorbs",
	"absorb": "absorb kind (ABSORB_KINDS) -> count (-1 = all)",
	"dmg": "damage per shot",
	"period": "s between shots",
	"homing": "shots home",
	"volleys": "army volley damage + (bucket 2) while the blob centre is inside the field",
	"b2": "machine damage + (bucket 2, inside TEAM_B2_CAP)",
	"breaks_per_s": "breaks per second while it burns",
}
## Keys whose value is itself a dict of ULT_FIELDS (status_at: ULT_TIMING -> such a dict).
const ULT_PARTS: Dictionary[String, String] = {
	"extra": "the follow-up hit that carries the hero's second ult number (HeroData.HEROES.ult2)",
	"field": "a lingering zone",
	"turrets": "turrets on a wall",
	"status_at": "ULT_TIMING -> statuses put on squads at that moment ({target, reach | radius, statuses, ..._s})",
	"buff": "a timed team buff",
	"afterburn": "a struck structure keeps burning",
}
## Values of `at` and the keys of `status_at`.
const ULT_TIMING: Dictionary[String, String] = {
	"cast": "when the ult is cast",
	"end": "when the ult ends / the ward closes",
	"delay": "`delay` s after the cast",
	"wave": "as one more wave after the last",
	"land": "where the flock lands (every struck structure)",
}
## Values of a part's `target`.
const ULT_TARGETS: Dictionary[String, String] = {
	"biggest": "the `count` (1) biggest hostiles within `reach`",
	"biggest_squad": "the biggest squad in reach",
	"area": "the ult's own area again",
	"strip": "a strip `width` u wide from the ult's place to `to` u ahead",
	"all": "every squad on the screen",
	"reach": "every squad within `reach` u",
	"struck": "every squad within `radius` u of a struck structure",
	"farthest": "the fortress gate at the siege, else the farthest structure struck",
	"machines": "the fielded machines",
	"volleys": "the army's volleys (statuses on their targets)",
}
## What a wall, drone or feather takes for the army (KindView.absorb).
const ABSORB_KINDS: Dictionary[String, String] = {
	"turret": "a turret shot at the army",
	"blade": "a blade contact",
	"contact": "a blade or barricade contact",
}
## Bot policy condition -> {params, doc}; a policy {ref, any: [{when, <params>}]} fires when any holds
## (HeroKinds.ult_worth, §10.4).
const POLICY_WHEN: Dictionary = {
	"squads": {"params": ["count", "reach", "from"], "doc": ">= count living squads with d in [hero + from, hero + reach] (from 0)"},
	"flying": {"params": ["reach"], "doc": "a Flying squad within reach"},
	"armored": {"params": ["reach"], "doc": "an Armored squad within reach"},
	"lane": {"params": ["count", "reach"], "doc": ">= count hostiles (squads and structures) in the hero's lane within reach"},
	"fan": {"params": ["count"], "doc": ">= count squads inside the ult's fan (its angle and length)"},
	"structures": {"params": ["count", "reach", "kinds"], "doc": ">= count structures of kinds within reach"},
	"hazards": {"params": ["reach", "kinds"], "doc": "a hazard row of kinds ([] = any) within reach"},
	"gate_row": {"params": ["reach", "hidden"], "doc": "the next gate row within reach (hidden: only while it has unrevealed values)"},
	"clash": {"params": ["within"], "doc": "a clash is on or starts within `within` s"},
	"siege": {"params": [], "doc": "the fortress siege"},
	"army_loss": {"params": ["share", "window"], "doc": ">= share of the army lost in the last window s"},
	"champion_down": {"params": [], "doc": "a champion has fallen"},
}
## Ult kind -> {hero, ref, loc {name, desc, value}, charge, shape, main (the base key that carries
## HEROES[hero].ult_main), base, knobs, forms [II, III, IV, V: null | {name, desc, rule (class rule), element2,
## set, knobs}], policy {ref, any}}.
const ULTS: Dictionary = {
	"quake": {"hero": "titan", "ref": "§6.1", "loc": {"name": "ULT_QUAKE", "desc": "ULT_TITAN_DESC", "value": "ULT_TITAN_VALUE"}, "charge": 40, "shape": "waves", "main": "kills", "base": {"waves": 4, "spacing": 3.5, "gap": 0.18, "from": 1.0, "to": 15.0, "kills": 12, "breaks": 12, "armor_time": 6.0}, "knobs": [], "forms": [null, null, null, null], "policy": {"ref": "§10.4", "any": [{"when": "structures", "count": 1, "reach": 12.0, "kinds": ["barricade", "turret", "geode", "fortress"]}, {"when": "hazards", "reach": 6.0, "kinds": []}]}},  # titan waves, forms I-I
	"anchor": {"hero": "arin", "ref": "§6.2", "loc": {"name": "ULT_ARIN", "desc": "ULT_ARIN_DESC", "value": "ULT_ARIN_VALUE"}, "charge": 36, "shape": "drop", "main": "kills", "base": {"ahead": 8.0, "at_x": true, "radius": 2.5, "kills": 22, "breaks": 22, "hold": 3.0, "hold_width": 4.0, "gate_hits": 3}, "knobs": [], "forms": [null, null, null, null], "policy": {"ref": "§10.4", "any": [{"when": "armored", "reach": 8.0}, {"when": "gate_row", "reach": 8.0, "hidden": false}]}},  # arin drop, forms I-I
	"storm": {"hero": "bolt", "ref": "§6.3", "loc": {"name": "ULT_STORM", "desc": "ULT_BOLT_DESC", "value": "ULT_BOLT_VALUE"}, "charge": 35, "shape": "timed", "main": "kills", "base": {"duration": 3.0, "tick": 0.25, "range": 18.0, "kills": 5, "breaks": 3, "gate_hits": 1}, "knobs": [], "forms": [{"name": null, "desc": "ULT_BOLT_F2_DESC", "rule": "ranger", "element2": "", "set": {"flying_mult": 1.5, "ground_after": 1.0, "statuses": {"jolt": 1}}, "knobs": []}, null, null, null], "policy": {"ref": "§10.4", "any": [{"when": "squads", "count": 2, "reach": 16.0}, {"when": "flying", "reach": 16.0}]}},  # bolt timed, forms I-II
	"rime": {"hero": "eira", "ref": "§6.4", "loc": {"name": "ULT_EIRA", "desc": "ULT_EIRA_DESC", "value": "ULT_EIRA_VALUE"}, "charge": 34, "shape": "area", "main": "kills", "base": {"from": 0.0, "to": 14.0, "width": null, "sweep": 0.6, "kills": 4, "statuses": {"chill": 3}, "freeze_s": 1.0, "heal": 5, "heal_pool": 0.25}, "knobs": [], "forms": [{"name": null, "desc": "ULT_EIRA_F2_DESC", "rule": "healer", "element2": "", "set": {"revive": 1, "revive_hp": 0.5}, "knobs": []}, null, null, null], "policy": {"ref": "§10.4", "any": [{"when": "clash", "within": 1.5}]}},  # eira area, forms I-II
	"rift": {"hero": "seer", "ref": "§6.5", "loc": {"name": "ULT_RIFT", "desc": "ULT_SEER_DESC", "value": "ULT_SEER_VALUE"}, "charge": 38, "shape": "timed", "main": "kills", "base": {"duration": 4.0, "tick": 0.5, "range": 16.0, "ahead": 7.0, "kills": 5, "breaks": 4, "slow": 0.6}, "knobs": [], "forms": [{"name": null, "desc": "ULT_SEER_F2_DESC", "rule": "mage", "element2": "", "set": {"statuses": {"seal": 1}}, "knobs": []}, {"name": "ULT_SEER_F3", "desc": "ULT_SEER_F3_DESC", "rule": "", "element2": "", "set": {"reveal": 30.0, "gate_hits": 1}, "knobs": []}, null, null], "policy": {"ref": "§10.4", "any": [{"when": "gate_row", "reach": 10.0, "hidden": true}, {"when": "squads", "count": 3, "reach": 12.0}]}},  # seer timed, forms I-III
	"comet": {"hero": "iskar", "ref": "§6.6", "loc": {"name": "ULT_ISKAR", "desc": "ULT_ISKAR_DESC", "value": "ULT_ISKAR_VALUE"}, "charge": 36, "shape": "beam", "main": "kills", "base": {"at_x": true, "width": 1.6, "from": 2.0, "to": 30.0, "duration": 1.5, "tick": 0.25, "kills": 6, "breaks": 5, "flying": true, "pierce_shield": true}, "knobs": [], "forms": [{"name": null, "desc": "ULT_ISKAR_F2_DESC", "rule": "ranger", "element2": "", "set": {"flying_mult": 1.5, "ground": 2.0, "paint_s": 4.0}, "knobs": []}, {"name": "ULT_ISKAR_F3", "desc": "ULT_ISKAR_F3_DESC", "rule": "", "element2": "", "set": {"follow": true, "gate_hits": 1}, "knobs": []}, null, null], "policy": {"ref": "§10.4", "any": [{"when": "lane", "count": 3, "reach": 16.0}]}},  # iskar beam, forms I-III
	"sunglaive": {"hero": "vesta", "ref": "§6.7", "loc": {"name": "ULT_VESTA", "desc": "ULT_VESTA_DESC", "value": "ULT_VESTA_VALUE"}, "charge": 38, "shape": "drop", "main": "kills", "base": {"ahead": 5.0, "radius": 6.0, "pulses": 4, "gap": 0.3, "kills": 10, "breaks": 10, "statuses": {"burn": 1}}, "knobs": [], "forms": [{"name": null, "desc": "ULT_VESTA_F2_DESC", "rule": "warrior", "element2": "", "set": {"clash_loss": 0.2, "clash_loss_s": 3.0}, "knobs": ["clash_loss"]}, {"name": "ULT_VESTA_F3", "desc": "ULT_VESTA_F3_DESC", "rule": "", "element2": "", "set": {"field": {"duration": 4.0, "radius": 6.0, "statuses": {"burn": 1}, "volleys": 0.1}}, "knobs": ["field.volleys"]}, {"name": "ULT_VESTA_F4", "desc": "ULT_VESTA_F4_DESC", "rule": "", "element2": "", "set": {"extra": {"at": "delay", "delay": 1.0, "target": "biggest", "reach": 20.0, "radius": 4.0, "kills": 8, "breaks": 8, "neg_gate_hits": 2, "leap_s": 0.6}}, "knobs": []}, null], "policy": {"ref": "§10.4", "any": [{"when": "squads", "count": 2, "reach": 6.0}, {"when": "siege"}]}},  # vesta drop, forms I-IV
	"forgewall": {"hero": "vartan", "ref": "§6.8", "loc": {"name": "ULT_VARTAN", "desc": "ULT_VARTAN_DESC", "value": "ULT_VARTAN_VALUE"}, "charge": 42, "shape": "wall", "main": "kills", "base": {"ahead": 3.0, "width": 6.0, "duration": 5.0, "moves": true, "kills": 8, "statuses": {"stagger": 1}, "wall_hp": 30, "contact_breaks": 10, "absorb": {"turret": -1, "contact": 1}}, "knobs": [], "forms": [{"name": null, "desc": "ULT_VARTAN_F2_DESC", "rule": "guardian", "element2": "", "set": {"wall_hp_mult": 1.5}, "knobs": []}, {"name": "ULT_VARTAN_F3", "desc": "ULT_VARTAN_F3_DESC", "rule": "", "element2": "", "set": {"turrets": {"count": 4, "dmg": 1, "period": 0.5, "homing": true, "flying": true, "statuses": {"mark": 1}}}, "knobs": []}, {"name": "ULT_VARTAN_F4", "desc": "ULT_VARTAN_F4_DESC", "rule": "", "element2": "", "set": {"extra": {"at": "end", "target": "strip", "to": 10.0, "width": 6.0, "kills": 8, "breaks": 8}}, "knobs": []}, null], "policy": {"ref": "§10.4", "any": [{"when": "hazards", "reach": 6.0, "kinds": ["turret", "blade"]}]}},  # vartan wall, forms I-IV
	"spectrum": {"hero": "lumen", "ref": "§6.9", "loc": {"name": "ULT_LUMEN", "desc": "ULT_LUMEN_DESC", "value": "ULT_LUMEN_VALUE"}, "charge": 42, "shape": "fan", "main": "kills", "base": {"rays": 7, "angle": 60.0, "length": 16.0, "at_x": true, "duration": 2.5, "tick": 0.25, "kills": 2, "breaks": 2, "per_squad_max": 2, "flying": true, "pierce_shield": true}, "knobs": [], "forms": [{"name": null, "desc": "ULT_LUMEN_F2_DESC", "rule": "mage", "element2": "", "set": {"statuses": {"burn": 1}}, "knobs": []}, {"name": null, "desc": "ULT_LUMEN_F3_DESC", "rule": "", "element2": "", "set": {"gate_hits": 1}, "knobs": []}, {"name": "ULT_LUMEN_F4", "desc": "ULT_LUMEN_F4_DESC", "rule": "", "element2": "", "set": {"extra": {"at": "end", "target": "biggest", "count": 12, "kills": 4, "breaks": 4}}, "knobs": []}, {"name": "ULT_LUMEN_F5", "desc": "ULT_LUMEN_F5_DESC", "rule": "", "element2": "rune", "set": {"status_at": {"cast": {"target": "all", "statuses": {"seal": 1, "burn": 1}}}, "buff": {"target": "machines", "b2": 0.1, "duration": 6.0}}, "knobs": []}], "policy": {"ref": "§10.4", "any": [{"when": "fan", "count": 3}, {"when": "siege"}]}},  # lumen fan, forms I-V
	"eyes": {"hero": "pava", "ref": "§6.10", "loc": {"name": "ULT_PAVA", "desc": "ULT_PAVA_DESC", "value": "ULT_PAVA_VALUE"}, "charge": 44, "shape": "ward", "main": "return", "base": {"duration": 3.0, "record": 1, "return": 8, "return_pool": 0.3, "status_at": {"cast": {"target": "reach", "reach": 16.0, "statuses": {"seal": 1}}}}, "knobs": [], "forms": [{"name": null, "desc": "ULT_PAVA_F2_DESC", "rule": "healer", "element2": "", "set": {"revive": 1, "revive_hp": 0.5}, "knobs": []}, {"name": "ULT_PAVA_F3", "desc": "ULT_PAVA_F3_DESC", "rule": "", "element2": "", "set": {"record": 2}, "knobs": []}, {"name": "ULT_PAVA_F4", "desc": "ULT_PAVA_F4_DESC", "rule": "", "element2": "", "set": {"extra": {"at": "end", "target": "all", "kills": 4, "reveal": -1.0, "mark_phantoms": true}}, "knobs": []}, {"name": "ULT_PAVA_F5", "desc": "ULT_PAVA_F5_DESC", "rule": "", "element2": "frost", "set": {"revive": -1, "status_at": {"cast": {"statuses": {"chill": 3}, "freeze_s": 1.0}}}, "knobs": []}], "policy": {"ref": "§10.4", "any": [{"when": "army_loss", "share": 0.25, "window": 3.0}, {"when": "champion_down"}]}},  # pava ward, forms I-V
	"letter": {"hero": "sirko", "ref": "§6.28", "loc": {"name": "ULT_SIRKO", "desc": "ULT_SIRKO_DESC", "value": "ULT_SIRKO_VALUE"}, "charge": 42, "shape": "area", "main": "kills", "base": {"from": 3.0, "to": 15.0, "width": null, "duration": 2.0, "kills": 16, "breaks": 16, "statuses": {"stagger": 1, "seal": 1}, "stagger_s": 2.0, "fortress": true}, "knobs": ["kills"], "forms": [{"name": null, "desc": "ULT_SIRKO_F2_DESC", "rule": "warrior", "element2": "", "set": {"to": 19.0, "clash_loss": 0.2, "clash_loss_s": null}, "knobs": ["clash_loss"]}, {"name": "ULT_SIRKO_F3", "desc": "ULT_SIRKO_F3_DESC", "rule": "", "element2": "", "set": {"extra": {"at": "delay", "delay": 1.0, "target": "area", "kills": 8, "breaks": 8, "statuses": {"stagger": 1}, "stagger_s": 2.0}}, "knobs": ["extra.kills", "extra.breaks"]}, {"name": "ULT_SIRKO_F4", "desc": "ULT_SIRKO_F4_DESC", "rule": "", "element2": "", "set": {"strip_s": 5.0}, "knobs": []}, {"name": "ULT_SIRKO_F5", "desc": "ULT_SIRKO_F5_DESC", "rule": "", "element2": "tech", "set": {"buff": {"target": "volleys", "duration": 5.0, "statuses": {"seal": 1, "mark": 1}}}, "knobs": []}], "policy": {"ref": "proposed (§6.28 tip)", "any": [{"when": "squads", "count": 2, "from": 3.0, "reach": 15.0}, {"when": "siege"}]}},  # sirko area, forms I-V
	"doves": {"hero": "olha", "ref": "§6.29", "loc": {"name": "ULT_OLHA", "desc": "ULT_OLHA_DESC", "value": "ULT_OLHA_VALUE"}, "charge": 40, "shape": "flock", "main": "breaks", "base": {"waves": 3, "gap": 0.4, "reach": 30.0, "targets": ["barricade", "turret", "wall", "gate"], "fortress": true, "breaks": 18, "kills": 6, "statuses": {"burn": 1}, "burn_s": 3.0}, "knobs": ["breaks"], "forms": [{"name": null, "desc": "ULT_OLHA_F2_DESC", "rule": "ranger", "element2": "", "set": {"flying_mult": 1.5, "ground": 2.0}, "knobs": []}, {"name": "ULT_OLHA_F3", "desc": "ULT_OLHA_F3_DESC", "rule": "", "element2": "", "set": {"extra": {"at": "wave", "target": "biggest_squad", "kills": 8, "statuses": {"burn": 1}}}, "knobs": ["extra.kills"]}, {"name": "ULT_OLHA_F4", "desc": "ULT_OLHA_F4_DESC", "rule": "", "element2": "", "set": {"silence_s": 3.0}, "knobs": []}, {"name": "ULT_OLHA_F5", "desc": "ULT_OLHA_F5_DESC", "rule": "", "element2": "kinetic", "set": {"afterburn": {"target": "farthest", "duration": 4.0, "breaks_per_s": 3.0}, "status_at": {"land": {"target": "struck", "radius": 6.0, "statuses": {"stagger": 1}, "stagger_s": 1.5}}}, "knobs": ["afterburn.breaks_per_s"]}], "policy": {"ref": "proposed (§6.29 tip)", "any": [{"when": "siege"}, {"when": "structures", "count": 2, "reach": 30.0, "kinds": ["barricade", "turret"]}]}},  # olha flock, forms I-V
}
## Attack pattern -> delivery (the closed set).
const ATTACK_PATTERNS: Dictionary[String, String] = {
	"boulder": "a heavy shot with splash (Горан's rock, Вартан's rivet; HeroKinds.ATTACK_BOULDER)",
	"swing": "melee swings in an arc (`arc` u or `arc_deg` degrees)",
	"dart": "fast straight shots (HeroKinds.ATTACK_DART)",
	"orbs": "homing orbs (HeroKinds.ATTACK_ORBS)",
	"beam": "rays that ignore the Shielded pool",
}
## Every key an attack base, beat or proc may carry -> its meaning.
const ATTACK_FIELDS: Dictionary[String, String] = {
	"rate": "attacks per second (kit)",
	"dmg": "damage per hit (kit)",
	"range": "u (kit; Rangers +2 Long sight)",
	"splash": "extra kills around a squad target (kit)",
	"targets": "targets / rays per cast (kit)",
	"arc": "u, width of a swing",
	"arc_deg": "degrees of a swing",
	"homing": "shots home",
	"pierce": "squads a shot passes through (-1 = the whole corridor)",
	"pierce_shield": "ignores the Shielded pool",
	"statuses": "status id (ArsenalData.STATUSES; seal = BRAND) -> proc per hit",
	"stagger_s": "s of STAGGER",
	"burn_s": "s of BURN",
	"mark_s": "s of MARK",
	"ground": "s a Flying squad hit stays grounded",
	"reground": "s before the same squad can be grounded again",
	"structure_mult": "damage x on structures",
	"reveal_rows": "hidden gate rows a gate hit reveals",
	"charge_mult": "x on charge-gate hits",
	"focus_mult": "x when spare rays converge on fewer targets",
	"drones": "ward-drones, each absorbs one turret shot at the army",
	"drone_recharge": "s a drone recharges",
	"drone_contact_cd": "s, shared cooldown of a drone absorbing a blade / barricade contact",
	"mend_share": "share of soldiers lost that feed the revive pool (Healer Mend)",
	"frozen_clash_loss": "the army's clash losses vs a squad she froze x (1 + this)",
	"vs_burning": "damage + on a burning squad (bucket 2)",
	"burn_jumps": "squads her BURN jumps to on a wipe",
	"burning_machines": "machine damage + on burning squads (bucket 2, inside TEAM_B2_CAP)",
	"burning_volleys": "army volley damage + on burning structures",
	"procs": "proc id -> its rule (ATTACK_PROCS)",
	"on": "what triggers it (ATTACK_TRIGGERS)",
	"every": "every Nth trigger",
	"r": "u",
	"chains": "jumps a fork makes",
	"mult": "damage x",
	"soldiers": "soldiers back from the revive pool",
	"share": "share of the damage repeated",
	"kills": "soldiers removed per squad",
	"breaks": "hp removed per structure",
	"delay": "s",
	"depth": "u along the run",
	"duration": "s",
	"reach": "u ahead",
	"reveal": "u, Phantoms revealed within",
	"reveals": "reveals the Phantom it lands on",
	"rails": "parallel rails",
	"rail_dx": "u between a rail and x",
	"needs": "status the target must carry",
	"cd": "s cooldown",
	"kinds": "absorb kinds (ABSORB_KINDS)",
	"shield_cd": "s cooldown of the front-champion shield",
	"shield_ticks": "clash ticks the shield takes",
	"weaken": "the squad deals this much less clash damage",
	"weaken_s": "s the weaken lasts",
	"target": "farthest | farthest_structure",
	"fallback": "biggest_squad when no structure is in reach",
}
## Proc id -> what it does (keys of an attack's `procs`).
const ATTACK_PROCS: Dictionary[String, String] = {
	"fork": "chains to `targets` more within `r` (`chains` jumps)",
	"throw": "a throw to the `target` hostile within `reach` for x `mult`",
	"mend": "`soldiers` come back from the revive pool",
	"comet": "a bolt down the corridor",
	"eye": "plants an Eye: `soldiers` come back when that squad is wiped",
	"dove": "a dove to the `target` within `reach`",
	"echo": "repeats `share` of the hit on the next structure within `reach` behind",
	"burst": "an explosion `r` u at the target",
	"lance": "pierces the whole corridor for x `mult`",
	"bounce": "bounces to `targets` more within `r`",
	"mark": "MARKs the target",
	"ray": "+`targets` rays this cast",
	"strip": "a burning strip across the bridge",
	"double": "strikes twice",
	"flinch": "the next squad in the lane is STAGGERed",
	"guard": "intercepts one hit of `kinds` per `cd` s",
}
## Values of a proc's `on` (every hero hit when absent).
const ATTACK_TRIGGERS: Dictionary[String, String] = {
	"hit": "every hero hit (the default)",
	"structure": "hits on structures",
	"break": "a structure he breaks",
	"kill": "a hit that kills",
	"wipe": "a squad he wipes",
}
## Hero id -> {ref, loc {name, desc}, pattern, base (kit rate / dmg / range / splash / targets + the sheet's
## run rules), beats {"3" / "6" / "9": {name, desc, set, knobs}}, clips {attack_a, attack_b, b_on (the proc
## that plays attack_b)}}. Class traits are HERO_CLASS_RUN.
const ATTACKS: Dictionary = {
	"titan": {"ref": "§6.1", "loc": {"name": "ATK_TITAN", "desc": "ATK_TITAN_DESC"}, "pattern": "boulder", "base": {"rate": 1.2, "dmg": 4, "range": 12, "splash": 3, "targets": 1, "structure_mult": 1.5}, "beats": {"3": {"name": "ATK_TITAN_B3", "desc": "ATK_TITAN_B3_DESC", "set": {"statuses": {"stagger": 1.0}, "stagger_s": 0.4}, "knobs": []}, "6": {"name": "ATK_TITAN_B6", "desc": "ATK_TITAN_B6_DESC", "set": {"procs": {"echo": {"on": "structure", "every": 4, "share": 0.5, "reach": 4.0}}}, "knobs": ["procs.echo.share"]}, "9": {"name": "ATK_TITAN_B9", "desc": "ATK_TITAN_B9_DESC", "set": {"procs": {"burst": {"on": "break", "breaks": 2, "r": 1.5}}}, "knobs": ["procs.burst.breaks"]}}, "clips": {"attack_a": "throw", "attack_b": "ground slam", "b_on": null}},  # boulder, procs -
	"arin": {"ref": "§6.2", "loc": {"name": "ATK_ARIN", "desc": "ATK_ARIN_DESC"}, "pattern": "swing", "base": {"rate": 1.6, "dmg": 3, "range": 11, "splash": 2, "targets": 1, "arc": 1.5, "statuses": {"stagger": 1.0}, "procs": {"throw": {"every": 4, "target": "farthest", "reach": 11.0, "mult": 2.0}}}, "beats": {"3": {"name": "ATK_ARIN_B3", "desc": "ATK_ARIN_B3_DESC", "set": {"procs": {"throw": {"every": 3}}}, "knobs": []}, "6": {"name": "ATK_ARIN_B6", "desc": "ATK_ARIN_B6_DESC", "set": {"procs": {"throw": {"weaken": 0.15, "weaken_s": 3.0}}}, "knobs": ["procs.throw.weaken"]}, "9": {"name": "ATK_ARIN_B9", "desc": "ATK_ARIN_B9_DESC", "set": {"procs": {"burst": {"every": 12, "r": 1.5, "kills": 6}}}, "knobs": ["procs.burst.kills"]}}, "clips": {"attack_a": "overhead swing", "attack_b": "chain throw", "b_on": "throw"}},  # swing, procs throw
	"bolt": {"ref": "§6.3", "loc": {"name": "ATK_BOLT", "desc": "ATK_BOLT_DESC"}, "pattern": "dart", "base": {"rate": 3.6, "dmg": 1, "range": 15, "splash": 0, "targets": 1, "ground": 1.2, "reground": 4.0, "procs": {"fork": {"every": 3, "targets": 1, "r": 4.0, "chains": 1}}}, "beats": {"3": {"name": "ATK_BOLT_B3", "desc": "ATK_BOLT_B3_DESC", "set": {"procs": {"fork": {"r": 5.0, "chains": 2}}}, "knobs": ["procs.fork.chains"]}, "6": {"name": "ATK_BOLT_B6", "desc": "ATK_BOLT_B6_DESC", "set": {"procs": {"lance": {"every": 8, "mult": 2.0}}}, "knobs": ["procs.lance.mult"]}, "9": {"name": "ATK_BOLT_B9", "desc": "ATK_BOLT_B9_DESC", "set": {"procs": {"fork": {"statuses": {"jolt": 1.0}}}}, "knobs": []}}, "clips": {"attack_a": "paw flick", "attack_b": "two-paw rail shot", "b_on": "lance"}},  # dart, procs fork
	"eira": {"ref": "§6.4", "loc": {"name": "ATK_EIRA", "desc": "ATK_EIRA_DESC"}, "pattern": "beam", "base": {"rate": 2.0, "dmg": 1, "range": 14, "splash": 0, "targets": 1, "pierce_shield": true, "statuses": {"chill": 0.5}, "procs": {"mend": {"every": 6, "soldiers": 1}}}, "beats": {"3": {"name": "ATK_EIRA_B3", "desc": "ATK_EIRA_B3_DESC", "set": {"mend_share": 0.25}, "knobs": []}, "6": {"name": "ATK_EIRA_B6", "desc": "ATK_EIRA_B6_DESC", "set": {"frozen_clash_loss": -0.15}, "knobs": []}, "9": {"name": "ATK_EIRA_B9", "desc": "ATK_EIRA_B9_DESC", "set": {"procs": {"mend": {"shield_cd": 10.0, "shield_ticks": 1}}}, "knobs": []}}, "clips": {"attack_a": "pluck", "attack_b": "two-hand chord (heal)", "b_on": "mend"}},  # beam, procs mend
	"seer": {"ref": "§6.5", "loc": {"name": "ATK_SEER", "desc": "ATK_SEER_DESC"}, "pattern": "orbs", "base": {"rate": 2.0, "dmg": 1, "range": 16, "splash": 0, "targets": 2, "homing": true, "reveal_rows": 1, "charge_mult": 1.5, "statuses": {"seal": 0.5}}, "beats": {"3": {"name": "ATK_SEER_B3", "desc": "ATK_SEER_B3_DESC", "set": {"procs": {"bounce": {"on": "kill", "targets": 1, "r": 3.0}}}, "knobs": []}, "6": {"name": "ATK_SEER_B6", "desc": "ATK_SEER_B6_DESC", "set": {"procs": {"mark": {"every": 8, "mark_s": 3.0, "reveal": 4.0}}}, "knobs": []}, "9": {"name": "ATK_SEER_B9", "desc": "ATK_SEER_B9_DESC", "set": {"reveal_rows": 2}, "knobs": []}}, "clips": {"attack_a": "cast", "attack_b": null, "b_on": null}},  # orbs, procs -
	"iskar": {"ref": "§6.6", "loc": {"name": "ATK_ISKAR", "desc": "ATK_ISKAR_DESC"}, "pattern": "dart", "base": {"rate": 3.2, "dmg": 1, "range": 16, "splash": 0, "targets": 1, "pierce": 1, "procs": {"comet": {"every": 6, "pierce": -1, "mult": 3.0, "pierce_shield": true, "statuses": {"jolt": 1.0}}}}, "beats": {"3": {"name": "ATK_ISKAR_B3", "desc": "ATK_ISKAR_B3_DESC", "set": {"pierce": 2}, "knobs": []}, "6": {"name": "ATK_ISKAR_B6", "desc": "ATK_ISKAR_B6_DESC", "set": {"procs": {"comet": {"every": 5}}}, "knobs": []}, "9": {"name": "ATK_ISKAR_B9", "desc": "ATK_ISKAR_B9_DESC", "set": {"procs": {"comet": {"rails": 2, "rail_dx": 0.6}}}, "knobs": []}}, "clips": {"attack_a": null, "attack_b": "full-draw rail", "b_on": "comet"}},  # dart, procs comet
	"vesta": {"ref": "§6.7", "loc": {"name": "ATK_VESTA", "desc": "ATK_VESTA_DESC"}, "pattern": "swing", "base": {"rate": 1.5, "dmg": 3, "range": 12, "splash": 2, "targets": 1, "arc_deg": 120.0, "statuses": {"burn": 1.0}}, "beats": {"3": {"name": "ATK_VESTA_B3", "desc": "ATK_VESTA_B3_DESC", "set": {"procs": {"strip": {"every": 4, "depth": 3.0, "duration": 2.0, "statuses": {"burn": 1.0}}}}, "knobs": []}, "6": {"name": "ATK_VESTA_B6", "desc": "ATK_VESTA_B6_DESC", "set": {"vs_burning": 0.1}, "knobs": []}, "9": {"name": "ATK_VESTA_B9", "desc": "ATK_VESTA_B9_DESC", "set": {"procs": {"burst": {"every": 10, "r": 4.0, "kills": 6, "statuses": {"burn": 1.0}}}}, "knobs": []}}, "clips": {"attack_a": "sweep", "attack_b": "rising slash", "b_on": null}},  # swing, procs -
	"vartan": {"ref": "§6.8", "loc": {"name": "ATK_VARTAN", "desc": "ATK_VARTAN_DESC"}, "pattern": "boulder", "base": {"rate": 1.1, "dmg": 4, "range": 12, "splash": 3, "targets": 1, "statuses": {"mark": 1.0}, "drones": 2, "drone_recharge": 6.0}, "beats": {"3": {"name": "ATK_VARTAN_B3", "desc": "ATK_VARTAN_B3_DESC", "set": {"drones": 3}, "knobs": []}, "6": {"name": "ATK_VARTAN_B6", "desc": "ATK_VARTAN_B6_DESC", "set": {"drone_contact_cd": 8.0}, "knobs": []}, "9": {"name": "ATK_VARTAN_B9", "desc": "ATK_VARTAN_B9_DESC", "set": {"procs": {"burst": {"on": "structure", "delay": 1.0, "dmg": 2, "r": 1.5}}}, "knobs": []}}, "clips": {"attack_a": "recoil", "attack_b": "shield bash", "b_on": null}},  # boulder, procs -
	"lumen": {"ref": "§6.9", "loc": {"name": "ATK_LUMEN", "desc": "ATK_LUMEN_DESC"}, "pattern": "beam", "base": {"rate": 2.2, "dmg": 1, "range": 15, "splash": 1, "targets": 2, "pierce_shield": true, "statuses": {"burn": 0.5}, "focus_mult": 1.5}, "beats": {"3": {"name": "ATK_LUMEN_B3", "desc": "ATK_LUMEN_B3_DESC", "set": {"procs": {"ray": {"every": 3, "targets": 1}}}, "knobs": []}, "6": {"name": "ATK_LUMEN_B6", "desc": "ATK_LUMEN_B6_DESC", "set": {"procs": {"lance": {"every": 5, "mult": 3.0}}}, "knobs": []}, "9": {"name": "ATK_LUMEN_B9", "desc": "ATK_LUMEN_B9_DESC", "set": {"burn_jumps": 2, "burning_machines": 0.08}, "knobs": []}}, "clips": {"attack_a": "prism flick", "attack_b": "two-hand lance", "b_on": "lance"}},  # beam, procs -
	"pava": {"ref": "§6.10", "loc": {"name": "ATK_PAVA", "desc": "ATK_PAVA_DESC"}, "pattern": "dart", "base": {"rate": 1.9, "dmg": 1, "range": 14, "splash": 0, "targets": 1, "statuses": {"seal": 1.0}, "procs": {"eye": {"every": 5, "soldiers": 1}}}, "beats": {"3": {"name": "ATK_PAVA_B3", "desc": "ATK_PAVA_B3_DESC", "set": {"mend_share": 0.25, "procs": {"eye": {"every": 4}}}, "knobs": []}, "6": {"name": "ATK_PAVA_B6", "desc": "ATK_PAVA_B6_DESC", "set": {"procs": {"eye": {"statuses": {"mark": 1.0}, "reveals": true}}}, "knobs": []}, "9": {"name": "ATK_PAVA_B9", "desc": "ATK_PAVA_B9_DESC", "set": {"procs": {"guard": {"cd": 10.0, "kinds": ["turret", "blade"]}}}, "knobs": []}}, "clips": {"attack_a": "staff flick", "attack_b": "fan snap", "b_on": null}},  # dart, procs eye
	"sirko": {"ref": "§6.28", "loc": {"name": "ATK_SIRKO", "desc": "ATK_SIRKO_DESC"}, "pattern": "swing", "base": {"rate": 1.7, "dmg": 3, "range": 11, "splash": 2, "targets": 1, "arc": 1.5, "statuses": {"seal": 1.0}}, "beats": {"3": {"name": "ATK_SIRKO_B3", "desc": "ATK_SIRKO_B3_DESC", "set": {"procs": {"double": {"every": 4}}}, "knobs": []}, "6": {"name": "ATK_SIRKO_B6", "desc": "ATK_SIRKO_B6_DESC", "set": {"procs": {"flinch": {"on": "wipe", "needs": "seal", "statuses": {"stagger": 1.0}, "stagger_s": 1.0}}}, "knobs": []}, "9": {"name": "ATK_SIRKO_B9", "desc": "ATK_SIRKO_B9_DESC", "set": {"procs": {"burst": {"every": 10, "r": 3.0, "kills": 6, "statuses": {"seal": 1.0}}}}, "knobs": ["procs.burst.kills"]}}, "clips": {"attack_a": "diagonal sabre cut", "attack_b": "turning double cut", "b_on": "double"}},  # swing, procs -
	"olha": {"ref": "§6.29", "loc": {"name": "ATK_OLHA", "desc": "ATK_OLHA_DESC"}, "pattern": "dart", "base": {"rate": 3.4, "dmg": 1, "range": 16, "splash": 0, "targets": 1, "procs": {"dove": {"every": 6, "target": "farthest_structure", "reach": 20.0, "fallback": "biggest_squad", "statuses": {"burn": 1.0}, "burn_s": 3.0}}}, "beats": {"3": {"name": "ATK_OLHA_B3", "desc": "ATK_OLHA_B3_DESC", "set": {"pierce": 1}, "knobs": []}, "6": {"name": "ATK_OLHA_B6", "desc": "ATK_OLHA_B6_DESC", "set": {"burning_volleys": 0.15}, "knobs": ["burning_volleys"]}, "9": {"name": "ATK_OLHA_B9", "desc": "ATK_OLHA_B9_DESC", "set": {"procs": {"dove": {"every": 5, "reach": 24.0}}}, "knobs": []}}, "clips": {"attack_a": "quick draw and loose", "attack_b": "looses a dove upward", "b_on": "dove"}},  # dart, procs dove
}
## Class -> hero class trait numbers in the run. (heroes_design.md §5.1)
const HERO_CLASS_RUN: Dictionary = {"warrior": {"cleave": 1.5}, "ranger": {"sight": 2.0}, "mage": {"proc": 0.5}, "guardian": {"bulwark_hp": 1.5}, "healer": {"mend_share": 0.2}}

## Where every generated constant comes from: consts:<path> = tools/data/heroes_consts.json,
## roster:<path> = tools/data/heroes_roster.json (both checked by scripts/dev/test_heroes.gd),
## doc:<§> = heroes_design.md, derived:<rule> = computed by the generator from the json.
const SOURCE_KEYS: Dictionary[String, String] = {
	"HERO_ORDER": "roster:hero_order",
	"HEROES": "roster:heroes",
	"STARTERS": "roster:starters",
	"START_OWNED": "roster:start_owned",
	"STARTER_AT": "roster:starter_at",
	"UNLOCK_AT": "consts:unlocks",
	"DUP_FRAGS": "consts:progress.DUP_FRAGS",
	"FACET_FRAGS": "consts:progress.FACET_FRAGS",
	"RECUT_FRAGS": "consts:progress.RECUT_FRAGS",
	"RECUT_COINS": "consts:progress.RECUT_COINS",
	"OVERFLOW_FRAGS_PER_TOME": "consts:progress.OVERFLOW_FRAGS_PER_TOME",
	"TOME_COST": "consts:progress.TOME_COST",
	"SKILL_COINS": "consts:progress.SKILL_COINS",
	"HERO_SYNC_BEHIND": "consts:progress.HERO_SYNC_BEHIND",
	"GEAR_SLOT_AT": "consts:progress.GEAR_SLOT_AT",
	"CHRONICLE_PRICES": "consts:progress.CHRONICLE_PRICES",
	"FEATS": "consts:feats",
	"ULT_SHAPES": "roster:kind_vocab.ult_shapes",
	"ULT_FIELDS": "roster:kind_vocab.ult_fields",
	"ULT_PARTS": "roster:kind_vocab.ult_parts",
	"ULT_TIMING": "roster:kind_vocab.ult_timing",
	"ULT_TARGETS": "roster:kind_vocab.ult_targets",
	"ABSORB_KINDS": "roster:kind_vocab.absorb_kinds",
	"POLICY_WHEN": "roster:kind_vocab.policy_when",
	"ULTS": "roster:ults",
	"ATTACK_PATTERNS": "roster:kind_vocab.attack_patterns",
	"ATTACK_FIELDS": "roster:kind_vocab.attack_fields",
	"ATTACK_PROCS": "roster:kind_vocab.attack_procs",
	"ATTACK_TRIGGERS": "roster:kind_vocab.attack_triggers",
	"ATTACKS": "roster:attacks",
	"HERO_CLASS_RUN": "doc:§5.1",
}
# </GENERATED>


# ------------------------------------------------------------------ helpers (hand-written)

## Native gem key of hero `id` ("" for an unknown id).
static func native(id: String) -> String:
	return str((HEROES.get(id, {}) as Dictionary).get("native", ""))


## Fragments for one duplicate copy of a character born `native_gem` (heroes and champions).
static func dup_frags(native_gem: String) -> int:
	return DUP_FRAGS[Ladder.gem_index(native_gem)]


## Fragments to reach Full facets from 0 at `gem`.
static func full_facets_cost(gem: String) -> int:
	var s := 0
	for v: int in FACET_FRAGS[Ladder.gem_index(gem)]:
		s += v
	return s


# ------------------------------------------------------------------ ults and attacks (§6 sheets as data)

## Ult kind of hero `id` ("" for an unknown id; heroes_design.md §6.0).
static func ult_kind(id: String) -> String:
	return str((HEROES.get(id, {}) as Dictionary).get("ult", ""))


## The highest form ult `kind` has: 1 + the forms its native gem does not cap (0 for an unknown kind).
static func ult_top_form(kind: String) -> int:
	var u: Dictionary = ULTS.get(kind, {})
	if u.is_empty():
		return 0
	var n := 1
	for f: Variant in u["forms"]:
		if f == null:
			break
		n += 1
	return n


## The numbers of ult `kind` at form `form` (1 = I ... 5 = V; §6 sheets): ULTS[kind].base with the deltas of forms
## II .. `form` merged in order (merged()). A form the native gem caps ends the merge, so a form past the cap gives
## the top form. A fresh copy; {} for an unknown kind. kills / breaks / heal / return / wall_hp are still x ult power.
static func ult_numbers(kind: String, form: int) -> Dictionary:
	var u: Dictionary = ULTS.get(kind, {})
	if u.is_empty():
		return {}
	var out := merged({}, u["base"])
	var forms: Array = u["forms"]
	for i in clampi(form - 1, 0, forms.size()):
		if forms[i] == null:
			break
		out = merged(out, (forms[i] as Dictionary)["set"])
	return out


## Hero `id`'s attack at Attack rank `rank` (§6 sheets): ATTACKS[id].base with every beat of Ladder.ATK_BEATS up to
## `rank` merged in rank order (merged()). A fresh copy; {} for an unknown id. Class traits are HERO_CLASS_RUN.
static func attack_numbers(id: String, rank: int) -> Dictionary:
	var a: Dictionary = ATTACKS.get(id, {})
	if a.is_empty():
		return {}
	var out := merged({}, a["base"])
	var beats: Dictionary = a["beats"]
	for b: int in Ladder.ATK_BEATS:
		if b <= rank and beats.has(str(b)):
			out = merged(out, (beats[str(b)] as Dictionary)["set"])
	return out


## `a` with `b` merged in, the one rule of ult forms and attack beats: a key whose values in both are Dictionaries
## merges recursively, any other value of `b` replaces. Returns a deep copy (the const tables stay untouched).
static func merged(a: Dictionary, b: Dictionary) -> Dictionary:
	var out: Dictionary = a.duplicate(true)
	for k: Variant in b:
		var v: Variant = b[k]
		if v is Dictionary and out.get(k) is Dictionary:
			out[k] = merged(out[k], v)
		elif v is Dictionary:
			out[k] = (v as Dictionary).duplicate(true)
		elif v is Array:
			out[k] = (v as Array).duplicate(true)
		else:
			out[k] = v
	return out
