class_name HeroData
extends RefCounted
## Heroes & Champions data (heroes_design.md §12.2, WS-A). The block below is generated by
## tools/gen_heroes_data.py from tools/data/heroes_consts.json + heroes_roster.json; hand-written
## helpers go after it. Nothing in the shipped game reads this class before EconData.HEROES_PHASE >= 1.

# <GENERATED by tools/gen_heroes_data.py — edit the json / the generator, never this block>
## Sources: heroes_consts.json sha256 6993c4c2e6e4fd89, heroes_roster.json sha256 2fafefef60d8c470.

# ---- roster (heroes_design.md §6.0; kit = Lv1 rank-1 Quartz-normalised, eff = kit x Ladder.NATIVE_MULT[native])
## Collector order 01-10.
const HERO_ORDER: Array[String] = ["titan", "arin", "bolt", "eira", "seer", "iskar", "vesta", "vartan", "lumen", "pava"]
## id -> {no, native, class, element, element2 (ult form V), faction, niche, ult (kind id), kit {hp, rate, dmg,
## splash, range, targets, ult_charge}, ult_main {value, note}, ult2 {value, note, rank}, rally {hook, param, base,
## note}}. Notes are designer notes for tools, never UI copy (names and texts are Loc HERO_<ID>*).
const HEROES: Dictionary = {
	"titan": {"no": 1, "native": "C", "class": "guardian", "element": "kinetic", "element2": "", "faction": "stoneheart", "niche": "structures", "ult": "quake", "kit": {"hp": 32, "rate": 1.2, "dmg": 4, "splash": 3, "range": 12, "targets": 1, "ult_charge": 40}, "ult_main": {"value": 12, "note": "kills & breaks per band (4 bands)"}, "ult2": {}, "rally": {"hook": "army_scrape", "param": "", "base": 3.0, "note": "soldiers spared per hazard contact"}},  # C guardian quake
	"arin": {"no": 2, "native": "C", "class": "warrior", "element": "kinetic", "element2": "", "faction": "dawn", "niche": "armored", "ult": "anchor", "kit": {"hp": 26, "rate": 1.6, "dmg": 3, "splash": 2, "range": 11, "targets": 1, "ult_charge": 36}, "ult_main": {"value": 22, "note": "impact kills & breaks"}, "ult2": {}, "rally": {"hook": "army_drill", "param": "", "base": 0.075, "note": "extra clash loss of squads he hit"}},  # C warrior anchor
	"bolt": {"no": 3, "native": "R", "class": "ranger", "element": "volt", "element2": "", "faction": "wildfang", "niche": "flying", "ult": "storm", "kit": {"hp": 14, "rate": 3.6, "dmg": 1, "splash": 0, "range": 15, "targets": 1, "ult_charge": 35}, "ult_main": {"value": 5, "note": "storm kills per tick (12 ticks)"}, "ult2": {}, "rally": {"hook": "machines_element", "param": "volt", "base": 0.03, "note": "Volt machine damage, bucket 2"}},  # R ranger storm
	"eira": {"no": 4, "native": "R", "class": "healer", "element": "frost", "element2": "", "faction": "dawn", "niche": "shielded", "ult": "rime", "kit": {"hp": 20, "rate": 2.0, "dmg": 1, "splash": 0, "range": 14, "targets": 1, "ult_charge": 34}, "ult_main": {"value": 4, "note": "Litany kills per squad"}, "ult2": {}, "rally": {"hook": "champions_hp", "param": "", "base": 0.15, "note": "champion HP x(1+v)"}},  # R healer rime
	"seer": {"no": 5, "native": "E", "class": "mage", "element": "rune", "element2": "", "faction": "wildfang", "niche": "", "ult": "rift", "kit": {"hp": 18, "rate": 2.0, "dmg": 1, "splash": 0, "range": 16, "targets": 2, "ult_charge": 38}, "ult_main": {"value": 5, "note": "rift kills per tick (8 ticks)"}, "ult2": {}, "rally": {"hook": "ult_start", "param": "", "base": 0.1, "note": "ult charge at level start"}},  # E mage rift
	"iskar": {"no": 6, "native": "E", "class": "ranger", "element": "volt", "element2": "", "faction": "celestial", "niche": "", "ult": "comet", "kit": {"hp": 13, "rate": 3.2, "dmg": 1, "splash": 0, "range": 16, "targets": 1, "ult_charge": 36}, "ult_main": {"value": 6, "note": "comet kills per tick (6 ticks)"}, "ult2": {}, "rally": {"hook": "machines_verb", "param": "lane", "base": 0.025, "note": "LANE machine damage, bucket 2"}},  # E ranger comet
	"vesta": {"no": 7, "native": "L", "class": "warrior", "element": "plasma", "element2": "", "faction": "dawn", "niche": "", "ult": "sunglaive", "kit": {"hp": 27, "rate": 1.5, "dmg": 3, "splash": 2, "range": 12, "targets": 1, "ult_charge": 38}, "ult_main": {"value": 10, "note": "Sunrise kills & breaks per pulse (4 pulses)"}, "ult2": {"value": 8, "note": "Sunstride slam (form IV)", "rank": 7}, "rally": {"hook": "army_reserves", "param": "", "base": 6.0, "note": "soldiers joining at the siege"}},  # L warrior sunglaive
	"vartan": {"no": 8, "native": "L", "class": "guardian", "element": "tech", "element2": "", "faction": "stoneheart", "niche": "", "ult": "forgewall", "kit": {"hp": 33, "rate": 1.1, "dmg": 4, "splash": 3, "range": 12, "targets": 1, "ult_charge": 42}, "ult_main": {"value": 8, "note": "wall contact kills (wall HP 30 scales the same)"}, "ult2": {"value": 8, "note": "Landslide (form IV)", "rank": 7}, "rally": {"hook": "army_volleys", "param": "", "base": 0.15, "note": "army volley damage x(1+v)"}},  # L guardian forgewall
	"lumen": {"no": 9, "native": "M", "class": "mage", "element": "plasma", "element2": "rune", "faction": "celestial", "niche": "", "ult": "spectrum", "kit": {"hp": 17, "rate": 2.2, "dmg": 1, "splash": 1, "range": 15, "targets": 2, "ult_charge": 42}, "ult_main": {"value": 2, "note": "fan kills & breaks per ray per tick (10 ticks)"}, "ult2": {"value": 4, "note": "Crown Shard hit (form IV)", "rank": 7}, "rally": {"hook": "machines_element", "param": "plasma", "base": 0.03, "note": "Plasma machine damage, bucket 2"}},  # M mage spectrum
	"pava": {"no": 10, "native": "M", "class": "healer", "element": "rune", "element2": "frost", "faction": "wildfang", "niche": "", "ult": "eyes", "kit": {"hp": 21, "rate": 1.9, "dmg": 1, "splash": 0, "range": 14, "targets": 1, "ult_charge": 44}, "ult_main": {"value": 8, "note": "fan base return (+30% of the revive pool)"}, "ult2": {"value": 4, "note": "Eyes Wide kills (form IV)", "rank": 7}, "rally": {"hook": "champions_aura", "param": "", "base": 0.06, "note": "champion aura value x(1+v)"}},  # M healer eyes
}
const STARTERS: Array[String] = ["titan", "bolt", "seer"]
## Heroes owned by a brand-new account.
const START_OWNED: Array[String] = ["bolt"]
## Starter -> the level after which it joins (0 = from the start; Мейра 24, guest at L5).
const STARTER_AT: Dictionary[String, int] = {"titan": 4, "bolt": 0, "seer": 24}

# ---- unlock levels (after_win; §11.1)
const UNLOCK_AT: Dictionary[String, int] = {"champions": 14, "portal": 20, "seer": 24, "skills": 30, "workshop": 32, "slot3": 40}

# ---- PROGRESS (§3.2, §3.3; champions reuse the fragment tables)
## PROGRESS[...] in the design = these constants.
const DUP_FRAGS: Array[int] = [10, 15, 25, 50, 100]
## FACET_FRAGS[g][f] = fragments for facet f -> f + 1 at gem g.
const FACET_FRAGS: Array = [[5, 5, 10, 10, 20], [10, 10, 15, 15, 25], [15, 15, 20, 20, 30], [20, 20, 30, 30, 50], [30, 30, 40, 40, 60]]
## RECUT_FRAGS[g] = fragments for the recut g -> g + 1.
const RECUT_FRAGS: Array[int] = [40, 60, 100, 150]
const RECUT_COINS: Array[int] = [0, 0, 0, 0]
const OVERFLOW_FRAGS_PER_TOME: int = 20
## TOME_COST[r] = Tomes for skill rank r -> r + 1.
const TOME_COST: Array[int] = [0, 2, 3, 5, 8, 12, 16, 20, 25, 30, 40]
const SKILL_COINS: int = 0
const HERO_SYNC_BEHIND: int = 3
const GEAR_SLOT_AT: Dictionary[String, int] = {"weapon": 1, "armour": 4, "charm": 8, "relic": 12}
const CHRONICLE_PRICES: Array[int] = [10, 15, 20, 30, 40]

# ---- hero Feats (§3.6; pay Tomes, never Beacons)
const FEATS: Dictionary = {"F-61": {"counter": "heroes_owned", "tiers": [4, 7, 10], "reward": ["tomes", [2, 4, 8]]}, "F-62": {"counter": "recuts", "tiers": [1, 6, 20], "reward": ["tomes", [2, 4, 8]]}, "F-63": {"counter": "full_cuts", "tiers": [2, 10, 30], "reward": ["tomes", [2, 4, 8]]}, "F-64": {"counter": "champions_owned", "tiers": [4, 8, 12], "reward": ["tomes", [2, 4, 8]]}, "F-65": {"counter": "skill_ranks", "tiers": [10, 40, 100], "reward": ["tomes", [2, 4, 8]]}, "F-66": {"counter": "awakenings", "tiers": [1, 3, 6], "reward": ["tomes", [2, 4, 8]]}, "F-70": {"counter": "champion_level", "tiers": [5, 12, 20], "reward": ["tomes", [2, 4, 8]]}}

## Where every generated constant comes from: consts:<path> = tools/data/heroes_consts.json,
## roster:<path> = tools/data/heroes_roster.json (both checked by scripts/dev/test_heroes.gd),
## doc:<§> = heroes_design.md, derived:<rule> = computed by the generator from the json.
const SOURCE_KEYS: Dictionary[String, String] = {
	"HERO_ORDER": "roster:hero_order",
	"HEROES": "roster:heroes",
	"STARTERS": "roster:starters",
	"START_OWNED": "roster:start_owned",
	"STARTER_AT": "roster:starter_at",
	"UNLOCK_AT": "consts:unlocks",
	"DUP_FRAGS": "consts:progress.DUP_FRAGS",
	"FACET_FRAGS": "consts:progress.FACET_FRAGS",
	"RECUT_FRAGS": "consts:progress.RECUT_FRAGS",
	"RECUT_COINS": "consts:progress.RECUT_COINS",
	"OVERFLOW_FRAGS_PER_TOME": "consts:progress.OVERFLOW_FRAGS_PER_TOME",
	"TOME_COST": "consts:progress.TOME_COST",
	"SKILL_COINS": "consts:progress.SKILL_COINS",
	"HERO_SYNC_BEHIND": "consts:progress.HERO_SYNC_BEHIND",
	"GEAR_SLOT_AT": "consts:progress.GEAR_SLOT_AT",
	"CHRONICLE_PRICES": "consts:progress.CHRONICLE_PRICES",
	"FEATS": "consts:feats",
}
# </GENERATED>


# ------------------------------------------------------------------ helpers (hand-written)

## Native gem key of hero `id` ("" for an unknown id).
static func native(id: String) -> String:
	return str((HEROES.get(id, {}) as Dictionary).get("native", ""))


## Fragments for one duplicate copy of a character born `native_gem` (heroes and champions).
static func dup_frags(native_gem: String) -> int:
	return DUP_FRAGS[Ladder.gem_index(native_gem)]


## Fragments to reach Full facets from 0 at `gem`.
static func full_facets_cost(gem: String) -> int:
	var s := 0
	for v: int in FACET_FRAGS[Ladder.gem_index(gem)]:
		s += v
	return s
