class_name Ladder
extends RefCounted
## Heroes & Champions data (heroes_design.md §12.2, WS-A). The block below is generated by
## tools/gen_heroes_data.py from tools/data/heroes_consts.json + heroes_roster.json; hand-written
## helpers go after it. Nothing in the shipped game reads this class before EconData.HEROES_PHASE >= 1.

# <GENERATED by tools/gen_heroes_data.py — edit the json / the generator, never this block>
## Sources: heroes_consts.json sha256 652c2fc3bfb2e83f, heroes_roster.json sha256 324878e62b9b0a76.

# ---- gems (keys = the Meta-1 rarity enum; display names come from Loc GEM_C ... GEM_M)
const GEMS: Array[String] = ["C", "R", "E", "L", "M"]
## Reference names (Кварц, Сапфір, Аметист, Топаз, Опал); UI copy reads Loc, never these.
const GEM_NAME_UK: Array[String] = ["Кварц", "Сапфір", "Аметист", "Топаз", "Опал"]
const GEM_NAME_EN: Array[String] = ["Quartz", "Sapphire", "Amethyst", "Topaz", "Opal"]
const HERO_MAX_GEM: String = "M"
## Champion recut stops at Topaz (§4.1).
const CHAMPION_MAX_GEM: String = "L"

# ---- B1 stats: ladder(n, g, f) = NATIVE_MULT[n] x RECUT_STEP^(g - n) x (1 + FACET_STEP f)  (§2.2)
const Q_NATIVE: float = 1.08
const FACET_STEP: float = 0.0073
const NATIVE_MULT: Array[float] = [1.0, 1.08, 1.1664, 1.2597120000000002, 1.3604889600000003]
const RECUT_STEP: float = 1.0365
const CEILING: float = 0.96
const FACETS_PER_GEM: int = 5

# ---- B2 skills (F-CAP): skill_cap(n, g, f) = SKILL_BASE[g] - [g > n] + [f == FACETS_PER_GEM]
const SKILL_BASE: Array[int] = [2, 4, 6, 8, 10]

# ---- B3 ult forms: ult_form(n, rank) = min(n + 1, #{FORM_AT_RANK <= rank})
const FORM_AT_RANK: Array[int] = [1, 3, 5, 7, 9]

# ---- B4 Awakening (F-AWK2): can_awaken = g >= AWAKEN_MIN_GEM and (f == 5 or (g == n and n >= BORN_AWAKENED_MIN))
const AWAKEN_MIN_GEM: String = "E"
## awaken_cap(n, g) = AWAKEN_CAP[g] - [g > n] (0 below AWAKEN_MIN_GEM).
const AWAKEN_CAP: Dictionary[String, int] = {"E": 2, "L": 3, "M": 4}
const BORN_AWAKENED_MIN: String = "L"

# ---- rank steps and the hero level curve (§3.1, §3.3)
const ULT_RANK_STEP: float = 0.05
const ATK_RANK_STEP: float = 0.01
const RALLY_RANK_STEP: float = 0.1
const LV_DMG: float = 0.035
const LV_HP: float = 0.04
const LV_RATE: float = 0.01
const LV_ULT: float = 0.036
## Attack rule beats (ranks).
const ATK_BEATS: Array[int] = [3, 6, 9]

# ---- budgets (§2.3 kit profile bands; LevelSim / test_kit_budget)
const AWK_STEP: float = 0.04
const AWK_TOL: float = 0.005
const FORM_STEP: float = 0.03
const FORM_TOL: float = 0.005
const ATK_BEAT: float = 0.01
const BEAT_TOL: float = 0.003
const RELIC_BEAT: float = 0.03
const RELIC_TOL: float = 0.005
const KIT_TOL: float = 0.015
const SET4_VALUE: float = 0.05
const U_SHARE: float = 0.3
const HP_W: float = 0.05
const RALLY_W: float = 0.03

## Where every generated constant comes from: consts:<path> = tools/data/heroes_consts.json,
## roster:<path> = tools/data/heroes_roster.json (both checked by scripts/dev/test_heroes.gd),
## doc:<§> = heroes_design.md, derived:<rule> = computed by the generator from the json.
const SOURCE_KEYS: Dictionary[String, String] = {
	"GEMS": "roster:gems.keys",
	"GEM_NAME_UK": "roster:gems.uk",
	"GEM_NAME_EN": "roster:gems.en",
	"HERO_MAX_GEM": "roster:hero_max_gem",
	"CHAMPION_MAX_GEM": "roster:champion_max_gem",
	"Q_NATIVE": "consts:ladder.Q_NATIVE",
	"FACET_STEP": "consts:ladder.FACET_STEP",
	"NATIVE_MULT": "consts:ladder.NATIVE_MULT",
	"RECUT_STEP": "consts:ladder.RECUT_STEP",
	"CEILING": "consts:ladder.CEILING",
	"FACETS_PER_GEM": "consts:ladder.FACETS_PER_GEM",
	"SKILL_BASE": "consts:ladder.SKILL_BASE",
	"FORM_AT_RANK": "consts:ladder.FORM_AT_RANK",
	"AWAKEN_MIN_GEM": "consts:ladder.AWAKEN_MIN_GEM",
	"AWAKEN_CAP": "consts:ladder.AWAKEN_CAP",
	"BORN_AWAKENED_MIN": "consts:ladder.BORN_AWAKENED_MIN",
	"ULT_RANK_STEP": "consts:ladder.ULT_RANK_STEP",
	"ATK_RANK_STEP": "consts:ladder.ATK_RANK_STEP",
	"RALLY_RANK_STEP": "consts:ladder.RALLY_RANK_STEP",
	"LV_DMG": "consts:ladder.LV_DMG",
	"LV_HP": "consts:ladder.LV_HP",
	"LV_RATE": "consts:ladder.LV_RATE",
	"LV_ULT": "consts:ladder.LV_ULT",
	"ATK_BEATS": "roster:atk_beats",
	"AWK_STEP": "consts:budgets.AWK_STEP",
	"AWK_TOL": "consts:budgets.AWK_TOL",
	"FORM_STEP": "consts:budgets.FORM_STEP",
	"FORM_TOL": "consts:budgets.FORM_TOL",
	"ATK_BEAT": "consts:budgets.ATK_BEAT",
	"BEAT_TOL": "consts:budgets.BEAT_TOL",
	"RELIC_BEAT": "consts:budgets.RELIC_BEAT",
	"RELIC_TOL": "consts:budgets.RELIC_TOL",
	"KIT_TOL": "consts:budgets.KIT_TOL",
	"SET4_VALUE": "consts:budgets.SET4_VALUE",
	"U_SHARE": "consts:budgets.U_SHARE",
	"HP_W": "consts:budgets.HP_W",
	"RALLY_W": "consts:budgets.RALLY_W",
}
# </GENERATED>


# ------------------------------------------------------------------ rules (hand-written; §2.2)

## Gem key -> index 0..4 (C R E L M); -1 for an unknown key.
static func gem_index(gem: String) -> int:
	return GEMS.find(gem)


## B1: stat multiplier of a character born `native`, now at `gem` with `facets` (0..5). Multiplies
## hero damage, HP, ult effect and Rally value (champions: HP, Action power, Aura), never rates,
## ranges, radii, cooldowns or counts.
static func mult(native: String, gem: String, facets: int) -> float:
	var n := gem_index(native)
	var g := gem_index(gem)
	return NATIVE_MULT[n] * pow(RECUT_STEP, g - n) * (1.0 + FACET_STEP * facets)


## B2 (F-CAP): the rank cap of Ult / Attack / Rally. A recut is always one cap below a native of
## its current gem; Full facets add one.
static func skill_cap(native: String, gem: String, facets: int) -> int:
	var g := gem_index(gem)
	return SKILL_BASE[g] - (1 if g > gem_index(native) else 0) + (1 if facets == FACETS_PER_GEM else 0)


## B3: the ult form (1..5 = I..V) at Ult `rank`; never above the native gem's form.
static func ult_form(native: String, rank: int) -> int:
	var reached := 0
	for r: int in FORM_AT_RANK:
		if rank >= r:
			reached += 1
	return mini(gem_index(native) + 1, reached)


## B3: the highest ult form a character born `native` can ever reach.
static func max_form(native: String) -> int:
	return gem_index(native) + 1


## B4 (F-AWK2): Awakening is open at Full facets in Amethyst+, and native Topaz / Opal characters
## hold it from the moment they are obtained.
static func can_awaken(native: String, gem: String, facets: int) -> bool:
	var n := gem_index(native)
	var g := gem_index(gem)
	if g < gem_index(AWAKEN_MIN_GEM):
		return false
	return facets == FACETS_PER_GEM or (g == n and n >= gem_index(BORN_AWAKENED_MIN))


## B4: the Awakening rank cap (0 below Amethyst; a recut one below a native of its gem).
static func awaken_cap(native: String, gem: String) -> int:
	if gem_index(gem) < gem_index(AWAKEN_MIN_GEM):
		return 0
	return int(AWAKEN_CAP[gem]) - (1 if gem_index(gem) > gem_index(native) else 0)


## True for a native Topaz / Opal: Awakening rank 1 from the moment it is obtained.
static func born_awakened(native: String) -> bool:
	return gem_index(native) >= gem_index(BORN_AWAKENED_MIN)


## The FROZEN ladder check (§2.2): a recut gains at most CEILING of a native's gem step, so a
## recut never reaches a native of its current gem. Also checks the generated tables' shapes.
static func check() -> bool:
	return (RECUT_STEP <= CEILING * Q_NATIVE + 1e-12
			and absf(RECUT_STEP - (1.0 + FACETS_PER_GEM * FACET_STEP)) < 1e-12
			and NATIVE_MULT.size() == GEMS.size() and SKILL_BASE.size() == GEMS.size()
			and FORM_AT_RANK.size() == GEMS.size())
