class_name PortalData
extends RefCounted
## Heroes & Champions data (heroes_design.md §12.2, WS-A). The block below is generated by
## tools/gen_heroes_data.py from tools/data/heroes_consts.json + heroes_roster.json; hand-written
## helpers go after it. Nothing in the shipped game reads this class before EconData.HEROES_PHASE >= 1.

# <GENERATED by tools/gen_heroes_data.py — edit the json / the generator, never this block>
## Sources: heroes_consts.json sha256 6993c4c2e6e4fd89, heroes_roster.json sha256 a8186af098662605.

# ---- Portal (§7.1 - §7.4; unlock UNLOCK_PORTAL)
const UNLOCK_PORTAL: int = 20
const BASE_ODDS: Dictionary[String, float] = {"C": 0.55, "R": 0.28, "E": 0.12, "L": 0.04, "M": 0.01}
## Amethyst+ certain on the summon number `hard` since the last Amethyst+.
const PITY_E: Dictionary[String, int] = {"hard": 10}
## Topaz+ chance rises by `step` from summon `soft_from`, certain on `hard`.
const PITY_L: Dictionary[String, float] = {"soft_from": 21.0, "step": 0.07, "hard": 30.0}
## Inside a Topaz-or-better result: Opal this share, Topaz the rest.
const OPAL_SHARE_IN_L: float = 0.2
## The Focus hero gets exactly this share of its gem's results once the gem is complete.
const FOCUS_TOTAL: float = 0.6
const SEAL_PRICES: Dictionary[String, int] = {"E": 40, "L": 100, "M": 200}
## An owned Seal pick = this x the hero's DUP_FRAGS.
const OWNED_SEAL_PICK_MULT: int = 2
const WELCOME_X10: Dictionary = {"free": true, "rule": "topaz_plus_in_10"}
## Beacon sources (earned only; §7.3). track = 0: Track nodes never pay Beacons.
const BEACON: Dictionary = {"first_clear": 0.2, "boss": 2, "mission": 0.3333333333333333, "weekly": 4, "exp3": 1, "exp5": 2, "login7": 1, "track_nodes": [5, 10], "track": 0}
## (heroes_design.md §7.1)
const BEACONS_PER_SUMMON: int = 1
## (heroes_design.md §7.1)
const X10_SUMMONS: int = 10
## (heroes_design.md §7.4)
const SEALS_PER_SUMMON: int = 1

# ---- disclosed exact odds ((i) sheet, §7.2 / §7.5), computed by the sim (portal_exact, portal_x10_best,
# chest_exact_best). Read at runtime instead of solving the pity chain on every sheet open (review F3);
# Summon.solve_consolidated / x10_best / HeroChest.exact_best recompute them in tests and tools/odds_table.gd
## Each gem's long-run share of all summons (stationary pity chain).
const ODDS_CONSOLIDATED: Dictionary[String, float] = {"C": 0.5209373930684413, "R": 0.26520449101666094, "E": 0.1435342403492899, "L": 0.056259100452445, "M": 0.01406477511311125}
## Best gem of a ×10 from fresh pity.
const ODDS_X10_FRESH: Dictionary[String, float] = {"E": 0.5987369392383782, "L": 0.30564513577042535, "M": 0.09561792499119544}
## Best gem of the free welcome ×10 (fresh pity: Beacon summons wait for it, Summon.block).
const ODDS_X10_WELCOME: Dictionary[String, float] = {"L": 0.7846346871611276, "M": 0.21536531283887114}
## Best gem of a typical ×10 (stationary pity start).
const ODDS_X10_TYPICAL: Dictionary[String, float] = {"E": 0.4356325289188595, "L": 0.429883009902738, "M": 0.1344844611783501}
## Best card of a Hero / Grand chest without pity.
const CHEST_BEST: Dictionary = {"hero": {"C": 0.3844, "R": 0.4077, "E": 0.1682999999999999, "L": 0.03960000000000008}, "grand": {"C": 0.0, "R": 0.0, "E": 0.785781818181818, "L": 0.21421818181818197}}

# ---- Hero Chests (§7.5; unlock UNLOCK_CHESTS)
const UNLOCK_CHESTS: int = 14
const CHEST_ODDS: Dictionary[String, float] = {"C": 0.62, "R": 0.27, "E": 0.09, "L": 0.02}
const CHEST_PITY_L: int = 15
const CHEST_CHARGE_PER_WIN: float = 0.3333333333333333
const CHEST_REPLAYS_PER_DAY: int = 3
## Kind -> [min, max] Tomes (Grand only, after the skills unlock).
const CHEST_TOMES: Dictionary = {"hero": [0, 0], "grand": [2, 2]}
## Hero-fragment card = round(CHEST_HERO_CARD x DUP_FRAGS[native]) x CHEST_HERO_FRAG_MULT[kind].
const CHEST_HERO_CARD: float = 0.15
const CHEST_CARDS: Dictionary[String, int] = {"hero": 2, "grand": 3}
const CHEST_HERO_FRAG_MULT: Dictionary[String, int] = {"hero": 1, "grand": 2}
const CHEST_FOCUS_TOTAL: float = 0.6
const TOMES_BOSS: int = 1
const TOMES_WEEKLY: int = 2
const TOMES_EXP5: int = 2
## Per native gem, Hero Chest (x CHEST_HERO_FRAG_MULT in a Grand chest); half rounds up like the sim.
const CHEST_HERO_CARD_FRAGS: Array[int] = [2, 2, 4, 8, 15]
## The team hero's weight when the hero-fragment card picks an owned hero. (heroes_design.md §7.5)
const CHEST_TEAM_HERO_WEIGHT: int = 2
## The Grand chest's last card is drawn among this gem and better. (heroes_design.md §7.5)
const GRAND_LAST_CARD_MIN: String = "E"
## CHEST_PITY_L forces a card of this gem. (heroes_design.md §7.5)
const CHEST_PITY_GEM: String = "L"

# ---- scripted chests (§7.5): #1 by the team hero, #2 fixed
const SCRIPTED_FIRST: Dictionary[String, String] = {"bolt": "alba", "titan": "otto"}
const SCRIPTED_FIRST_DEFAULT: String = "otto"
const SCRIPTED_SECOND: String = "mila"

## Where every generated constant comes from: consts:<path> = tools/data/heroes_consts.json,
## roster:<path> = tools/data/heroes_roster.json (both checked by scripts/dev/test_heroes.gd),
## doc:<§> = heroes_design.md, derived:<rule> = computed by the generator from the json.
const SOURCE_KEYS: Dictionary[String, String] = {
	"UNLOCK_PORTAL": "consts:unlocks.portal",
	"BASE_ODDS": "consts:portal.BASE_ODDS",
	"PITY_E": "consts:portal.PITY_E",
	"PITY_L": "consts:portal.PITY_L",
	"OPAL_SHARE_IN_L": "consts:portal.OPAL_SHARE_IN_L",
	"FOCUS_TOTAL": "consts:portal.FOCUS_TOTAL",
	"SEAL_PRICES": "consts:portal.SEAL_PRICES",
	"OWNED_SEAL_PICK_MULT": "consts:portal.OWNED_SEAL_PICK_MULT",
	"WELCOME_X10": "consts:portal.WELCOME_X10",
	"BEACON": "consts:portal.BEACON",
	"BEACONS_PER_SUMMON": "doc:§7.1",
	"X10_SUMMONS": "doc:§7.1",
	"SEALS_PER_SUMMON": "doc:§7.4",
	"ODDS_CONSOLIDATED": "roster:oracle.portal_consolidated",
	"ODDS_X10_FRESH": "roster:oracle.portal_x10_fresh",
	"ODDS_X10_WELCOME": "roster:oracle.portal_x10_welcome",
	"ODDS_X10_TYPICAL": "roster:oracle.portal_x10_stationary",
	"CHEST_BEST": "roster:oracle.chest_best",
	"UNLOCK_CHESTS": "consts:unlocks.champions",
	"CHEST_ODDS": "consts:chests.CHEST_ODDS",
	"CHEST_PITY_L": "consts:chests.CHEST_PITY_L",
	"CHEST_CHARGE_PER_WIN": "consts:chests.CHEST_CHARGE_PER_WIN",
	"CHEST_REPLAYS_PER_DAY": "consts:chests.CHEST_REPLAYS_PER_DAY",
	"CHEST_TOMES": "consts:chests.CHEST_TOMES",
	"CHEST_HERO_CARD": "consts:chests.CHEST_HERO_CARD",
	"CHEST_CARDS": "consts:chests.CHEST_CARDS",
	"CHEST_HERO_FRAG_MULT": "consts:chests.CHEST_HERO_FRAG_MULT",
	"CHEST_FOCUS_TOTAL": "consts:chests.CHEST_FOCUS_TOTAL",
	"TOMES_BOSS": "consts:chests.TOMES_BOSS",
	"TOMES_WEEKLY": "consts:chests.TOMES_WEEKLY",
	"TOMES_EXP5": "consts:chests.TOMES_EXP5",
	"CHEST_HERO_CARD_FRAGS": "derived:round(CHEST_HERO_CARD x DUP_FRAGS)",
	"CHEST_TEAM_HERO_WEIGHT": "doc:§7.5",
	"GRAND_LAST_CARD_MIN": "doc:§7.5",
	"CHEST_PITY_GEM": "doc:§7.5",
	"SCRIPTED_FIRST": "roster:scripted_chests.first",
	"SCRIPTED_FIRST_DEFAULT": "roster:scripted_chests.first_default",
	"SCRIPTED_SECOND": "roster:scripted_chests.second",
}
# </GENERATED>


# ------------------------------------------------------------------ helpers (hand-written)

## Chance that the next summon is Topaz or better after `since_l` summons without one (§7.2:
## base L + M, +PITY_L.step per summon from PITY_L.soft_from, certain on PITY_L.hard).
static func topaz_plus_chance(since_l: int) -> float:
	var n := since_l + 1
	var base := float(BASE_ODDS["L"]) + float(BASE_ODDS["M"])
	if n >= int(PITY_L["hard"]):
		return 1.0
	if n >= int(PITY_L["soft_from"]):
		return minf(1.0, base + float(PITY_L["step"]) * (n - int(PITY_L["soft_from"]) + 1))
	return base


## Seals that buy any eligible hero of `gem` (0 = not for sale: Quartz / Sapphire).
static func seal_price(gem: String) -> int:
	return int(SEAL_PRICES.get(gem, 0))
