class_name SaveV3Data
## GENERATED by tools/gen_save_v3_data.py — do not edit by hand (python3 tools/gen_save_v3_data.py).
## Numbers Save v3 and the v2 -> v3 migration read (heroes_design.md §12.1, §12.3). Sources:
## heroes_consts.json sha256 6993c4c2e6e4fd89, tools/data/heroes_migration.json sha256 481a75840e013f17.
## WS-A's Ladder / HeroData / ChampionData carry the same numbers for the rules; this file only feeds
## the save layer so Save v3 has no load-order dependency on the rule classes.

const GEMS: Array[String] = ["C", "R", "E", "L", "M"]
## Hero id -> native gem (roster order).
const HERO_NATIVE := {"titan": "C", "arin": "C", "bolt": "R", "eira": "R", "seer": "E", "iskar": "E", "vesta": "L", "vartan": "L", "lumen": "M", "pava": "M"}
## Champion id -> native gem (roster order). Champions recut at most to CHAMPION_MAX_GEM.
const CHAMPION_NATIVE := {"mila": "C", "ivo": "C", "borko": "C", "alba": "R", "otto": "R", "taya": "R", "brant": "E", "teo": "E", "olena": "E", "nimb": "L", "dara": "L", "menhir": "L", "taras": "L"}
const CHAMPION_MAX_GEM := "L"
const HERO_MAX_GEM := "M"
const STARTERS: Array[String] = ["titan", "bolt", "seer"]
## Heroes owned by a brand-new account.
const START_OWNED: Array[String] = ["bolt"]

# ---- ladder (heroes_consts.json "ladder")
const FACETS_PER_GEM := 5
const SKILL_BASE: Array[int] = [2, 4, 6, 8, 10]
const AWAKEN_MIN_GEM := "E"
const AWAKEN_CAP := {"E": 2, "L": 3, "M": 4}
const BORN_AWAKENED_MIN := "E"
## Ult power = (1 + ULT_RANK_STEP x (rank - 1)) x (1 + LV_ULT x (lvl - 1)) (no-loss migration check).
const ULT_RANK_STEP := 0.05
const LV_ULT := 0.036

# ---- progress (heroes_consts.json "progress")
## TOME_COST[r] = Tomes for skill rank r -> r + 1.
const TOME_COST: Array[int] = [0, 2, 3, 5, 8, 12, 16, 20, 25, 30, 40]
const CHAMP_LEVEL_MAX := 20

# ---- unlock levels (heroes_consts.json "unlocks"; after_win)
const UNLOCK_AT := {"champions": 14, "portal": 20, "seer": 24, "skills": 30, "workshop": 32, "slot3": 40}

# ---- lump grant on update day (heroes_design.md §12.3 step 3 = heroes_sim.migrate_grant)
## Frontier L = next level to play - FRONTIER_OFFSET (the last level cleared).
const FRONTIER_OFFSET := 1
const BEACON_FIRST_CLEAR := 0.2
const BEACON_BOSS := 2
const BEACON_CAP := 60
const HERO_CHEST_CAP := 20
const HERO_CHEST_EVERY := 3
const TOMES_BOSS := 1
## Star Ore per Glory step above 1 (credited at the Workshop unlock; heroes_design.md §12.3 step 2).
const ORE_PER_GLORY_STEP := 10
const CAMPAIGN_LEVELS := 56
const BOSS_LEVELS: Array[int] = [8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112]
## EXPECTED Champion Level at frontier L (index 0..112), median of the sim's casual EXPECTED-only runs.
const EXPECTED_CHAMPION_LEVEL: Array[int] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13]
