class_name TeamData
extends RefCounted
## Heroes & Champions data (heroes_design.md §12.2, WS-A). The block below is generated by
## tools/gen_heroes_data.py from tools/data/heroes_consts.json + heroes_roster.json; hand-written
## helpers go after it. Nothing in the shipped game reads this class before EconData.HEROES_PHASE >= 1.

# <GENERATED by tools/gen_heroes_data.py — edit the json / the generator, never this block>
## Sources: heroes_consts.json sha256 6993c4c2e6e4fd89, heroes_roster.json sha256 dae7c1d01db2a96f.

# ---- tags (§5.1 - §5.3)
## (heroes_design.md §5.1)
const CLASSES: Array[String] = ["warrior", "ranger", "mage", "guardian", "healer"]
## = ArsenalData.FAMILY_ORDER without rift. (heroes_design.md §5.2)
const ELEMENTS: Array[String] = ["kinetic", "volt", "frost", "plasma", "tech", "rune"]
const FACTIONS: Array[String] = ["dawn", "wildfang", "stoneheart", "celestial"]
## Faction -> home worlds.
const FACTION_HOME: Dictionary = {"dawn": [1, 6], "wildfang": [2, 3], "stoneheart": [4, 5], "celestial": [7]}

# ---- synergy as power-index terms (heroes_sim / Might; NOT the run effects)
## Index term per tier 0..III (dawn / stoneheart: army term; wildfang:
## ult charge x; celestial: machine damage, bucket 2).
const FACTION_TIERS: Dictionary = {"dawn": [0.0, 0.02, 0.04, 0.07], "wildfang": [1.0, 1.06, 1.12, 1.2], "stoneheart": [0.0, 0.02, 0.04, 0.06], "celestial": [0.0, 0.03, 0.06, 0.1]}
## Affinity: fielded machines of element E +AFFINITY_PER x living members
## of E (bucket 2), cap AFFINITY_CAP.
const AFFINITY_PER: float = 0.03
const AFFINITY_CAP: float = 0.09
## Celestials + Affinity + Rally machine hooks add at most this to one machine.
const TEAM_B2_CAP: float = 0.2
## Class -> [index stat, value] for 2 of the class.
const CLASS_PAIR: Dictionary = {"warrior": ["army", 0.03], "ranger": ["rate", 1.05], "mage": ["ultp", 1.08], "guardian": ["champ_all", 1.05], "healer": ["army", 0.02]}
## Class pair -> champion index x for that class (Guardian: Block cooldown -20%, Ranger: cooldown -15%).
const CHAMP_CLS_PAIR: Dictionary[String, float] = {"guardian": 1.1, "ranger": 1.1}
## Account power weights of the sim (§8.1: machines · hero · army) and the
## bucket-2 efficiency of machine synergy (Team.score / Auto-team).
const POWER_W: Dictionary[String, float] = {"mach": 0.5, "hero": 0.25, "army": 0.25, "b2_eff": 0.8}

# ---- synergy effects in the run (§5.1, §5.3)
## Faction -> {stat, tiers [none, I, II, III]}. (heroes_design.md §5.3)
const FACTION_RUN: Dictionary = {"dawn": {"stat": "siege_reserves", "tiers": [0, 4, 8, 14]}, "wildfang": {"stat": "ult_charge", "tiers": [0.0, 0.06, 0.12, 0.2]}, "stoneheart": {"stat": "hazard_losses", "tiers": [0.0, -0.15, -0.3, -0.45]}, "celestial": {"stat": "machine_damage_b2", "tiers": [0.0, 0.03, 0.06, 0.1]}}
## Living members needed for tier 0..III. (heroes_design.md §5.3)
const FACTION_MEMBERS_FOR_TIER: Array[int] = [0, 2, 3, 4]
## Class -> run effects with 2 of the class. (heroes_design.md §5.1)
const CLASS_PAIR_RUN: Dictionary = {"warrior": {"squad_clash_loss": 0.12}, "ranger": {"hero_rate": 0.05, "ranger_champion_cooldown": -0.15}, "mage": {"ult_effect": 0.08}, "guardian": {"champion_hp": 0.25, "block_cooldown": -0.2}, "healer": {"revive_pool": 0.25, "mend_rate": 0.2}}

# ---- Rally hooks (§5.4): value = base x Ladder.mult(n, g, f) x (1 + RALLY_RANK_STEP (rank - 1))
## Hook -> {target, op (add | mul), base at rank 1, Quartz-normalised}.
const RALLY_HOOKS: Dictionary = {"army_scrape": {"target": "Army.scrape_spare", "op": "add", "base": 3.0}, "army_drill": {"target": "Army.drill_mult", "op": "add", "base": 0.075}, "machines_element": {"target": "Weapons._b2", "op": "add", "base": 0.03}, "champions_hp": {"target": "champion.hp", "op": "mul", "base": 0.15}, "ult_start": {"target": "tactics.ult_start", "op": "add", "base": 0.1}, "machines_verb": {"target": "Weapons._b2", "op": "add", "base": 0.025}, "army_reserves": {"target": "Army.reserves", "op": "add", "base": 6.0}, "army_volleys": {"target": "Army.volley_mult", "op": "mul", "base": 0.15}, "champions_aura": {"target": "champion.aura", "op": "mul", "base": 0.06}, "army_recruits": {"target": "Army.recruits", "op": "add", "base": 1.0}, "ult_charge": {"target": "ult.charge_rate", "op": "mul", "base": 0.05}}
## Total tactics.ult_start never exceeds this. (heroes_design.md §5.4)
const ULT_START_CAP: float = 0.4

# ---- difficulty re-bake (§8.2): LevelGen enemy budget multiplier per world
## World (as a string key, like the json) -> multiplier on the EXPECTED profile.
const TEAM_DEMAND: Dictionary[String, float] = {"1": 1.028, "2": 1.03, "3": 1.054, "4": 1.07, "5": 1.111, "6": 1.123, "7": 1.158, "8": 1.133, "9": 1.124, "10": 1.135, "11": 1.135, "12": 1.131, "13": 1.132, "14": 1.122}

## Where every generated constant comes from: consts:<path> = tools/data/heroes_consts.json,
## roster:<path> = tools/data/heroes_roster.json (both checked by scripts/dev/test_heroes.gd),
## doc:<§> = heroes_design.md, derived:<rule> = computed by the generator from the json.
const SOURCE_KEYS: Dictionary[String, String] = {
	"CLASSES": "doc:§5.1",
	"ELEMENTS": "doc:§5.2",
	"FACTIONS": "roster:factions",
	"FACTION_HOME": "roster:faction_home",
	"FACTION_TIERS": "consts:team.FACTION_TIERS",
	"AFFINITY_PER": "consts:team.AFFINITY_PER",
	"AFFINITY_CAP": "consts:team.AFFINITY_CAP",
	"TEAM_B2_CAP": "consts:team.TEAM_B2_CAP",
	"CLASS_PAIR": "consts:team.CLASS_PAIR",
	"CHAMP_CLS_PAIR": "roster:index_terms.champ_cls_pair",
	"POWER_W": "roster:index_terms.power_w",
	"FACTION_RUN": "doc:§5.3",
	"FACTION_MEMBERS_FOR_TIER": "doc:§5.3",
	"CLASS_PAIR_RUN": "doc:§5.1",
	"RALLY_HOOKS": "derived:roster heroes.*.rally.base + doc §5.4 targets",
	"ULT_START_CAP": "doc:§5.4",
	"TEAM_DEMAND": "consts:team_demand",
}
# </GENERATED>
